{
 "title": "Hashicorp Vault",
 "description": "Hashicorp Vault metrics",
 "tags": [ "vault" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Prometheus data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(vault_core_active, job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(vault_core_active{job=~\"$job\"}, instance)"
    }
   },
   {
    "name": "mountpoint",
    "label": "mountpoint",
    "query": {
     "query": "label_values(vault_secret_kv_count{job=~\"$job\",instance=~\"$instance\"}, mount_point)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Healthy status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Misc" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Secrets",
   "type": "table",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "last_over_time(vault_secret_kv_count{job=~\"$job\", instance=~\"$instance\", mount_point=~\"$mountpoint/\"}[$__range])",
     "legendFormat": "{{ mount_point }}"
    }
   ]
  },
  {
   "title": "Number of identity entities",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(vault_identity_num_entities{job=~\"$job\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Identity entities aliases by method",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 0 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg without(instance) (vault_identity_entity_alias_count{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{ auth_method }}"
    }
   ]
  },
  {
   "title": "Sealed status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(1 + vault_core_unsealed{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Number of leases",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(vault_expire_num_leases{job=~\"$job\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Path info $mountpoint",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "repeat": "mountpoint",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Number of operations / $__interval",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase({__name__=\"vault_route_create_${mountpoint}__count\",job=~\"$job\", instance=~\"$instance\"}[$__interval]))",
       "legendFormat": "Create"
      },
      {
       "expr": "sum(increase({__name__=\"vault_route_delete_${mountpoint}__count\",job=~\"$job\", instance=~\"$instance\"}[$__interval]))",
       "legendFormat": "Delete"
      },
      {
       "expr": "sum(increase({__name__=\"vault_route_read_${mountpoint}__count\",job=~\"$job\", instance=~\"$instance\"}[$__interval]))",
       "legendFormat": "Read"
      },
      {
       "expr": "sum(increase({__name__=\"vault_route_list_${mountpoint}__count\",job=~\"$job\", instance=~\"$instance\"}[$__interval]))",
       "legendFormat": "List"
      },
      {
       "expr": "sum(increase({__name__=\"vault_route_rollback_${mountpoint}__count\",job=~\"$job\", instance=~\"$instance\"}[$__interval]))",
       "legendFormat": "Rollback"
      }
     ]
    },
    {
     "title": "Time of operations in \"$mountpoint\"",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "avg(rate(vault_route_create_${mountpoint}__sum{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]) / rate(vault_route_create_${mountpoint}__count{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]) * 1000)",
       "legendFormat": "Create"
      },
      {
       "expr": "avg(rate(vault_route_delete_${mountpoint}__sum{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]) / rate(vault_route_delete_${mountpoint}__count{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]) * 1000)",
       "legendFormat": "Delete"
      },
      {
       "expr": "avg(rate(vault_route_read_${mountpoint}__sum{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]) / rate(vault_route_read_${mountpoint}__count{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]) * 1000)",
       "legendFormat": "Read"
      },
      {
       "expr": "avg(rate(vault_route_list_${mountpoint}__sum{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]) / rate(vault_route_list_${mountpoint}__count{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]) * 1000)",
       "legendFormat": "List"
      }
     ]
    }
   ]
  },
  {
   "title": "Resource usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Heap objects used",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(vault_runtime_heap_objects{job=~\"$job\", instance=~\"$instance\"} / vault_runtime_malloc_count{job=~\"$job\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(vault_runtime_num_goroutines{job=~\"$job\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Allocated bytes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(vault_runtime_alloc_bytes{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "Allocated bytes"
    }
   ]
  },
  {
   "title": "Tokens",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Available tokens",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(vault_token_count{job=~\"$job\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Tokens by policy",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(policy) (vault_token_count_by_policy{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{ policy }}"
    }
   ]
  },
  {
   "title": "Pending tokens",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(vault_token_create_count{job=~\"$job\", instance=~\"$instance\"} - vault_token_store_count{job=~\"$job\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Tokens by TTL",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(creation_ttl) (vault_token_count_by_ttl{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{ creation_ttl }}"
    }
   ]
  },
  {
   "title": "Tokens by auth method",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(auth_method) (vault_token_count_by_auth{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{ auth_method }}"
    }
   ]
  },
  {
   "title": "Tokens creation by method and TTL",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by(auth_method, creation_ttl) (sum_over_time(vault_token_creation{job=~\"$job\", instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "{{ auth_method }} - {{ creation_ttl }}"
    }
   ]
  },
  {
   "title": "Token creation/storage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "avg without(instance) (vault_token_create_count{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "Create"
    },
    {
     "expr": "avg without(instance) (vault_token_store_count{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "Store"
    }
   ]
  },
  {
   "title": "Token lookups",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(irate(vault_token_lookup_count{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Lookups"
    }
   ]
  },
  {
   "title": "Audit",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Log request failures",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(idelta(vault_audit_log_request_failure{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "Log requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 3, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(irate(vault_audit_log_request_count{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Request "
    },
    {
     "expr": "avg(irate(vault_audit_log_response_count{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Response"
    },
    {
     "expr": "avg(irate(vault_core_handle_request_count{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Handled"
    }
   ]
  },
  {
   "title": "Consul requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(irate(vault_consul_get_count{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "GET"
    },
    {
     "expr": "avg(irate(vault_consul_put_count{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "PUT"
    },
    {
     "expr": "avg(irate(vault_consul_delete_count{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "DELETE"
    },
    {
     "expr": "irate(vault_consul_list_count{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "LIST"
    }
   ]
  },
  {
   "title": "Log response failures",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(idelta(vault_audit_log_response_failure{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "Policy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Policy set",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(irate(vault_policy_set_policy_count{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "SET"
    }
   ]
  },
  {
   "title": "Policy get",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(irate(vault_policy_get_policy_count{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "GET"
    }
   ]
  }
 ]
}