{
 "title": "F5 BIG-IP node overview",
 "tags": [ "f5-bigip-mixin" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(bigip_node_status_availability_state{}, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(bigip_node_status_availability_state{job=~\"$job\"}, instance)"
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" },
   {
    "name": "bigip_node",
    "label": "BIG-IP node",
    "query": "label_values(bigip_node_status_availability_state{}, node)"
   },
   {
    "name": "bigip_partition",
    "label": "BIG-IP partition",
    "query": "label_values(bigip_node_status_availability_state{node=~\"$bigip_node\"}, partition)"
   }
  ]
 },
 "panels": [
  { "title": "Node overview", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Availability status",
   "type": "table",
   "description": "The availability status of the node.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "bigip_node_status_availability_state{job=~\"$job\",instance=~\"$instance\", node=~\"$bigip_node\", partition=~\"$bigip_partition\"}",
     "legendFormat": "{{node}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Requests / $__interval",
   "type": "timeseries",
   "description": "The number of requests made to the node.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(bigip_node_tot_requests{job=~\"$job\",instance=~\"$instance\", node=~\"$bigip_node\", partition=~\"$bigip_partition\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{node}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Active sessions",
   "type": "timeseries",
   "description": "The current number of active sessions to the node.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "bigip_node_cur_sessions{job=~\"$job\",instance=~\"$instance\", node=~\"$bigip_node\", partition=~\"$bigip_partition\"}",
     "legendFormat": "{{node}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "description": "The current active server-side connections to the node in comparison to the maximum connection capacity.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "bigip_node_serverside_cur_conns{job=~\"$job\",instance=~\"$instance\", node=~\"$bigip_node\", partition=~\"$bigip_partition\"}",
     "legendFormat": "{{node}} - {{instance}} - current"
    },
    {
     "expr": "bigip_node_serverside_max_conns{job=~\"$job\",instance=~\"$instance\", node=~\"$bigip_node\", partition=~\"$bigip_partition\"}",
     "legendFormat": "{{node}} - {{instance}} - max"
    }
   ]
  },
  {
   "title": "Traffic inbound",
   "type": "timeseries",
   "description": "The rate of data received from the pool by the node.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(bigip_node_serverside_bytes_in{job=~\"$job\",instance=~\"$instance\", node=~\"$bigip_node\", partition=~\"$bigip_partition\"}[$__rate_interval])",
     "legendFormat": "{{node}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Traffic outbound",
   "type": "timeseries",
   "description": "The rate of data sent from the pool by the node.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(bigip_node_serverside_bytes_out{job=~\"$job\",instance=~\"$instance\", node=~\"$bigip_node\", partition=~\"$bigip_partition\"}[$__rate_interval])",
     "legendFormat": "{{node}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Packets inbound / $__interval",
   "type": "timeseries",
   "description": "The number of packets received by the node from the pool.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(bigip_node_serverside_pkts_in{job=~\"$job\",instance=~\"$instance\", node=~\"$bigip_node\", partition=~\"$bigip_partition\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{node}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Packets outbound / $__interval",
   "type": "timeseries",
   "description": "The number of packets sent by the node from the pool.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(bigip_node_serverside_pkts_out{job=~\"$job\",instance=~\"$instance\", node=~\"$bigip_node\", partition=~\"$bigip_partition\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{node}} - {{instance}}"
    }
   ]
  }
 ]
}