{
 "title": "F5 BIG-IP cluster overview",
 "tags": [ "f5-bigip-mixin" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(bigip_node_status_availability_state{}, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(bigip_node_status_availability_state{job=~\"$job\"}, instance)"
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" },
   { "name": "k", "label": "Top node count", "query": "5 : 5,10 : 10,20 : 20,50 : 50" },
   {
    "name": "bigip_partition",
    "label": "BIG-IP partition",
    "query": "label_values(bigip_node_status_availability_state{}, partition)"
   }
  ]
 },
 "panels": [
  { "title": "Cluster overview", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Node availability",
   "type": "gauge",
   "description": "The percentage of nodes available.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * sum by (job,instance,partition) (bigip_node_status_availability_state{job=~\"$job\",instance=~\"$instance\"}) / clamp_min(count by (job,instance,partition) (bigip_node_status_availability_state{job=~\"$job\",instance=~\"$instance\"}),1)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Pool availability",
   "type": "gauge",
   "description": "The percentage of pools available.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * sum by (job,instance,partition) (bigip_pool_status_availability_state{job=~\"$job\",instance=~\"$instance\"}) / clamp_min(count by (job,instance,partition) (bigip_pool_status_availability_state{job=~\"$job\",instance=~\"$instance\"}),1)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Virtual server availability",
   "type": "gauge",
   "description": "The percentage of virtual servers available.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * sum by (job,instance,partition) (bigip_vs_status_availability_state{job=~\"$job\",instance=~\"$instance\"}) / clamp_min(count by (job,instance,partition) (bigip_vs_status_availability_state{job=~\"$job\",instance=~\"$instance\"}),1)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Top active server-side nodes",
   "type": "bargauge",
   "description": "Nodes with the highest number of active server-side connections.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk($k, bigip_node_serverside_cur_conns{job=~\"$job\",instance=~\"$instance\", partition=~\"$bigip_partition\"})",
     "legendFormat": "{{node}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Top outbound traffic nodes / $__interval",
   "type": "bargauge",
   "description": "Nodes with the highest outbound traffic.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "topk($k, increase(bigip_node_serverside_bytes_out{job=~\"$job\",instance=~\"$instance\", partition=~\"$bigip_partition\"}[$__interval:] offset -$__interval))",
     "legendFormat": "{{node}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Top active members in pools",
   "type": "bargauge",
   "description": "Pools with the highest number of active members.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk($k, bigip_pool_active_member_cnt{job=~\"$job\",instance=~\"$instance\", partition=~\"$bigip_partition\"})",
     "legendFormat": "{{pool}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Top requested pools / $__interval",
   "type": "bargauge",
   "description": "Pools with the highest number of requests.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk($k, increase(bigip_pool_tot_requests{job=~\"$job\",instance=~\"$instance\", partition=~\"$bigip_partition\"}[$__interval:] offset -$__interval))",
     "legendFormat": "{{pool}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Top queue depth",
   "type": "bargauge",
   "description": "Pools with the largest connection queues.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk($k, bigip_pool_connq_depth{job=~\"$job\",instance=~\"$instance\", partition=~\"$bigip_partition\"})",
     "legendFormat": "{{pool}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Top utilized virtual servers / $__interval",
   "type": "bargauge",
   "description": "Virtual servers with the highest traffic (inbound and outbound).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "topk($k, increase(bigip_vs_clientside_bytes_in{job=~\"$job\",instance=~\"$instance\", partition=~\"$bigip_partition\"}[$__interval:] offset -$__interval)) + topk($k, increase(bigip_vs_clientside_bytes_out{job=~\"$job\",instance=~\"$instance\", partition=~\"$bigip_partition\"}[$__interval:] offset -$__interval))",
     "legendFormat": "{{vs}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Top latency virtual servers",
   "type": "bargauge",
   "description": "Virtual servers with the highest response times.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk($k, bigip_vs_cs_mean_conn_dur{job=~\"$job\",instance=~\"$instance\", partition=~\"$bigip_partition\"})",
     "legendFormat": "{{vs}} - {{instance}}"
    }
   ]
  }
 ]
}