{
 "title": "F5 BIG-IP virtual server overview",
 "tags": [ "f5-bigip-mixin" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(bigip_node_status_availability_state{}, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(bigip_node_status_availability_state{job=~\"$job\"}, instance)"
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" },
   {
    "name": "bigip_vs",
    "label": "BIG-IP virtual server",
    "query": "label_values(bigip_vs_status_availability_state{}, vs)"
   },
   {
    "name": "bigip_partition",
    "label": "BIG-IP partition",
    "query": "label_values(bigip_vs_status_availability_state{, vs=~\"$bigip_vs\"}, partition)"
   }
  ]
 },
 "panels": [
  { "title": "Virtual server overview", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Availability status",
   "type": "table",
   "description": "The availability status of the virtual server.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "bigip_vs_status_availability_state{job=~\"$job\",instance=~\"$instance\", vs=~\"$bigip_vs\", partition=~\"$bigip_partition\"}",
     "legendFormat": "{{vs}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Requests / $__interval",
   "type": "timeseries",
   "description": "The number of requests made to the virtual server.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(bigip_vs_tot_requests{job=~\"$job\",instance=~\"$instance\", vs=~\"$bigip_vs\", partition=~\"$bigip_partition\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{vs}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Average connection duration",
   "type": "timeseries",
   "description": "The average connection duration within the virtual server.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "bigip_vs_cs_mean_conn_dur{job=~\"$job\",instance=~\"$instance\", vs=~\"$bigip_vs\", partition=~\"$bigip_partition\"}",
     "legendFormat": "{{vs}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "description": "The evicted and current client-side connections within the virtual server.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "bigip_vs_clientside_cur_conns{job=~\"$job\",instance=~\"$instance\", vs=~\"$bigip_vs\", partition=~\"$bigip_partition\"}",
     "legendFormat": "{{vs}} - {{instance}} - current"
    },
    {
     "expr": "bigip_vs_clientside_max_conns{job=~\"$job\",instance=~\"$instance\", vs=~\"$bigip_vs\", partition=~\"$bigip_partition\"}",
     "legendFormat": "{{vs}} - {{instance}} - max"
    },
    {
     "expr": "bigip_vs_clientside_evicted_conns{job=~\"$job\",instance=~\"$instance\", vs=~\"$bigip_vs\", partition=~\"$bigip_partition\"}",
     "legendFormat": "{{vs}} - {{instance}} - evicted"
    }
   ]
  },
  {
   "title": "Ephemeral connections",
   "type": "timeseries",
   "description": "The ephemeral evicted and current client-side connections within the virtual server.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "bigip_vs_ephemeral_cur_conns{job=~\"$job\",instance=~\"$instance\", vs=~\"$bigip_vs\", partition=~\"$bigip_partition\"}",
     "legendFormat": "{{vs}} - {{instance}} - current"
    },
    {
     "expr": "bigip_vs_ephemeral_max_conns{job=~\"$job\",instance=~\"$instance\", vs=~\"$bigip_vs\", partition=~\"$bigip_partition\"}",
     "legendFormat": "{{vs}} - {{instance}} - max"
    },
    {
     "expr": "bigip_vs_ephemeral_evicted_conns{job=~\"$job\",instance=~\"$instance\", vs=~\"$bigip_vs\", partition=~\"$bigip_partition\"}",
     "legendFormat": "{{vs}} - {{instance}} - evicted"
    }
   ]
  },
  {
   "title": "Traffic inbound",
   "type": "timeseries",
   "description": "The rate of data received from clients by the virtual server.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(bigip_vs_clientside_bytes_in{job=~\"$job\",instance=~\"$instance\", vs=~\"$bigip_vs\", partition=~\"$bigip_partition\"}[$__rate_interval])",
     "legendFormat": "{{vs}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Traffic outbound",
   "type": "timeseries",
   "description": "The rate of data sent from clients by the virtual server.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(bigip_vs_clientside_bytes_out{job=~\"$job\",instance=~\"$instance\", vs=~\"$bigip_vs\", partition=~\"$bigip_partition\"}[$__rate_interval])",
     "legendFormat": "{{vs}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Ephemeral traffic inbound",
   "type": "timeseries",
   "description": "The rate of ephemeral data received from clients by the virtual server.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(bigip_vs_ephemeral_bytes_in{job=~\"$job\",instance=~\"$instance\", vs=~\"$bigip_vs\", partition=~\"$bigip_partition\"}[$__rate_interval])",
     "legendFormat": "{{vs}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Ephemeral traffic outbound",
   "type": "timeseries",
   "description": "The rate of ephemeral data sent from clients by the virtual server.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(bigip_vs_ephemeral_bytes_out{job=~\"$job\",instance=~\"$instance\", vs=~\"$bigip_vs\", partition=~\"$bigip_partition\"}[$__rate_interval])",
     "legendFormat": "{{vs}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Packets inbound / $__interval",
   "type": "timeseries",
   "description": "The number of packets received by the virtual server.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(bigip_vs_clientside_pkts_in{job=~\"$job\",instance=~\"$instance\", vs=~\"$bigip_vs\", partition=~\"$bigip_partition\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{vs}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Packets outbound / $__interval",
   "type": "timeseries",
   "description": "The number of packets sent by the virtual server.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(bigip_vs_clientside_pkts_out{job=~\"$job\",instance=~\"$instance\", vs=~\"$bigip_vs\", partition=~\"$bigip_partition\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{vs}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Ephemeral packets inbound / $__interval",
   "type": "timeseries",
   "description": "The number of ephemeral packets received by the virtual server.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(bigip_vs_ephemeral_pkts_in{job=~\"$job\",instance=~\"$instance\", vs=~\"$bigip_vs\", partition=~\"$bigip_partition\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{vs}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Ephemeral packets outbound / $__interval",
   "type": "timeseries",
   "description": "The number of ephemeral packets sent by the virtual server.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(bigip_vs_ephemeral_pkts_out{job=~\"$job\",instance=~\"$instance\", vs=~\"$bigip_vs\", partition=~\"$bigip_partition\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{vs}} - {{instance}}"
    }
   ]
  }
 ]
}