{
 "title": "NSQ Topics",
 "tags": [ "nsq" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "job",
    "label": "job",
    "query": "label_values(nsq_topic_message_count, job)"
   },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(nsq_topic_message_count{job=~\"$job\"},instance)"
   },
   {
    "name": "topic",
    "query": "label_values(nsq_topic_message_count{job=~\"$job\",instance=~\"$instance\"},topic)"
   },
   {
    "name": "channel",
    "query": "label_values(nsq_topic_channel_message_count{job=~\"$job\",instance=~\"$instance\",topic=~\"$topic\"},channel)"
   }
  ]
 },
 "panels": [
  { "title": "Topics", "type": "row", "gridPos": { "h": 0, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Topic end-to-end processing time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg without (instance) (nsq_topic_e2e_processing_latency_99{job=~\"$job\", instance=~\"$instance\",topic=~\"$topic\"})",
     "legendFormat": "{{topic}} p99"
    }
   ]
  },
  {
   "title": "Topic messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (topic) (rate(nsq_topic_message_count{job=~\"$job\", instance=~\"$instance\",topic=~\"$topic\"}[$__rate_interval]))",
     "legendFormat": "{{topic}} rps"
    },
    {
     "expr": "sum by () (rate(nsq_topic_message_bytes{job=~\"$job\", instance=~\"$instance\",topic=~\"$topic\"}[$__rate_interval]))",
     "legendFormat": "selected topics Bps rate"
    }
   ]
  },
  {
   "title": "Topic depth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without (instance) (nsq_topic_depth{job=~\"$job\", instance=~\"$instance\",topic=~\"$topic\"})",
     "legendFormat": "{{topic}} depth"
    },
    {
     "expr": "sum without (instance) (nsq_topic_backend_depth{job=~\"$job\", instance=~\"$instance\",topic=~\"$topic\"})",
     "legendFormat": "{{topic}} memory+disk depth"
    }
   ]
  },
  { "title": "Channels", "type": "row", "gridPos": { "h": 0, "w": 0, "x": 0, "y": 14 } },
  {
   "title": "Channel end-to-end processing time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg without (instance) (nsq_topic_channel_e2e_processing_latency_99{job=~\"$job\", instance=~\"$instance\",topic=~\"$topic\",channel=~\"$channel\"})",
     "legendFormat": "{{topic}}/{{channel}} p99"
    }
   ]
  },
  {
   "title": "Channel clients",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without (instance) (nsq_topic_channel_clients{job=~\"$job\", instance=~\"$instance\",topic=~\"$topic\",channel=~\"$channel\"})",
     "legendFormat": "{{topic}}/{{channel}}"
    }
   ]
  },
  {
   "title": "Channel stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without (instance) (nsq_topic_channel_depth{job=~\"$job\", instance=~\"$instance\",topic=~\"$topic\",channel=~\"$channel\"})",
     "legendFormat": "{{topic}}/{{channel}} depth"
    },
    {
     "expr": "sum without (instance) (nsq_topic_channel_backend_depth{job=~\"$job\", instance=~\"$instance\",topic=~\"$topic\",channel=~\"$channel\"})",
     "legendFormat": "{{topic}}/{{channel}} memory+disk depth"
    },
    {
     "expr": "sum without (instance) (nsq_topic_channel_in_flight_count{job=~\"$job\", instance=~\"$instance\",topic=~\"$topic\",channel=~\"$channel\"})",
     "legendFormat": "{{topic}}/{{channel}} in-flight"
    },
    {
     "expr": "avg without (instance) (rate(nsq_topic_channel_requeue_count{job=~\"$job\", instance=~\"$instance\",topic=~\"$topic\",channel=~\"$channel\"}[$__rate_interval]))",
     "legendFormat": "{{topic}}/{{channel}} requeue"
    },
    {
     "expr": "avg without (instance) (rate(nsq_topic_channel_timeout_count{job=~\"$job\", instance=~\"$instance\",topic=~\"$topic\",channel=~\"$channel\"}[$__rate_interval]))",
     "legendFormat": "{{topic}}/{{channel}} timeout"
    },
    {
     "expr": "sum without (instance) (nsq_topic_channel_deferred_count{job=~\"$job\", instance=~\"$instance\",topic=~\"$topic\",channel=~\"$channel\"})",
     "legendFormat": "{{topic}}/{{channel}} deferred"
    }
   ]
  }
 ]
}