{
 "title": "Tailscale / Machine",
 "description": "A dashboard that gives an overview of Tailscale Machine daemon metrics. The dashboards were generated using [tailscale-mixin](https://github.com/adinhodovic/tailscale-exporter/tree/main/tailscale-mixin). Open issues and create feature requests in the repository.",
 "tags": [
  "tailscale",
  "tailscale-mixin"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(tailscaled_health_messages, cluster)"
   },
   {
    "name": "job",
    "label": "job",
    "query": "label_values(tailscaled_health_messages{cluster=\"$cluster\"}, job)"
   },
   {
    "name": "tailscale_machine",
    "label": "Tailscale Machine",
    "query": "label_values(tailscaled_health_messages{cluster=\"$cluster\", job=~\"$job\"}, tailscale_machine)"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Tailscale Machines",
   "type": "stat",
   "description": "A stat panel showing the number of Tailscale machines reporting to the selected Tailscale control plane.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(\n  tailscaled_health_messages{\n    cluster=\"$cluster\"\n,\njob=~\"$job\"\n\n  }\n)\n"
    }
   ]
  },
  {
   "title": "Advertised / Approved Routes",
   "type": "piechart",
   "description": "A pie chart panel showing the number of advertised and approved routes for the selected Tailscale machines.",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  tailscaled_advertised_routes{\n    cluster=\"$cluster\"\n,\njob=~\"$job\"\n\n  }\n)\n",
     "legendFormat": "Advertised"
    },
    {
     "expr": "sum(\n  tailscaled_approved_routes{\n    cluster=\"$cluster\"\n,\njob=~\"$job\"\n\n  }\n)\n",
     "legendFormat": "Approved"
    }
   ]
  },
  {
   "title": "Paths Distribution Inbound [1h]",
   "type": "piechart",
   "description": "A pie chart panel showing the distribution of outbound paths for the selected Tailscale machines.",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    tailscaled_inbound_bytes_total{\n      cluster=\"$cluster\"\n,\njob=~\"$job\"\n\n    }[1h]\n  )\n) by (path)\n",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Paths Distribution Outbound [1h]",
   "type": "piechart",
   "description": "A pie chart panel showing the distribution of inbound paths for the selected Tailscale machines.",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    tailscaled_outbound_bytes_total{\n      cluster=\"$cluster\"\n,\njob=~\"$job\"\n\n    }[1h]\n  )\n) by (path)\n",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Inbound vs Outbound Traffic [1h]",
   "type": "piechart",
   "description": "A pie chart panel showing the distribution of outbound paths for the selected Tailscale machines.",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    tailscaled_inbound_bytes_total{\n      cluster=\"$cluster\"\n,\njob=~\"$job\"\n\n    }[1h]\n  )\n)\n",
     "legendFormat": "Inbound"
    },
    {
     "expr": "sum(\n  rate(\n    tailscaled_outbound_bytes_total{\n      cluster=\"$cluster\"\n,\njob=~\"$job\"\n\n    }[1h]\n  )\n)\n",
     "legendFormat": "Outbound"
    }
   ]
  },
  {
   "title": "Dropped Packets by Reason [1h]",
   "type": "piechart",
   "description": "A pie chart panel showing the distribution of dropped packets by reason for the selected Tailscale machines.",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    tailscaled_outbound_dropped_packets_total{\n      cluster=\"$cluster\"\n,\njob=~\"$job\"\n\n    }[1h]\n  )\n) by (reason)\n",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "Top 20 Machines by Inbound Traffic (1h)",
   "type": "table",
   "description": "A table panel showing the top 20 Tailscale machines by inbound traffic over the last hour.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "topk(\n  20,\n  sum(\n    rate(\n      tailscaled_inbound_bytes_total{\n        cluster=\"$cluster\"\n,\njob=~\"$job\"\n\n      }[1h]\n    )\n  ) by (tailscale_machine)\n)\n"
    }
   ]
  },
  {
   "title": "Machines with Unapproved Routes",
   "type": "table",
   "description": "A table panel showing the Tailscale machines with unadvertised routes.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  tailscaled_advertised_routes{\n    cluster=\"$cluster\"\n,\njob=~\"$job\"\n\n  }\n) by (tailscale_machine)\n-\nsum(\n  tailscaled_approved_routes{\n    cluster=\"$cluster\"\n,\njob=~\"$job\"\n\n  }\n) by (tailscale_machine)\n> 0\n"
    }
   ]
  },
  {
   "title": "Machines with Dropped Packets (1h)",
   "type": "table",
   "description": "A table panel showing the Tailscale machines with dropped packets in the last hour.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    tailscaled_outbound_dropped_packets_total{\n      cluster=\"$cluster\"\n,\njob=~\"$job\"\n\n    }[1h]\n  )\n) by (tailscale_machine)\n/\nsum(\n  increase(\n    tailscaled_outbound_packets_total{\n      cluster=\"$cluster\"\n,\njob=~\"$job\"\n\n    }[1h]\n  )\n) by (tailscale_machine)\n* 100\n> 0\n"
    }
   ]
  },
  { "title": "Network Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Health Messages by Type",
   "type": "timeseries",
   "description": "A bar gauge panel showing the number of health messages by type.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  tailscaled_health_messages{\n    cluster=\"$cluster\"\n,\njob=~\"$job\"\n\n  }\n) by (type)\n",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Outbound Dropped Packets by Reason",
   "type": "timeseries",
   "description": "A timeseries panel showing the outbound dropped packets by reason.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    tailscaled_outbound_dropped_packets_total{\n      cluster=\"$cluster\"\n,\njob=~\"$job\"\n\n    }[$__rate_interval]\n  )\n) by (reason)\n",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "Inbound Bytes by Path",
   "type": "timeseries",
   "description": "A timeseries panel showing the inbound bytes by path.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    tailscaled_inbound_bytes_total{\n      cluster=\"$cluster\"\n,\njob=~\"$job\"\n\n    }[$__rate_interval]\n  )\n) by (path)\n",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Inbound Packets by Path",
   "type": "timeseries",
   "description": "A timeseries panel showing the inbound packets by path.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    tailscaled_inbound_packets_total{\n      cluster=\"$cluster\"\n,\njob=~\"$job\"\n\n    }[$__rate_interval]\n  )\n) by (path)\n",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Outbound Bytes by Path",
   "type": "timeseries",
   "description": "A timeseries panel showing the outbound bytes by path.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    tailscaled_outbound_bytes_total{\n      cluster=\"$cluster\"\n,\njob=~\"$job\"\n\n    }[$__rate_interval]\n  )\n) by (path)\n",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Outbound Packets by Path",
   "type": "timeseries",
   "description": "A timeseries panel showing the outbound packets by path.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    tailscaled_outbound_packets_total{\n      cluster=\"$cluster\"\n,\njob=~\"$job\"\n\n    }[$__rate_interval]\n  )\n) by (path)\n",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Tailscale Machine $tailscale_machine",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "repeat": "tailscale_machine"
  },
  {
   "title": "Advertised / Approved Routes",
   "type": "piechart",
   "description": "A pie chart panel showing the number of advertised and approved routes for the selected Tailscale machines.",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  tailscaled_advertised_routes{\n    cluster=\"$cluster\"\n,\njob=~\"$job\"\n,\ntailscale_machine=\"$tailscale_machine\"\n\n  }\n)\n",
     "legendFormat": "Advertised"
    },
    {
     "expr": "sum(\n  tailscaled_approved_routes{\n    cluster=\"$cluster\"\n,\njob=~\"$job\"\n,\ntailscale_machine=\"$tailscale_machine\"\n\n  }\n)\n",
     "legendFormat": "Approved"
    }
   ]
  },
  {
   "title": "DERP vs Non-DERP Outbound Traffic [1h]",
   "type": "piechart",
   "description": "A pie chart panel showing the DERP vs Non-DERP outbound traffic for the selected Tailscale machine.",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    tailscaled_outbound_bytes_total{\n      cluster=\"$cluster\"\n,\njob=~\"$job\"\n,\ntailscale_machine=\"$tailscale_machine\"\n,\n      path=\"derp\"\n    }[1h]\n  )\n)\n",
     "legendFormat": "DERP"
    },
    {
     "expr": "sum(\n  rate(\n    tailscaled_outbound_bytes_total{\n      cluster=\"$cluster\"\n,\njob=~\"$job\"\n,\ntailscale_machine=\"$tailscale_machine\"\n,\n      path!=\"derp\"\n    }[1h]\n  )\n)\n",
     "legendFormat": "Non-DERP"
    }
   ]
  },
  {
   "title": "Dropped Packets by Reason [1h]",
   "type": "piechart",
   "description": "A pie chart panel showing the distribution of dropped packets by reason for the selected Tailscale machines.",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    tailscaled_outbound_dropped_packets_total{\n      cluster=\"$cluster\"\n,\njob=~\"$job\"\n,\ntailscale_machine=\"$tailscale_machine\"\n\n    }[1h]\n  )\n) by (reason)\n",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "Health Messages by Type",
   "type": "timeseries",
   "description": "A bar gauge panel showing the number of health messages by type for the selected Tailscale machine.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  tailscaled_health_messages{\n    cluster=\"$cluster\"\n,\njob=~\"$job\"\n,\ntailscale_machine=\"$tailscale_machine\"\n\n  }\n) by (type)\n",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Outbound Dropped Packets by Reason",
   "type": "timeseries",
   "description": "A timeseries panel showing the outbound dropped packets by reason for the selected Tailscale machine.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    tailscaled_outbound_dropped_packets_total{\n      cluster=\"$cluster\"\n,\njob=~\"$job\"\n,\ntailscale_machine=\"$tailscale_machine\"\n\n    }[$__rate_interval]\n  )\n) by (reason)\n",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "Inbound Bytes by Path",
   "type": "timeseries",
   "description": "A timeseries panel showing the inbound bytes by path for the selected Tailscale machine.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    tailscaled_inbound_bytes_total{\n      cluster=\"$cluster\"\n,\njob=~\"$job\"\n,\ntailscale_machine=\"$tailscale_machine\"\n\n    }[$__rate_interval]\n  )\n) by (path)\n",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Inbound Packets by Path",
   "type": "timeseries",
   "description": "A timeseries panel showing the inbound packets by path for the selected Tailscale machine.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    tailscaled_inbound_packets_total{\n      cluster=\"$cluster\"\n,\njob=~\"$job\"\n,\ntailscale_machine=\"$tailscale_machine\"\n\n    }[$__rate_interval]\n  )\n) by (path)\n",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Outbound Bytes by Path",
   "type": "timeseries",
   "description": "A timeseries panel showing the outbound bytes by path for the selected Tailscale machine.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    tailscaled_outbound_bytes_total{\n      cluster=\"$cluster\"\n,\njob=~\"$job\"\n,\ntailscale_machine=\"$tailscale_machine\"\n\n    }[$__rate_interval]\n  )\n) by (path)\n",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Outbound Packets by Path",
   "type": "timeseries",
   "description": "A timeseries panel showing the outbound packets by path for the selected Tailscale machine.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    tailscaled_outbound_packets_total{\n      cluster=\"$cluster\"\n,\njob=~\"$job\"\n,\ntailscale_machine=\"$tailscale_machine\"\n\n    }[$__rate_interval]\n  )\n) by (path)\n",
     "legendFormat": "{{ path }}"
    }
   ]
  }
 ]
}