{
 "title": "Spinnaker AWS Details",
 "tags": [
  "spinnaker",
  "aws"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "AwsRegion",
    "query": "aws_request_httpRequestTime_seconds_count"
   },
   {
    "name": "Instance",
    "query": "label_values(aws_request_httpRequestTime_seconds_count, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "AWS Delay by Service  (clouddriver, $Instance)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(AWS_delay_sum{instance=~\"$Instance\", statusCode=\"-1\"}) by (serviceName)\n/\nsum(AWS_delay_count{instance=~\"$Instance\", statusCode=\"-1\"}) by (serviceName) , \"serviceName\", \"$1\", \"serviceName\", \"Amazon(.+)\")",
     "legendFormat": "{{serviceName}} / UNK"
    },
    {
     "expr": "label_replace(sum(AWS_delay_sum{instance=~\"$Instance\", statusCode!=\"-1\"}) by (serviceName, statusCode)\n/\nsum(AWS_delay_count{instance=~\"$Instance\", statusCode!=\"-1\"}) by (serviceName, statusCode), \"serviceName\", \"$1\", \"serviceName\", \"Amazon(.+)\") ",
     "legendFormat": "{{serviceName}} / {{statusCode}}"
    }
   ]
  },
  {
   "title": "AWS Delay by Request (clouddriver, $Instance)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(AWS_delay_sum{instance=~\"$Instance\", statusCode=\"-1\"}) by (requestType)\n/\nsum(AWS_delay_count{instance=~\"$Instance\", statusCode=\"-1\"}) by (requestType) ",
     "legendFormat": "{{requestType}} / UNK"
    },
    {
     "expr": "sum(AWS_delay_sum{instance=~\"$Instance\", statusCode!=\"-1\"}) by (requestType, statusCode)\n/\nsum(AWS_delay_count{instance=~\"$Instance\", statusCode!=\"-1\"}) by (requestType, statusCode) ",
     "legendFormat": "{{requestType}} / {{statusCode}}"
    }
   ]
  },
  {
   "title": "AWS Errors by Region (clouddriver, $Instance)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(rate(aws_request_httpRequestTime_seconds_count{instance=~\"$Instance\",serviceEndpoint=~\".*$AwsRegion.*\",error=\"true\"}[$__interval])) by (serviceEndpoint, statusCode), \"region\", \"$1\", \"serviceEndpoint\", \"[^\\\\.]+\\\\.([^\\\\.]+).*\")",
     "legendFormat": "{{region}} / {{statusCode}}"
    }
   ]
  },
  {
   "title": "AWS Errors in $AwsRegion (clouddriver, $Instance)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(label_replace(sum(rate(aws_request_httpRequestTime_seconds_count{instance=~\"$Instance\",serviceEndpoint=~\".*$AwsRegion.*\",error=\"true\"}[$__interval])) by (requestType, serviceName, statusCode, AWSErrorCode), \"requestType\", \"$1\", \"requestType\", \"(.*)Request(.*)\"), \"serviceName\",  \"$1\", \"serviceName\", \"Amazon(.+)\")",
     "legendFormat": "{{statusCode}}/{{serviceName}}.{{requestType}}->{{AWSErrorCode}}"
    }
   ]
  },
  {
   "title": "AWS EC2 Requests  by Region (clouddriver, $Instance)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(rate(aws_request_httpRequestTime_seconds_count{instance=~\"$Instance\",serviceName=\"AmazonEC2\", error=\"false\"}[$__interval])) by (serviceEndpoint), \"region\", \"$1\", \"serviceEndpoint\", \"[^\\\\.]+\\\\.([^\\\\.]+).*\")",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "AWS EC2 Requests in $AwsRegion (clouddriver, $Instance)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(rate(aws_request_httpRequestTime_seconds_count{instance=~\"$Instance\",serviceEndpoint=~\".*$AwsRegion.*\",serviceName=\"AmazonEC2\", error=\"false\"}[$__interval])) by (requestType, serviceName), \"requestType\", \"$1\", \"requestType\", \"(.*)Request\")",
     "legendFormat": "{{requestType}}"
    }
   ]
  },
  {
   "title": "AWS EC2 Request Latency by Region  (clouddriver, $Instance)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(rate(aws_request_httpRequestTime_seconds_sum{instance=~\"$Instance\",serviceEndpoint=~\".*$AwsRegion.*\",serviceName=\"AmazonEC2\"}[$__interval])) by (serviceEndpoint, serviceName)\n/ sum(rate(aws_request_httpRequestTime_seconds_count{instance=~\"$Instance\",serviceName=\"AmazonEC2\", error=\"false\"}[$__interval])) by (serviceEndpoint, serviceName), \"region\", \"$1\", \"serviceEndpoint\", \"[^\\\\.]+\\\\.([^\\\\.]+).*\")",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "AWS EC2 Request Latency in $AwsRegion  (clouddriver, $Instance)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(aws_request_httpRequestTime_seconds_sum{instance=~\"$Instance\",serviceEndpoint=~\".*$AwsRegion.*\",serviceName=\"AmazonEC2\"}[$__interval])) by (requestType, serviceName)\n/ sum(rate(aws_request_httpRequestTime_seconds_count{instance=~\"$Instance\",serviceName=\"AmazonEC2\", error=\"false\"}[$__interval])) by (requestType, serviceName)",
     "legendFormat": "{{requestType}}"
    }
   ]
  },
  {
   "title": "AWS Requests (non EC2) by Region (clouddriver, $Instance)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(rate(aws_request_httpRequestTime_seconds_count{instance=~\"$Instance\",serviceEndpoint=~\".*$AwsRegion.*\",serviceName!=\"AmazonEC2\", error=\"false\"}[$__interval])) by (serviceName, serviceEndpoint), \"region\", \"$1\", \"serviceEndpoint\", \"[^\\\\.]+\\\\.([^\\\\.]+).*\")",
     "legendFormat": "{{serviceName}} / {{region}}"
    }
   ]
  },
  {
   "title": "AWS Requests (non EC2) in $AwsRegion (clouddriver, $Instance)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(rate(aws_request_httpRequestTime_seconds_count{instance=~\"$Instance\",serviceEndpoint=~\".*$AwsRegion.*\",serviceName!=\"AmazonEC2\", error=\"false\"}[$__interval])) by (requestType, serviceName), \"serviceName\", \"$1\", \"serviceName\", \"Amazon(.+)\")",
     "legendFormat": "{{serviceName}}.{{requestType}}"
    }
   ]
  },
  {
   "title": "AWS Non-EC2 Request Latency by Region  (clouddriver, $Instance)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "label_replace(label_replace(sum(rate(aws_request_httpRequestTime_seconds_sum{instance=~\"$Instance\",serviceEndpoint=~\".*$AwsRegion.*\",serviceName!=\"AmazonEC2\"}[$__interval])) by (serviceEndpoint, serviceName)\n/ sum(rate(aws_request_httpRequestTime_seconds_count{serviceName!=\"AmazonEC2\", error=\"false\"}[$__interval])) by (serviceEndpoint, serviceName), \"serviceName\", \"$1\", \"serviceName\", \"Amazon(.+)\"), \"region\", \"$1\", \"serviceEndpoint\", \"[^\\\\.]+\\\\.([^\\\\.]+).*\")",
     "legendFormat": "{{serviceName}} / {{region}}"
    }
   ]
  },
  {
   "title": "AWS Non-EC2 Request Latency in $AwsRegion  (clouddriver, $Instance)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "label_replace(label_replace(sum(rate(aws_request_httpRequestTime_seconds_sum{instance=~\"$Instance\",serviceEndpoint=~\".*$AwsRegion.*\",serviceName!=\"AmazonEC2\"}[$__interval])) by (requestType, serviceName)\n/\nsum(rate(aws_request_httpRequestTime_seconds_count{serviceName!=\"AmazonEC2\", error=\"false\"}[$__interval])) by (requestType, serviceName), \"serviceName\", \"$1\", \"serviceName\", \"Amazon(.+)\"), \"requestType\", \"$1\", \"requestType\", \"(.*)Request\")",
     "legendFormat": "{{serviceName}}.{{requestType}}"
    }
   ]
  }
 ]
}