{
 "title": "Spinnaker Kubernetes Details",
 "tags": [
  "spinnaker",
  "kubernetes"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "spinSvc", "query": "clouddriver" },
   {
    "name": "Instance",
    "query": "label_values(up{job=~\".*$spinSvc*.\"}, instance)"
   },
   {
    "name": "KubernetesAccount",
    "query": "label_values(kubernetes_api_seconds_count, account)"
   },
   {
    "name": "KubernetesNamespace",
    "query": "label_values(kubernetes_api_seconds_count, exported_namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Kubernetes Success for \"$KubernetesAccount\" in \"$KubernetesNamespace\" (clouddriver)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kubernetes_api_seconds_count{instance=~\"$Instance\",exported_namespace=~\"$KubernetesNamespace\",account=~\"$KubernetesAccount\",success=\"true\"}[$__interval])) by (action)",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Kubernetes Latency for \"$KubernetesAccount\" in \"$KubernetesNamespace\" (clouddriver)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kubernetes_api_seconds_sum{instance=~\"$Instance\",exported_namespace=~\"$KubernetesNamespace\",success=\"true\",account=~\"$KubernetesAccount\"}[$__interval])) by (action)\n/\nsum(rate(kubernetes_api_seconds_count{instance=~\"$Instance\",exported_namespace=~\"$KubernetesNamespace\",account=~\"$KubernetesAccount\",success=\"true\"}[$__interval])) by (action)",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Kubernetes Failure for \"$KubernetesAccount\" in \"$KubernetesNamespace\" (clouddriver)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kubernetes_api_seconds_count{instance=~\"$Instance\",exported_namespace=~\"$KubernetesNamespace\",account=~\"$KubernetesAccount\",success!=\"true\"}[$__interval])) by (action, reason)",
     "legendFormat": "{{action}}/{{reason}}"
    }
   ]
  },
  {
   "title": "Kubernetes Failure Latency for \"$KubernetesAccount\" in \"$KubernetesNamespace\" (clouddriver)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kubernetes_api_seconds_sum{instance=~\"$Instance\",exported_namespace=~\"$KubernetesNamespace\",success!=\"true\",account=~\"$KubernetesAccount\"}[$__interval])) by (action, reason)\n/\nsum(rate(kubernetes_api_seconds_count{instance=~\"$Instance\",exported_namespace=~\"$KubernetesNamespace\",account=~\"$KubernetesAccount\",success!=\"true\"}[$__interval])) by (action)",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Kubernetes Success by Kind (clouddriver, $Instance)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kubernetes_api_seconds_count{instance=~\"$Instance\",success=\"true\"}[$__interval])) by (kinds)",
     "legendFormat": "{{kinds}}"
    }
   ]
  },
  {
   "title": "Kubernetes Success by Account (clouddriver, $Instance)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 10, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kubernetes_api_seconds_count{instance=~\"$Instance\",success=\"true\"}[$__interval])) by (account)",
     "legendFormat": "{{account}} "
    }
   ]
  },
  {
   "title": "Kubernetes Success by Namespace (clouddriver, $Instance)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kubernetes_api_seconds_count{instance=~\"$Instance\",success=\"true\"}[$__interval])) by (exported_namespace)",
     "legendFormat": "{{exported_namespace}} "
    }
   ]
  },
  {
   "title": "Kubernetes Latency by Kind (clouddriver)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kubernetes_api_seconds_sum{instance=~\"$Instance\",success=\"true\"}[$__interval])) by (kinds)\n/\nsum(rate(kubernetes_api_seconds_count{instance=~\"$Instance\",success=\"true\"}[$__interval])) by (kinds)",
     "legendFormat": "{{kinds}}"
    }
   ]
  },
  {
   "title": "Kubernetes Latency by Account (clouddriver)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 10, "y": 22 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kubernetes_api_seconds_sum{instance=~\"$Instance\",success=\"true\"}[$__interval])) by (account)\n/\nsum(rate(kubernetes_api_seconds_count{instance=~\"$Instance\",success=\"true\"}[$__interval])) by (account)",
     "legendFormat": "{{account}}"
    }
   ]
  },
  {
   "title": "Kubernetes Latency by Namespace (clouddriver)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 22 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kubernetes_api_seconds_sum{instance=~\"$Instance\",success=\"true\"}[$__interval])) by (exported_namespace) / sum(rate(kubernetes_api_seconds_count{instance=~\"$Instance\",success=\"true\"}[$__interval])) by (exported_namespace)",
     "legendFormat": "{{exported_namespace}}"
    }
   ]
  },
  {
   "title": "Kubernetes Failure by Kind (clouddriver, $Instance)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kubernetes_api_seconds_count{instance=~\"$Instance\",success!=\"true\"}[$__interval])) by (kinds)",
     "legendFormat": "{{kinds}} "
    }
   ]
  },
  {
   "title": "Kubernetes Failure by Account (clouddriver, $Instance)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 10, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kubernetes_api_seconds_count{instance=~\"$Instance\",success!=\"true\"}[$__interval])) by (account)",
     "legendFormat": "{{account}} "
    }
   ]
  },
  {
   "title": "Kubernetes Failure by Namespace (clouddriver, $Instance)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kubernetes_api_seconds_count{instance=~\"$Instance\",success!=\"true\"}[$__interval])) by (exported_namespace)",
     "legendFormat": "{{exported_namespace}} "
    }
   ]
  }
 ]
}