{
 "title": "Ceph NVMe-oF Gateways - Overview",
 "description": "Ceph NVMe-oF gateways overview",
 "tags": [ "ceph-mixin" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(ceph_health_status, cluster)"
   },
   {
    "name": "group",
    "label": "Gateway Group",
    "query": "label_values(ceph_nvmeof_gateway_info,group)"
   },
   {
    "name": "gateway",
    "label": "Gateway Hostname",
    "query": "label_values(ceph_nvmeof_gateway_info{group=~'$group'},hostname)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Gateway Groups",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count  by (group) (ceph_nvmeof_gateway_info))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Gateways",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ceph_nvmeof_gateway_info) + sum(ceph_health_detail{name='NVMEOF_GATEWAY_DOWN'})",
     "legendFormat": "Total"
    },
    {
     "expr": "count(ceph_nvmeof_gateway_info)",
     "legendFormat": "Available"
    },
    {
     "expr": "(ceph_health_detail{name='NVMEOF_GATEWAY_DOWN'})",
     "legendFormat": "Down"
    }
   ]
  },
  {
   "title": "Ceph Health NVMeoF WARNING",
   "type": "timeseries",
   "description": "Ceph healthchecks NVMeoF WARNINGs",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(ceph_health_detail{name='NVMEOF_GATEWAY_DOWN'})",
     "legendFormat": "NVMEOF_GATEWAY_DOWN"
    },
    {
     "expr": "sum(ceph_health_detail{name='NVMEOF_GATEWAY_DELETING'})",
     "legendFormat": "NVMEOF_GATEWAY_DELETING"
    },
    {
     "expr": "sum(ceph_health_detail{name='NVMEOF_SINGLE_GATEWAY'})",
     "legendFormat": "NVMEOF_SINGLE_GATEWAY"
    }
   ]
  },
  { "title": "Active Alerts", "type": "alertlist", "gridPos": { "h": 8, "w": 9, "x": 15, "y": 1 } },
  {
   "title": "Gateways per group",
   "type": "piechart",
   "description": "Gateways in each group",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count  by (group) (ceph_nvmeof_gateway_info)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NVMeoF Group Overview -  $group",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }
  },
  {
   "title": "Gateways",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ceph_nvmeof_gateway_info{group=~'$group'})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Subsystems",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by(nqn) (ceph_nvmeof_subsystem_metadata{group=~'$group',instance=~'$gateway'}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Namespaces",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (bdev_name) (\n  ceph_nvmeof_bdev_metadata{instance=~'$gateway'} * on (instance) group_left(group) ceph_nvmeof_gateway_info{group=~'$group'}\n))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connected Clients",
   "type": "stat",
   "description": "Average connected clients",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (nqn) (sum by(gw_name, nqn) (ceph_nvmeof_host_connection_state{instance=~'$gateway'} * on (instance) group_left(group) ceph_nvmeof_gateway_info{group=~'$group'}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Capacity Exported",
   "type": "stat",
   "description": "The sum of capacity from all namespaces defined to subsystems",
   "gridPos": { "h": 3, "w": 5, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg by (group) (sum by(group, instance) (ceph_nvmeof_bdev_capacity_bytes{instance=~'$gateway'} * on (instance) group_left(group) ceph_nvmeof_gateway_info{group=~'$group'})))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Subsystem Security",
   "type": "stat",
   "description": "WARNING if any subsystem is defined with open/no security",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ceph_nvmeof_subsystem_metadata{allow_any_host='yes',group=~'$group', instance=~'$gateway'}) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active gateways count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count by (group) (ceph_nvmeof_gateway_info{group=~'$group',instance=~'$gateway'})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 5 Busiest Gateway CPU",
   "type": "bargauge",
   "description": "Shows the highest average CPU on a gateway within the gateway group",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, avg by(instance) (rate(ceph_nvmeof_reactor_seconds_total{mode='busy',instance=~'$gateway'}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IOPS - $gateway",
   "type": "stat",
   "description": "All gateways",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(ceph_nvmeof_bdev_reads_completed_total{instance=~'$gateway'}[$__rate_interval]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(irate(ceph_nvmeof_bdev_writes_completed_total{instance=~'$gateway'}[$__rate_interval]))",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Throughput - $gateway",
   "type": "stat",
   "description": "All gateways",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (irate(ceph_nvmeof_bdev_read_bytes_total{instance=~'$gateway'}[$__rate_interval]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum (irate(ceph_nvmeof_bdev_written_bytes_total{instance=~'$gateway'}[$__rate_interval]))",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Gateway Information",
   "type": "table",
   "gridPos": { "h": 12, "w": 17, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "(count by(instance) (ceph_nvmeof_reactor_seconds_total{mode='busy'})) * on (instance) group_left(group,hostname,version,addr) ceph_nvmeof_gateway_info{group=~'$group'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 5 Subsystems by Namespace",
   "type": "bargauge",
   "description": "Show the subsystems by the count of namespaces they present to the client",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, avg by (nqn) (ceph_nvmeof_subsystem_namespace_count{instance=~'$gateway'} * on (instance) group_left(group) ceph_nvmeof_gateway_info{group=~'$group'}))",
     "legendFormat": "{{nqn}}"
    }
   ]
  },
  {
   "title": "Top 5 Subsystems with Most Connected Clients",
   "type": "bargauge",
   "description": "Show the subsystems by the count of namespaces they present to the client",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, avg by (nqn) (sum by(gw_name, nqn) (ceph_nvmeof_host_connection_state{instance=~'$gateway'} * on (instance) group_left(group) ceph_nvmeof_gateway_info{group=~'$group'}))) ",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}