{
 "title": "SMB Overview",
 "description": "SMB Overview dashboard shows data across all clusters and hosts associated with the SMB service.",
 "tags": [ "ceph-mixin" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "query": "label_values(ceph_health_status, cluster)"
   },
   {
    "name": "SMBcluster",
    "label": "SMB Cluster",
    "query": "label_values(smb_metrics_status,netbiosname)"
   },
   {
    "name": "hostname",
    "label": "Hostname",
    "query": "label_values(smb_metrics_status{netbiosname=~\"$SMBcluster\"},instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Prometheus SMB metrics status",
   "type": "stat",
   "description": "SMB metrics daemon health.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(smb_metrics_status{instance=~\"$hostname\"})  by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nodes per Cluster",
   "type": "stat",
   "description": "Number of nodes per cluster",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (netbiosname) (smb_sessions_total * on (instance) group_left (netbiosname) smb_metrics_status{netbiosname=~\"$SMBcluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active sessions per Cluster",
   "type": "stat",
   "description": "Number of users currently logged in Cluster",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(netbiosname)(smb_sessions_total * on (instance) group_left (netbiosname) smb_metrics_status{netbiosname=~\"$SMBcluster\"}) / (count by ( netbiosname)(smb_sessions_total * on (instance) group_left (netbiosname) smb_metrics_status{netbiosname=~\"$SMBcluster\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Shares activity per Cluster",
   "type": "stat",
   "description": "Number of remote machines using a share in cluster",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(netbiosname)(smb_share_activity * on (instance) group_left (netbiosname) smb_metrics_status{netbiosname=~\"$SMBcluster\"}) / (count by ( netbiosname)(smb_share_activity * on (instance) group_left (netbiosname) smb_metrics_status{netbiosname=~\"$SMBcluster\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active users per Cluster",
   "type": "stat",
   "description": "Number of currently active SMB user per cluster",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(netbiosname)(smb_users_total * on (instance) group_left (netbiosname) smb_metrics_status{netbiosname=~\"$SMBcluster\"}) / (count by ( netbiosname)(smb_users_total * on (instance) group_left (netbiosname) smb_metrics_status{netbiosname=~\"$SMBcluster\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ingress throughtput",
   "type": "stat",
   "description": "Current total ingress throughput, bytes going in per second",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(smb_smb2_request_inbytes{instance=~\"$hostname\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "stat",
   "description": "Current total request time for the sum of all runing operations",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(smb_smb2_request_duration_microseconds_sum{instance=~\"$hostname\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Egress throughtput",
   "type": "stat",
   "description": "Current total egress throughput, bytes going out per second",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(smb_smb2_request_outbytes{instance=~\"$hostname\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "I/O",
   "type": "stat",
   "description": "Current total number of operations per second",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(smb_smb2_request_outbytes{instance=~\"$hostname\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(smb_smb2_request_inbytes{instance=~\"$hostname\"}[$__rate_interval])",
     "legendFormat": "Inbytes.{{instance}}.{{operation}}"
    },
    {
     "expr": "rate(smb_smb2_request_outbytes{instance=~\"$hostname\"}[$__rate_interval])",
     "legendFormat": "Outbytes.{{instance}}.{{operation}}"
    }
   ]
  },
  {
   "title": "I/O",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(smb_smb2_request_total{instance=~\"$hostname\"}[$__rate_interval])",
     "legendFormat": "{{instance}}.{{operation}}"
    }
   ]
  },
  {
   "title": "Latencies",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(smb_smb2_request_duration_microseconds_sum{instance=~\"$hostname\"}[$__rate_interval])",
     "legendFormat": "{{instance}}.{{operation}}"
    }
   ]
  }
 ]
}