{
 "title": "Cilium / Components / Agent",
 "description": "Dashboard for Cilium v1.12 (https://cilium.io/) Agent metrics",
 "tags": [ "cilium-agent" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(cilium_version, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(cilium_version{cluster=~\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(cilium_version{cluster=~\"$cluster\", namespace=~\"$namespace\"}, pod)"
    }
   },
   { "name": "k", "label": "top k", "query": "10" }
  ]
 },
 "panels": [
  {
   "title": "Top Agent Error Rates",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk($k, sum(rate(cilium_errors_warnings_total{k8s_app=\"cilium\", level=\"error\", pod=~\"$pod\"}[$__rate_interval])) by (pod))",
     "legendFormat": "{{ pod }} "
    }
   ]
  },
  {
   "title": "Top-10 Agent Warnings Rates",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "topk($k, sum(rate(cilium_errors_warnings_total{k8s_app=\"cilium\", level=\"warning\", pod=~\"$pod\"}[$__rate_interval])) by (pod))",
     "legendFormat": "{{ pod }} "
    }
   ]
  },
  {
   "title": "Agent Controller Runs",
   "type": "timeseries",
   "description": "This tracks internal controller runs within Cilium. Controllers are asynchronous controllers that attempt to reconcile Cilium state. Failing runs could indicate a problem with the agent.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "sum(rate(cilium_controllers_runs_total{k8s_app=\"cilium\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Top Agent Controller Failures by Pod",
   "type": "timeseries",
   "description": "This tracks internal controller runs within Cilium. Controllers are asynchronous controllers that attempt to reconcile Cilium state. Failing runs could indicate a problem with the agent.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "topk($k, sum(rate(cilium_controllers_runs_total{k8s_app=\"cilium\", pod=~\"$pod\", status=\"failure\"}[$__rate_interval])) by (pod))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "P95 Agent Controller Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile(0.95, rate(cilium_controllers_runs_duration_seconds_sum{pod=~\"$pod\"}[$__rate_interval]) / rate(cilium_controllers_runs_duration_seconds_count{pod=~\"$pod\"}[$__rate_interval])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Agent API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Top API Call Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk($k, sum(rate(cilium_agent_api_process_time_seconds_sum{k8s_app=\"cilium\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])/rate(cilium_agent_api_process_time_seconds_count{k8s_app=\"cilium\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) by (pod, method, path))",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Top API Call Rates",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk($k, rate(cilium_agent_api_process_time_seconds_count{k8s_app=\"cilium\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) by (pod, method, path)",
     "legendFormat": "{{pod}} {{method}} {{path}} "
    }
   ]
  },
  {
   "title": "P95 API Call Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile(.95, rate(cilium_agent_api_process_time_seconds_sum[$__rate_interval]) / rate(cilium_agent_api_process_time_seconds_count[$__rate_interval])) by (method, endpoint)",
     "legendFormat": "{{method}} {{endpoint}}"
    }
   ]
  },
  {
   "title": "Avg Agent API Call Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile(.5, rate(cilium_agent_api_process_time_seconds_sum[$__rate_interval]) / rate(cilium_agent_api_process_time_seconds_count[$__rate_interval])) by (method, endpoint)",
     "legendFormat": "{{method}} {{endpoint}}"
    }
   ]
  },
  {
   "title": "Avg API Calls",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(cilium_agent_api_process_time_seconds_count{k8s_app=\"cilium\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) by (method, path) > 0",
     "legendFormat": "{{method}} {{path}} "
    }
   ]
  },
  {
   "title": "Top API Return Codes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk($k, (sum(rate(cilium_agent_api_process_time_seconds_count{k8s_app=\"cilium\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) by (method, path, return_code)) > 0)",
     "legendFormat": "{{return_code}} {{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Top Non-2XX API Return Codes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk($k, sum(rate(cilium_agent_api_process_time_seconds_count{k8s_app=\"cilium\", pod=~\"$pod\", return_code!~\"2[0-9][0-9]\"}[$__rate_interval])) by (method, path, return_code) > 0)",
     "legendFormat": "{{return_code}} {{method}} {{path}}"
    }
   ]
  }
 ]
}