{
 "title": "Cilium / Components / L7 Proxy",
 "description": "Dashboard for Cilium v1.12 (https://cilium.io/) Agent metrics",
 "tags": [ "cilium-agent" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(cilium_version, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(cilium_version{cluster=~\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(cilium_version{cluster=~\"$cluster\", namespace=~\"$namespace\"}, pod)"
    }
   },
   { "name": "k", "label": "top k", "query": "10" }
  ]
 },
 "panels": [
  {
   "title": "L7 Total Proxy Redirects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(cilium_proxy_redirects{k8s_app=\"cilium\", pod=~\"$pod\", protocol_l7!=\"\"}) by (protocol_l7)",
     "legendFormat": "{{protocol_l7}}"
    },
    {
     "expr": "sum(cilium_proxy_redirects{k8s_app=\"cilium\", pod=~\"$pod\", protocol_l7!=\"\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "L7 Parse Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk($k, sum(rate(cilium_policy_l7_parse_errors_total{k8s_app=\"cilium\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) by (pod))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Policy Trigger Duration Quantiles (95, 50, 25)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile(0.95, rate(cilium_triggers_policy_update_call_duration_seconds_sum{k8s_app=\"cilium\", pod=~\"$pod\", type=\"duration\"}[$__rate_interval]) / rate(cilium_triggers_policy_update_call_duration_seconds_count{k8s_app=\"cilium\", pod=~\"$pod\", type=\"duration\"}[$__rate_interval]))",
     "legendFormat": "p95"
    },
    {
     "expr": "quantile(0.5, rate(cilium_triggers_policy_update_call_duration_seconds_sum{k8s_app=\"cilium\", pod=~\"$pod\", type=\"duration\"}[$__rate_interval]) / rate(cilium_triggers_policy_update_call_duration_seconds_count{k8s_app=\"cilium\", pod=~\"$pod\", type=\"duration\"}[$__rate_interval]))",
     "legendFormat": "p50"
    },
    {
     "expr": "quantile(0.25, rate(cilium_triggers_policy_update_call_duration_seconds_sum{k8s_app=\"cilium\", pod=~\"$pod\", type=\"duration\"}[$__rate_interval]) / rate(cilium_triggers_policy_update_call_duration_seconds_count{k8s_app=\"cilium\", pod=~\"$pod\", type=\"duration\"}[$__rate_interval]))",
     "legendFormat": "p25"
    }
   ]
  },
  {
   "title": "Policy Trigger Latency Quantiles (95, 50, 25)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile(0.95, rate(cilium_triggers_policy_update_call_duration_seconds_sum{k8s_app=\"cilium\", pod=~\"$pod\", type=\"latency\"}[$__rate_interval]) / rate(cilium_triggers_policy_update_call_duration_seconds_count{k8s_app=\"cilium\", pod=~\"$pod\", type=\"latency\"}[$__rate_interval]))",
     "legendFormat": "p95"
    },
    {
     "expr": "quantile(0.5, rate(cilium_triggers_policy_update_call_duration_seconds_sum{k8s_app=\"cilium\", pod=~\"$pod\", type=\"latency\"}[$__rate_interval]) / rate(cilium_triggers_policy_update_call_duration_seconds_count{k8s_app=\"cilium\", pod=~\"$pod\", type=\"duration\"}[$__rate_interval]))",
     "legendFormat": "p50"
    },
    {
     "expr": "quantile(0.25, rate(cilium_triggers_policy_update_call_duration_seconds_sum{k8s_app=\"cilium\", pod=~\"$pod\", type=\"latency\"}[$__rate_interval]) / rate(cilium_triggers_policy_update_call_duration_seconds_count{k8s_app=\"cilium\", pod=~\"$pod\", type=\"duration\"}[$__rate_interval]))",
     "legendFormat": "p25"
    }
   ]
  }
 ]
}