{
 "title": "Apache Airflow overview",
 "description": "Dashboard providing an overview of Apache Airflow DAGs, tasks, and scheduler performance.",
 "tags": [ "apache-airflow-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(airflow_dagbag_size{}, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(airflow_dagbag_size{job=~\"$job\"}, instance)"
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" },
   {
    "name": "dag_id",
    "label": "DAG",
    "query": "label_values(airflow_dagrun_duration_success_sum{job=~\"$job\", instance=~\"$instance\"}, dag_id)"
   },
   {
    "name": "task_id",
    "label": "Task",
    "query": "label_values(airflow_task_finish_total{job=~\"$job\", instance=~\"$instance\"}, task_id)"
   },
   {
    "name": "state",
    "label": "State",
    "query": "label_values(airflow_task_finish_total{job=~\"$job\", instance=~\"$instance\"}, state)"
   },
   {
    "name": "pool_name",
    "label": "Pool name",
    "query": "label_values(airflow_pool_running_slots{job=~\"$job\", instance=~\"$instance\"}, pool_name)"
   }
  ]
 },
 "panels": [
  { "title": "Apache Airflow overview", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "DAG file parsing errors",
   "type": "timeseries",
   "description": "The number of errors from trying to parse DAG files in an Apache Airflow system.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "airflow_dag_processing_import_errors{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "SLA misses",
   "type": "timeseries",
   "description": "The number of Service Level Agreement misses for any DAG runs in the Apache Airflow system.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(airflow_sla_missed{job=~\"$job\",instance=~\"$instance\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Task failures",
   "type": "timeseries",
   "description": "The overall task instances failures for an Apache Airflow system.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(airflow_ti_failures{job=~\"$job\",instance=~\"$instance\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "DAG success duration",
   "type": "timeseries",
   "description": "The average time taken for recent successful DAG runs by DAG ID in the Apache Airflow system.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(airflow_dagrun_duration_success_sum{job=~\"$job\",instance=~\"$instance\", dag_id=~\"$dag_id\"}[$__interval:] offset -$__interval)/clamp_min(increase(airflow_dagrun_duration_success_count{job=~\"$job\",instance=~\"$instance\", dag_id=~\"$dag_id\"}[$__interval:] offset -$__interval),1)",
     "legendFormat": "{{dag_id}}"
    }
   ]
  },
  {
   "title": "DAG failed duration",
   "type": "timeseries",
   "description": "The average time taken for recent failed DAG runs by DAG ID in the Apache Airflow system.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(airflow_dagrun_duration_failed_sum{job=~\"$job\",instance=~\"$instance\", dag_id=~\"$dag_id\"}[$__interval:] offset -$__interval)/clamp_min(increase(airflow_dagrun_duration_failed_count{job=~\"$job\",instance=~\"$instance\", dag_id=~\"$dag_id\"}[$__interval:] offset -$__interval),1)",
     "legendFormat": "{{dag_id}}"
    }
   ]
  },
  {
   "title": "Task duration",
   "type": "bargauge",
   "description": "The average time taken for recent task runs by Task ID in the Apache Airflow system.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(airflow_dag_task_duration_sum{job=~\"$job\",instance=~\"$instance\", dag_id=~\"$dag_id\", task_id=~\"$task_id\"}[$__interval:] offset -$__interval)/clamp_min(increase(airflow_dag_task_duration_count{job=~\"$job\",instance=~\"$instance\", dag_id=~\"$dag_id\", task_id=~\"$task_id\"}[$__interval:] offset -$__interval),1) != 0",
     "legendFormat": "{{dag_id}} - {{task_id}}"
    }
   ]
  },
  {
   "title": "Task count summary",
   "type": "piechart",
   "description": "The number of task counts by DAG ID in the Apache Airflow system.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(job, instance, dag_id, state) (increase(airflow_task_finish_total{job=~\"$job\",instance=~\"$instance\", dag_id=~\"$dag_id\", task_id=~\"$task_id\", state=~\"$state\"}[$__interval:] offset -$__interval) > 0)",
     "legendFormat": "{{dag_id}} - {{state}}"
    }
   ]
  },
  {
   "title": "Task counts",
   "type": "timeseries",
   "description": "The number of task counts by Task ID in the Apache Airflow system.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(airflow_task_finish_total{job=~\"$job\",instance=~\"$instance\", dag_id=~\"$dag_id\", task_id=~\"$task_id\", state=~\"$state\"}[$__interval:] offset -$__interval) > 0",
     "legendFormat": "{{dag_id}} - {{task_id}} - {{state}}"
    }
   ]
  },
  { "title": "Scheduler details", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 25 } },
  {
   "title": "DAG schedule delay",
   "type": "timeseries",
   "description": "The amount of average delay between recent scheduled DAG runtime and the actual DAG runtime by DAG ID in the Apache Airflow system.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(airflow_dagrun_schedule_delay_sum{job=~\"$job\",instance=~\"$instance\", dag_id=~\"$dag_id\"}[$__interval:] offset -$__interval)/clamp_min(increase(airflow_dagrun_schedule_delay_count{job=~\"$job\",instance=~\"$instance\", dag_id=~\"$dag_id\"}[$__interval:] offset -$__interval),1)",
     "legendFormat": "{{dag_id}}"
    }
   ]
  },
  {
   "title": "Scheduler tasks",
   "type": "timeseries",
   "description": "The number of current tasks that the scheduler is handling in the Apache Airflow system.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "airflow_scheduler_tasks_executable{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - executable"
    },
    {
     "expr": "airflow_scheduler_tasks_starving{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - starving"
    }
   ]
  },
  {
   "title": "Executor tasks",
   "type": "timeseries",
   "description": "The number of current tasks that the executors are handling in the Apache Airflow system.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "airflow_executor_running_tasks{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - running"
    },
    {
     "expr": "airflow_executor_queued_tasks{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - queued"
    },
    {
     "expr": "airflow_executor_open_slots{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - open"
    }
   ]
  },
  {
   "title": "Pool task slots",
   "type": "timeseries",
   "description": "The number of current task slots that the pools are handling in the Apache Airflow system.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "airflow_pool_running_slots{job=~\"$job\",instance=~\"$instance\", pool_name=~\"$pool_name\"}",
     "legendFormat": "{{instance}} - {{pool_name}} - running"
    },
    {
     "expr": "airflow_pool_queued_slots{job=~\"$job\",instance=~\"$instance\", pool_name=~\"$pool_name\"}",
     "legendFormat": "{{instance}} - {{pool_name}} - queued"
    },
    {
     "expr": "airflow_pool_starving_tasks{job=~\"$job\",instance=~\"$instance\", pool_name=~\"$pool_name\"}",
     "legendFormat": "{{instance}} - {{pool_name}} - starving"
    },
    {
     "expr": "airflow_pool_open_slots{job=~\"$job\",instance=~\"$instance\", pool_name=~\"$pool_name\"}",
     "legendFormat": "{{instance}} - {{pool_name}} - open"
    }
   ]
  }
 ]
}