{
 "title": "Apache Cassandra keyspaces",
 "tags": [ "cassandra-mixin" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(cassandra_cache_hitrate{}, job)"
   },
   {
    "name": "cassandra_cluster",
    "label": "Cassandra cluster",
    "query": "label_values(cassandra_cache_hitrate{job=~\"$job\"}, cassandra_cluster)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(cassandra_cache_hitrate{job=~\"$job\",cassandra_cluster=~\"$cassandra_cluster\"}, instance)"
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" }
  ]
 },
 "panels": [
  { "title": "Keyspaces", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Keyspaces count",
   "type": "stat",
   "description": "The total count of the amount of keyspaces being reported.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(count by (keyspace) (cassandra_keyspace_writelatency_seconds{job=~\"$job\",cassandra_cluster=~\"$cassandra_cluster\",instance=~\"$instance\"}))",
     "legendFormat": "{{ keyspace}}"
    }
   ]
  },
  {
   "title": "Writes",
   "type": "timeseries",
   "description": "The number of writes performed on the keyspace.",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(sum(cassandra_keyspace_writelatency_seconds_count{job=~\"$job\",cassandra_cluster=~\"$cassandra_cluster\",instance=~\"$instance\"}) by (keyspace)[$__interval:] offset -$__interval)",
     "legendFormat": "{{ keyspace}}"
    }
   ]
  },
  {
   "title": "Reads",
   "type": "timeseries",
   "description": "The number of reads performed on the keyspace.",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(sum(cassandra_keyspace_readlatency_seconds_count{job=~\"$job\",cassandra_cluster=~\"$cassandra_cluster\",instance=~\"$instance\"}) by (keyspace)[$__interval:] offset -$__interval)",
     "legendFormat": "{{ keyspace}}"
    }
   ]
  },
  {
   "title": "Keyspace write latency",
   "type": "timeseries",
   "description": "The 95th and 99th percentils of local write latency for keyspaces.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(cassandra_keyspace_writelatency_seconds{job=~\"$job\",cassandra_cluster=~\"$cassandra_cluster\",instance=~\"$instance\", quantile=\"0.95\"} >= 0) by (keyspace)",
     "legendFormat": "{{ keyspace }} - p95"
    },
    {
     "expr": "sum(cassandra_keyspace_writelatency_seconds{job=~\"$job\",cassandra_cluster=~\"$cassandra_cluster\",instance=~\"$instance\", quantile=\"0.99\"} >= 0) by (keyspace)",
     "legendFormat": "{{ keyspace }} - p99"
    }
   ]
  },
  {
   "title": "Keyspace read latency",
   "type": "timeseries",
   "description": "Average local read latency for keyspaces.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(cassandra_keyspace_readlatency_seconds{job=~\"$job\",cassandra_cluster=~\"$cassandra_cluster\",instance=~\"$instance\", quantile=\"0.95\"} >= 0) by (keyspace)",
     "legendFormat": "{{ keyspace }} - p95"
    },
    {
     "expr": "sum(cassandra_keyspace_readlatency_seconds{job=~\"$job\",cassandra_cluster=~\"$cassandra_cluster\",instance=~\"$instance\", quantile=\"0.99\"} >= 0) by (keyspace)",
     "legendFormat": "{{ keyspace }} - p99"
    }
   ]
  },
  {
   "title": "Keyspace total disk space used",
   "type": "timeseries",
   "description": "Total amount of disk space used by keyspaces.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(cassandra_keyspace_totaldiskspaceused{job=~\"$job\",cassandra_cluster=~\"$cassandra_cluster\",instance=~\"$instance\"}) by (keyspace)",
     "legendFormat": "{{ keyspace}}"
    }
   ]
  },
  {
   "title": "Keyspace pending compactions",
   "type": "timeseries",
   "description": "The number of compaction operations a keyspace is pending to perform.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(cassandra_keyspace_pendingcompactions{job=~\"$job\",cassandra_cluster=~\"$cassandra_cluster\",instance=~\"$instance\"}) by (keyspace)",
     "legendFormat": "{{ keyspace}}"
    }
   ]
  },
  {
   "title": "Keyspace max partition size",
   "type": "timeseries",
   "description": "Max partition size for keyspaces.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max(cassandra_table_maxpartitionsize{job=~\"$job\",cassandra_cluster=~\"$cassandra_cluster\",instance=~\"$instance\"}) by (keyspace)",
     "legendFormat": "{{ keyspace}}"
    }
   ]
  },
  {
   "title": "Repair jobs started",
   "type": "timeseries",
   "description": "The number of repair jobs started per keyspace.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(sum(cassandra_keyspace_repairjobsstarted_count{job=~\"$job\",cassandra_cluster=~\"$cassandra_cluster\",instance=~\"$instance\"}) by (keyspace)[$__interval:] offset -$__interval)",
     "legendFormat": "{{ keyspace}}"
    }
   ]
  },
  {
   "title": "Repair jobs completed",
   "type": "timeseries",
   "description": "The number of repair jobs that were completed.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(sum(cassandra_keyspace_repairjobscompleted_count{job=~\"$job\",cassandra_cluster=~\"$cassandra_cluster\",instance=~\"$instance\"}) by (keyspace)[$__interval:] offset -$__interval)",
     "legendFormat": "{{ keyspace}}"
    }
   ]
  }
 ]
}