{
 "title": "Apache Cassandra nodes",
 "tags": [ "cassandra-mixin" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(cassandra_cache_hitrate{}, job)"
   },
   {
    "name": "cassandra_cluster",
    "label": "Cassandra cluster",
    "query": "label_values(cassandra_cache_hitrate{job=~\"$job\"}, cassandra_cluster)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(cassandra_cache_hitrate{job=~\"$job\",cassandra_cluster=~\"$cassandra_cluster\"}, instance)"
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" }
  ]
 },
 "panels": [
  { "title": "Nodes", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "description": "The JVM CPU usage of this node.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "jvm_process_cpu_load{job=~\"$job\",cassandra_cluster=~\"$cassandra_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "description": "The JVM memory usage of this node.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_usage_used_bytes{job=~\"$job\",cassandra_cluster=~\"$cassandra_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} - {{ area }}"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "timeseries",
   "description": "The number of bytes being used by this node.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "cassandra_storage_load_count{job=~\"$job\",cassandra_cluster=~\"$cassandra_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Garbage collection duration",
   "type": "timeseries",
   "description": "The amount of time spent performing the most recent garbage collection on this node.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "jvm_gc_duration_seconds{job=~\"$job\",cassandra_cluster=~\"$cassandra_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Garbage collections",
   "type": "timeseries",
   "description": "The number of times garbage collection was performed on this node.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_count{job=~\"$job\",cassandra_cluster=~\"$cassandra_cluster\",instance=~\"$instance\", name=\"G1 Young Generation\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Keycache hit rate",
   "type": "timeseries",
   "description": "The keycache hit rate for this node.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "cassandra_cache_hitrate{job=~\"$job\",cassandra_cluster=~\"$cassandra_cluster\",instance=~\"$instance\", cache=\"KeyCache\"} * 100",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Hint messages",
   "type": "timeseries",
   "description": "The number of hint messages written to this node.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(cassandra_storage_totalhints_count{job=~\"$job\",cassandra_cluster=~\"$cassandra_cluster\",instance=~\"$instance\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Pending compaction tasks",
   "type": "timeseries",
   "description": "The number of currently pending compaction tasks on this node.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cassandra_compaction_pendingtasks{job=~\"$job\",cassandra_cluster=~\"$cassandra_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Blocked compaction tasks",
   "type": "timeseries",
   "description": "The number of currently blocked compaction tasks on this node.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cassandra_threadpools_currentlyblockedtasks_count{job=~\"$job\",cassandra_cluster=~\"$cassandra_cluster\",instance=~\"$instance\", threadpools=\"CompactionExecutor\", path=\"internal\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Writes",
   "type": "timeseries",
   "description": "The number of local writes across all keyspaces for this node.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(sum by (instance) (cassandra_keyspace_writelatency_seconds_count{job=~\"$job\",cassandra_cluster=~\"$cassandra_cluster\",instance=~\"$instance\"})[$__interval:] offset -$__interval)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Reads",
   "type": "timeseries",
   "description": "The number of local reads across all keyspaces for this node.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(sum by (instance) (cassandra_keyspace_readlatency_seconds_count{job=~\"$job\",cassandra_cluster=~\"$cassandra_cluster\",instance=~\"$instance\"})[$__interval:] offset -$__interval)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Write average latency",
   "type": "timeseries",
   "description": "Average write latency for the node.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(cassandra_keyspace_writelatency_seconds_average{job=~\"$job\",cassandra_cluster=~\"$cassandra_cluster\",instance=~\"$instance\"} >= 0)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Read average latency",
   "type": "timeseries",
   "description": "Average read latency for the node.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(cassandra_keyspace_readlatency_seconds_average{job=~\"$job\",cassandra_cluster=~\"$cassandra_cluster\",instance=~\"$instance\"} >= 0) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Write latency quartiles",
   "type": "timeseries",
   "description": "Local write latency quartiles for the nodes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(cassandra_keyspace_writelatency_seconds{job=~\"$job\",cassandra_cluster=~\"$cassandra_cluster\",instance=~\"$instance\", quantile=\"0.95\"} >= 0) by (instance)",
     "legendFormat": "{{ instance }} - p95"
    },
    {
     "expr": "sum(cassandra_keyspace_writelatency_seconds{job=~\"$job\",cassandra_cluster=~\"$cassandra_cluster\",instance=~\"$instance\", quantile=\"0.99\"} >= 0) by (instance)",
     "legendFormat": "{{ instance }} - p99"
    }
   ]
  },
  {
   "title": "Read latency quartiles",
   "type": "timeseries",
   "description": "Local read latency quartiles for the nodes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(cassandra_keyspace_readlatency_seconds{job=~\"$job\",cassandra_cluster=~\"$cassandra_cluster\",instance=~\"$instance\", quantile=\"0.95\"} >= 0) by (instance)",
     "legendFormat": "{{ instance }} - p95"
    },
    {
     "expr": "sum(cassandra_keyspace_readlatency_seconds{job=~\"$job\",cassandra_cluster=~\"$cassandra_cluster\",instance=~\"$instance\", quantile=\"0.99\"} >= 0) by (instance)",
     "legendFormat": "{{ instance }} - p99"
    }
   ]
  },
  {
   "title": "Cross-node latency",
   "type": "timeseries",
   "description": "The cross-node latency from the node's perspective.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(cassandra_messaging_crossnodelatency_seconds{job=~\"$job\",cassandra_cluster=~\"$cassandra_cluster\",instance=~\"$instance\", quantile=\"0.95\"} >= 0) by (instance)",
     "legendFormat": "{{ instance }} - p99"
    },
    {
     "expr": "sum(cassandra_messaging_crossnodelatency_seconds{job=~\"$job\",cassandra_cluster=~\"$cassandra_cluster\",instance=~\"$instance\", quantile=\"0.99\"} >= 0) by (instance)",
     "legendFormat": "{{ instance }} - p99"
    }
   ]
  }
 ]
}