{
 "title": "Apache Cassandra nodes",
 "tags": [ "apache-cassandra-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "loki_datasource", "label": "Loki Datasource", "query": "loki" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(cassandra_cache_size, job)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(cassandra_cache_size{job=~\"$job\"}, cluster)"
   },
   {
    "name": "cassandra_cluster",
    "label": "Cassandra cluster",
    "query": "label_values(cassandra_cache_size{job=~\"$job\"}, cassandra_cluster)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(cassandra_cache_size{job=~\"$job\", cassandra_cluster=~\"$cassandra_cluster\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Disk usage",
   "type": "timeseries",
   "description": "The number of bytes being used by this node",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "cassandra_storage_load_count{job=~\"$job\", cassandra_cluster=~\"$cassandra_cluster\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "description": "The JVM memory usage of this node",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_usage_used_bytes{job=~\"$job\", cassandra_cluster=~\"$cassandra_cluster\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - {{area}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "description": "The JVM CPU usage of this node",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "jvm_process_cpu_load{job=~\"$job\", cassandra_cluster=~\"$cassandra_cluster\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Garbage collection duration",
   "type": "timeseries",
   "description": "The amount of time spent performing the most recent garbage collection on this node",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "jvm_gc_duration_seconds{job=~\"$job\", cassandra_cluster=~\"$cassandra_cluster\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Garbage collections",
   "type": "timeseries",
   "description": "The number of times garbage collection was performed on this node",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "jvm_gc_collection_count{job=~\"$job\", cassandra_cluster=~\"$cassandra_cluster\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - {{name}}"
    }
   ]
  },
  {
   "title": "Keycache hit rate",
   "type": "timeseries",
   "description": "The keycache hit rate for this node",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "cassandra_cache_hitrate{job=~\"$job\", cassandra_cluster=~\"$cassandra_cluster\", instance=~\"$instance\", cache=\"KeyCache\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Hint messages",
   "type": "timeseries",
   "description": "The number of hint messages written to this node",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 12 },
   "targets": [
    {
     "expr": "cassandra_storage_totalhints_count{job=~\"$job\", cassandra_cluster=~\"$cassandra_cluster\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Pending compaction tasks",
   "type": "timeseries",
   "description": "The number of currently pending compaction tasks on this node",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "cassandra_compaction_pendingtasks{job=~\"$job\", cassandra_cluster=~\"$cassandra_cluster\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Blocked compaction tasks",
   "type": "timeseries",
   "description": "The number of currently blocked compaction tasks on this node",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 12 },
   "targets": [
    {
     "expr": "cassandra_threadpools_currentlyblockedtasks_count{job=~\"$job\", cassandra_cluster=~\"$cassandra_cluster\", instance=~\"$instance\", threadpools=\"CompactionExecutor\", path=\"internal\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Writes",
   "type": "timeseries",
   "description": "The number of local writes across all keyspaces for this node",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "increase((sum by (instance) (cassandra_keyspace_writelatency_seconds_count{job=~\"$job\", cassandra_cluster=~\"$cassandra_cluster\", instance=~\"$instance\"})[$__interval:]))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Reads",
   "type": "timeseries",
   "description": "The number of local reads across all keyspaces for this node",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "increase((sum by (instance) (cassandra_keyspace_readlatency_seconds_count{job=~\"$job\", cassandra_cluster=~\"$cassandra_cluster\", instance=~\"$instance\"})[$__interval:]))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Write average latency",
   "type": "timeseries",
   "description": "Average write latency for the node",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(cassandra_keyspace_writelatency_seconds_average{job=~\"$job\", cassandra_cluster=~\"$cassandra_cluster\", instance=~\"$instance\"} >= 0) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Read average latency",
   "type": "timeseries",
   "description": "Average read latency for the node",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(cassandra_keyspace_readlatency_seconds_average{job=~\"$job\", cassandra_cluster=~\"$cassandra_cluster\", instance=~\"$instance\"} >= 0) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Write latency quartiles",
   "type": "timeseries",
   "description": "Local write latency quartiles for the nodes",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(cassandra_keyspace_writelatency_seconds{job=~\"$job\", cassandra_cluster=~\"$cassandra_cluster\", instance=~\"$instance\", quantile=\"0.95\"}) by (instance)",
     "legendFormat": "{{ instance }} - p95"
    },
    {
     "expr": "sum(cassandra_keyspace_writelatency_seconds{job=~\"$job\", cassandra_cluster=~\"$cassandra_cluster\", instance=~\"$instance\", quantile=\"0.99\"} >= 0) by (instance)",
     "legendFormat": "{{ instance }} - p99"
    }
   ]
  },
  {
   "title": "Read latency quartiles",
   "type": "timeseries",
   "description": "Local read latency quartiles for the nodes",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(cassandra_keyspace_readlatency_seconds{job=~\"$job\", cassandra_cluster=~\"$cassandra_cluster\", instance=~\"$instance\", quantile=\"0.95\"} >= 0) by (instance)",
     "legendFormat": "{{ instance }} - p95"
    },
    {
     "expr": "sum(cassandra_keyspace_readlatency_seconds{job=~\"$job\", cassandra_cluster=~\"$cassandra_cluster\", instance=~\"$instance\", quantile=\"0.99\"} >= 0) by (instance)",
     "legendFormat": "{{ instance }} - p99"
    }
   ]
  },
  {
   "title": "Cross-node latency",
   "type": "timeseries",
   "description": "The cross-node latency from the node's perspective.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(cassandra_messaging_crossnodelatency_seconds{job=~\"$job\", cassandra_cluster=~\"$cassandra_cluster\", instance=~\"$instance\", quantile=\"0.95\"}) by (instance)",
     "legendFormat": "{{instance}} - p95"
    },
    {
     "expr": "sum(cassandra_messaging_crossnodelatency_seconds{job=~\"$job\", cassandra_cluster=~\"$cassandra_cluster\", instance=~\"$instance\", quantile=\"0.99\"}) by (instance)",
     "legendFormat": "{{instance}} - p99"
    }
   ]
  },
  {
   "title": "System logs",
   "type": "logs",
   "description": "Recent logs from the Cassandra system.logs file",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "{job=~\"$job\", cassandra_cluster=~\"$cassandra_cluster\", instance=~\"$instance\"} |= ``"
    }
   ]
  }
 ]
}