{
 "title": "Clickhouse overview",
 "tags": [ "clickhouse" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(ClickHouseMetrics_InterserverConnection{job=~\"integrations/clickhouse\"}, job)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(ClickHouseMetrics_InterserverConnection{job=~\"integrations/clickhouse\",job=~\"$job\"}, cluster)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(ClickHouseMetrics_InterserverConnection{job=~\"integrations/clickhouse\",job=~\"$job\",cluster=~\"$cluster\"}, instance)"
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" }
  ]
 },
 "panels": [
  { "title": "Queries", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Successful queries",
   "type": "timeseries",
   "description": "Rate of successful queries per second",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "/ sec" } },
   "targets": [
    {
     "expr": "rate(ClickHouseProfileEvents_SelectQuery{job=~\"integrations/clickhouse\",job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{ instance }} - Select query"
    },
    {
     "expr": "rate(ClickHouseProfileEvents_InsertQuery{job=~\"integrations/clickhouse\",job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{ instance }} - Insert query"
    },
    {
     "expr": "rate(ClickHouseProfileEvents_AsyncInsertQuery{job=~\"integrations/clickhouse\",job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{ instance }} - Async insert query"
    }
   ]
  },
  {
   "title": "Failed queries",
   "type": "timeseries",
   "description": "Rate of failed queries per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "/ sec" } },
   "targets": [
    {
     "expr": "rate(ClickHouseProfileEvents_FailedSelectQuery{job=~\"integrations/clickhouse\",job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{ instance }} - Failed select query"
    },
    {
     "expr": "rate(ClickHouseProfileEvents_FailedInsertQuery{job=~\"integrations/clickhouse\",job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{ instance }} - Failed insert query"
    }
   ]
  },
  {
   "title": "Rejected inserts",
   "type": "timeseries",
   "description": "Number of rejected inserts per second",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "/ sec" } },
   "targets": [
    {
     "expr": "rate(ClickHouseProfileEvents_RejectedInserts{job=~\"integrations/clickhouse\",job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{ instance }} - Rejected inserts"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 17 } },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "description": "Memory usage over time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "ClickHouseMetrics_MemoryTracking{job=~\"integrations/clickhouse\",job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} - Memory tracking"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "gauge",
   "description": "Percentage of memory allocated by ClickHouse compared to OS total",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(ClickHouseMetrics_MemoryTracking{job=~\"integrations/clickhouse\",job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"} / ClickHouseAsyncMetrics_OSMemoryTotal{job=~\"integrations/clickhouse\",job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}) * 100",
     "legendFormat": "{{ instance }} - Memory tracking percent"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 26 } },
  {
   "title": "Active connections",
   "type": "timeseries",
   "description": "Current number of connections to ClickHouse",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ClickHouseMetrics_TCPConnection{job=~\"integrations/clickhouse\",job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} - TCP connection"
    },
    {
     "expr": "ClickHouseMetrics_HTTPConnection{job=~\"integrations/clickhouse\",job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} - HTTP connection"
    },
    {
     "expr": "ClickHouseMetrics_MySQLConnection{job=~\"integrations/clickhouse\",job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} - MySQL connection"
    },
    {
     "expr": "ClickHouseMetrics_PostgreSQLConnection{job=~\"integrations/clickhouse\",job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} - PostgreSQL connection"
    }
   ]
  },
  {
   "title": "Network received",
   "type": "timeseries",
   "description": "Received network throughput",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(ClickHouseProfileEvents_NetworkReceiveBytes{job=~\"integrations/clickhouse\",job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{ instance }} - Network receive bytes"
    }
   ]
  },
  {
   "title": "Network transmitted",
   "type": "timeseries",
   "description": "Transmitted network throughput",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(ClickHouseProfileEvents_NetworkSendBytes{job=~\"integrations/clickhouse\",job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{ instance }} - Network send bytes"
    }
   ]
  }
 ]
}