{
 "title": "Clickhouse replica",
 "tags": [ "clickhouse" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(ClickHouseMetrics_InterserverConnection{job=~\"integrations/clickhouse\"}, job)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(ClickHouseMetrics_InterserverConnection{job=~\"integrations/clickhouse\",job=~\"$job\"}, cluster)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(ClickHouseMetrics_InterserverConnection{job=~\"integrations/clickhouse\",job=~\"$job\",cluster=~\"$cluster\"}, instance)"
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" }
  ]
 },
 "panels": [
  { "title": "Operations", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Interserver connections",
   "type": "timeseries",
   "description": "Number of connections due to interserver communication",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "ClickHouseMetrics_InterserverConnection{job=~\"integrations/clickhouse\",job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} - Interserver connections"
    }
   ]
  },
  {
   "title": "Replica queue size",
   "type": "timeseries",
   "description": "Number of replica tasks in queue",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "ClickHouseAsyncMetrics_ReplicasMaxQueueSize{job=~\"integrations/clickhouse\",job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} - Max queue size"
    }
   ]
  },
  {
   "title": "Replica operations",
   "type": "timeseries",
   "description": "Replica Operations over time to other nodes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "/ sec" } },
   "targets": [
    {
     "expr": "rate(ClickHouseProfileEvents_ReplicatedPartFetches{job=~\"integrations/clickhouse\",job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{ instance }} - Part fetches"
    },
    {
     "expr": "rate(ClickHouseProfileEvents_ReplicatedPartMerges{job=~\"integrations/clickhouse\",job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{ instance }} - Part merges"
    },
    {
     "expr": "rate(ClickHouseProfileEvents_ReplicatedPartMutations{job=~\"integrations/clickhouse\",job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{ instance }} - Part mutations"
    },
    {
     "expr": "rate(ClickHouseProfileEvents_ReplicatedPartChecks{job=~\"integrations/clickhouse\",job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{ instance }} - Part checks"
    }
   ]
  },
  {
   "title": "Replica read only",
   "type": "timeseries",
   "description": "Shows replicas in read-only state over time",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ClickHouseMetrics_ReadonlyReplica{job=~\"integrations/clickhouse\",job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} - Read only"
    }
   ]
  },
  { "title": "ZooKeeper", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 17 } },
  {
   "title": "ZooKeeper watches",
   "type": "timeseries",
   "description": "Current number of watches in ZooKeeper",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ClickHouseMetrics_ZooKeeperWatch{job=~\"integrations/clickhouse\",job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} - ZooKeeper watches"
    }
   ]
  },
  {
   "title": "ZooKeeper sessions",
   "type": "timeseries",
   "description": "Current number of sessions to ZooKeeper",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ClickHouseMetrics_ZooKeeperSession{job=~\"integrations/clickhouse\",job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} - ZooKeeper sessions"
    }
   ]
  },
  {
   "title": "ZooKeeper requests",
   "type": "timeseries",
   "description": "Current number of active requests to ZooKeeper",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ClickHouseMetrics_ZooKeeperRequest{job=~\"integrations/clickhouse\",job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} - ZooKeeper requests"
    }
   ]
  }
 ]
}