{
 "title": "InfluxDB cluster overview",
 "description": "Dashboard providing an overview of InfluxDB cluster performance and health.",
 "tags": [ "influxdb-mixin" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(influxdb_uptime_seconds{}, job)"
   },
   {
    "name": "influxdb_cluster",
    "label": "InfluxDB cluster",
    "query": "label_values(influxdb_uptime_seconds{job=~\"$job\"}, influxdb_cluster)"
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" },
   { "name": "k", "label": "Top node count", "query": "5 : 5,10 : 10,20 : 20,50 : 50" }
  ]
 },
 "panels": [
  { "title": "InfluxDB cluster overview", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1 } },
  {
   "title": "Servers",
   "type": "table",
   "description": "Statistics for each instance in the cluster.",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 1 },
   "targets": [
    {
     "expr": "influxdb_uptime_seconds{job=~\"$job\",influxdb_cluster=~\"$influxdb_cluster\"}",
     "legendFormat": "Uptime"
    },
    {
     "expr": "influxdb_buckets_total{job=~\"$job\",influxdb_cluster=~\"$influxdb_cluster\"}",
     "legendFormat": "Buckets"
    },
    {
     "expr": "influxdb_users_total{job=~\"$job\",influxdb_cluster=~\"$influxdb_cluster\"}",
     "legendFormat": "Users"
    },
    {
     "expr": "influxdb_replications_total{job=~\"$job\",influxdb_cluster=~\"$influxdb_cluster\"}",
     "legendFormat": "Replications"
    },
    {
     "expr": "influxdb_remotes_total{job=~\"$job\",influxdb_cluster=~\"$influxdb_cluster\"}",
     "legendFormat": "Remotes"
    },
    {
     "expr": "influxdb_scrapers_total{job=~\"$job\",influxdb_cluster=~\"$influxdb_cluster\"}",
     "legendFormat": "Scrapers"
    },
    {
     "expr": "influxdb_dashboards_total{job=~\"$job\",influxdb_cluster=~\"$influxdb_cluster\"}",
     "legendFormat": "Dashboards"
    }
   ]
  },
  { "title": "Queries and operations", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 9 } },
  {
   "title": "Top instances by HTTP API requests",
   "type": "timeseries",
   "description": "HTTP API request rate for the instances with the most traffic in the cluster.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk($k, sum by(job, influxdb_cluster, instance) (rate(http_api_requests_total{job=~\"$job\",influxdb_cluster=~\"$influxdb_cluster\"}[$__rate_interval])))",
     "legendFormat": "{{influxdb_cluster}} - {{instance}}"
    }
   ]
  },
  {
   "title": "HTTP API request duration",
   "type": "histogram",
   "description": "Time taken to respond to HTTP API requests for the cluster.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, job, influxdb_cluster) (rate(http_api_request_duration_seconds_bucket{job=~\"$job\",influxdb_cluster=~\"$influxdb_cluster\"}[$__rate_interval])))",
     "legendFormat": "{{influxdb_cluster}}"
    }
   ]
  },
  {
   "title": "HTTP API response codes",
   "type": "piechart",
   "description": "Rate of different HTTP response codes for the entire cluster.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(job, influxdb_cluster, response_code) (rate(http_api_requests_total{job=~\"$job\",influxdb_cluster=~\"$influxdb_cluster\"}[$__rate_interval]))",
     "legendFormat": "{{influxdb_cluster}} - {{response_code}}"
    }
   ]
  },
  {
   "title": "HTTP operations",
   "type": "timeseries",
   "description": "Rate of database operations from HTTP for the cluster.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(job, influxdb_cluster, status) (rate(http_query_request_count{job=~\"$job\",influxdb_cluster=~\"$influxdb_cluster\"}[$__rate_interval])) > 0",
     "legendFormat": "{{influxdb_cluster}} - query - {{status}}"
    },
    {
     "expr": "sum by(job, influxdb_cluster, status) (rate(http_write_request_count{job=~\"$job\",influxdb_cluster=~\"$influxdb_cluster\"}[$__rate_interval])) > 0",
     "legendFormat": "{{influxdb_cluster}} - write - {{status}}"
    }
   ]
  },
  {
   "title": "HTTP operation data",
   "type": "timeseries",
   "description": "Rate of data transferred for HTTP query and write operations in the cluster.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(job, influxdb_cluster) (rate(http_query_request_bytes{job=~\"$job\",influxdb_cluster=~\"$influxdb_cluster\"}[$__rate_interval]))",
     "legendFormat": "{{influxdb_cluster}} - query - request"
    },
    {
     "expr": "sum by(job, influxdb_cluster) (rate(http_query_response_bytes{job=~\"$job\",influxdb_cluster=~\"$influxdb_cluster\"}[$__rate_interval]))",
     "legendFormat": "{{influxdb_cluster}} - query - response"
    },
    {
     "expr": "sum by(job, influxdb_cluster) (rate(http_write_request_bytes{job=~\"$job\",influxdb_cluster=~\"$influxdb_cluster\"}[$__rate_interval]))",
     "legendFormat": "{{influxdb_cluster}} - write - request"
    },
    {
     "expr": "sum by(job, influxdb_cluster) (rate(http_write_response_bytes{job=~\"$job\",influxdb_cluster=~\"$influxdb_cluster\"}[$__rate_interval]))",
     "legendFormat": "{{influxdb_cluster}} - write - response"
    }
   ]
  },
  {
   "title": "Top instances by IQL query rate",
   "type": "timeseries",
   "description": "Rate of InfluxQL queries for the instances with the most traffic in the cluster.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk($k, sum by(job, influxdb_cluster, instance) (rate(influxql_service_requests_total{job=~\"$job\",influxdb_cluster=~\"$influxdb_cluster\"}[$__rate_interval])))",
     "legendFormat": "{{influxdb_cluster}} - {{instance}}"
    }
   ]
  },
  {
   "title": "IQL query response time",
   "type": "timeseries",
   "description": "Response time for recent InfluxQL queries, organized by result.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(job, influxdb_cluster, result) (increase(influxql_service_executing_duration_seconds_sum{job=~\"$job\",influxdb_cluster=~\"$influxdb_cluster\"}[$__rate_interval]))",
     "legendFormat": "{{influxdb_cluster}}"
    }
   ]
  },
  {
   "title": "BoltDB operations",
   "type": "timeseries",
   "description": "Rate of reads and writes to the underlying BoltDB storage engine for the entire cluster.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(boltdb_reads_total{job=~\"$job\",influxdb_cluster=~\"$influxdb_cluster\"}[$__rate_interval])",
     "legendFormat": "{{influxdb_cluster}} - read"
    },
    {
     "expr": "rate(boltdb_writes_total{job=~\"$job\",influxdb_cluster=~\"$influxdb_cluster\"}[$__rate_interval])",
     "legendFormat": "{{influxdb_cluster}} - write"
    }
   ]
  },
  { "title": "Task scheduler", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 34 } },
  {
   "title": "Active tasks",
   "type": "timeseries",
   "description": "Number of tasks currently being executed for the cluster.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(job, influxdb_cluster) (task_scheduler_current_execution{job=~\"$job\",influxdb_cluster=~\"$influxdb_cluster\"})",
     "legendFormat": "{{influxdb_cluster}}"
    }
   ]
  },
  {
   "title": "Active workers",
   "type": "timeseries",
   "description": "Number of workers currently running tasks on the cluster.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(job, influxdb_cluster) (task_executor_total_runs_active{job=~\"$job\",influxdb_cluster=~\"$influxdb_cluster\"})",
     "legendFormat": "{{influxdb_cluster}}"
    }
   ]
  },
  {
   "title": "Executions",
   "type": "timeseries",
   "description": "Rate of execution operations and execution failures for the cluster.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(job, influxdb_cluster) (task_scheduler_total_execution_calls{job=~\"$job\",influxdb_cluster=~\"$influxdb_cluster\"})",
     "legendFormat": "{{influxdb_cluster}} - total"
    },
    {
     "expr": "sum by(job, influxdb_cluster) (task_scheduler_total_execute_failure{job=~\"$job\",influxdb_cluster=~\"$influxdb_cluster\"})",
     "legendFormat": "{{influxdb_cluster}} - failed"
    }
   ]
  },
  {
   "title": "Schedules",
   "type": "timeseries",
   "description": "Rate of schedule operations and schedule operation failures for the cluster.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(task_scheduler_total_schedule_calls{job=~\"$job\",influxdb_cluster=~\"$influxdb_cluster\"}[$__rate_interval])",
     "legendFormat": "{{influxdb_cluster}} - total"
    },
    {
     "expr": "rate(task_scheduler_total_schedule_fails{job=~\"$job\",influxdb_cluster=~\"$influxdb_cluster\"}[$__rate_interval])",
     "legendFormat": "{{influxdb_cluster}} - failed"
    }
   ]
  },
  { "title": "Go", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 51 } },
  {
   "title": "Top instances by heap memory usage",
   "type": "timeseries",
   "description": "Heap memory usage for the largest instances in the cluster.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk($k, sum by(job, influxdb_cluster, instance) (go_memstats_heap_alloc_bytes{job=~\"$job\",influxdb_cluster=~\"$influxdb_cluster\"}/clamp_min(go_memstats_heap_idle_bytes{job=~\"$job\",influxdb_cluster=~\"$influxdb_cluster\"} + go_memstats_heap_alloc_bytes{job=~\"$job\",influxdb_cluster=~\"$influxdb_cluster\"}, 1)))",
     "legendFormat": "{{influxdb_cluster}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Top instances by GC CPU usage",
   "type": "timeseries",
   "description": "Fraction of CPU time used for garbage collection for the top instances in the cluster.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "go_memstats_gc_cpu_fraction{job=~\"$job\",influxdb_cluster=~\"$influxdb_cluster\"}",
     "legendFormat": "{{influxdb_cluster}} - {{instance}}"
    }
   ]
  }
 ]
}