{
 "title": "Envoy / Overview",
 "description": "A dashboard that monitors Envoy with a focus on giving an generic overview. The dashboards were generated using [envoy-mixin](https://github.com/adinhodovic/envoy-mixin). Open issues and create feature requests in the repository.",
 "tags": [
  "envoy",
  "envoy-mixin",
  "gateway"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(envoy_cluster_upstream_rq_xx{}, cluster)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(envoy_cluster_upstream_rq_xx{cluster=\"$cluster\"}, namespace)"
   },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(envoy_cluster_upstream_rq_xx{cluster=\"$cluster\", namespace=~\"$namespace\"}, job)"
   },
   {
    "name": "envoy_cluster_name",
    "label": "Envoy Cluster Name",
    "query": "label_values(envoy_cluster_upstream_rq_xx{cluster=\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}, envoy_cluster_name)"
   },
   {
    "name": "envoy_http_conn_manager_prefix",
    "label": "Envoy HTTP Conn Manager Prefix",
    "query": "label_values(envoy_http_downstream_rq_xx{cluster=\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}, envoy_http_conn_manager_prefix)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(envoy_listener_http_downstream_rq_xx{cluster=\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}, pod)"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Envoy Pods",
   "type": "stat",
   "description": "The total number of Envoy pods being monitored.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(\n  count (\n    envoy_cluster_upstream_rq_total{\n      cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n\n    }\n  ) by (pod)\n)\n"
    }
   ]
  },
  {
   "title": "Upstreams",
   "type": "stat",
   "description": "The total number of upstreams being monitored.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(\n  count(\n    envoy_cluster_upstream_rq_total{\n      cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n\n    }\n  ) by (envoy_cluster_name)\n)\n"
    }
   ]
  },
  {
   "title": "Downstreams",
   "type": "stat",
   "description": "The total number of downstreams being monitored.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(\n  count(\n    envoy_http_downstream_rq_total{\n      cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n\n    }\n  ) by (envoy_http_conn_manager_prefix)\n)\n"
    }
   ]
  },
  {
   "title": "Upstream Active Connections",
   "type": "stat",
   "description": "The total number of active upstream connections across all Envoy clusters being monitored.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  envoy_cluster_upstream_cx_active{\n    cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n\n  }\n)\n"
    }
   ]
  },
  {
   "title": "Downstream Active Connections",
   "type": "stat",
   "description": "The total number of active downstream connections across all Envoy clusters being monitored.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  envoy_http_downstream_cx_active{\n    cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n\n  }\n)\n"
    }
   ]
  },
  {
   "title": "Membership Healthy Percent",
   "type": "stat",
   "description": "The percentage of healthy members in the Envoy clusters being monitored.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(\n  envoy_cluster_membership_healthy{\n    cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n\n  }\n)\n/\nsum(\n  envoy_cluster_membership_total{\n    cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n\n  }\n)\n* 100\n"
    }
   ]
  },
  {
   "title": "Upstream Rate by Envoy Cluster Name [1h]",
   "type": "piechart",
   "description": "The distribution of upstream request rates by Envoy cluster name.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(20,\n  sum(\n    rate(\n      envoy_cluster_upstream_rq_total{\n        cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n,\nenvoy_cluster_name=~\"$envoy_cluster_name\"\n\n      }[1h]\n    )\n  ) by (envoy_cluster_name)\n)\n",
     "legendFormat": "{{ envoy_cluster_name }}"
    }
   ]
  },
  {
   "title": "Upstream Rate by Code Class [1h]",
   "type": "piechart",
   "description": "The distribution of upstream request rates by response code class.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    envoy_cluster_upstream_rq_xx{\n      cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n,\nenvoy_cluster_name=~\"$envoy_cluster_name\"\n\n    }[1h]\n  )\n) by (envoy_response_code_class)\n",
     "legendFormat": "{{ envoy_response_code_class }}xx"
    }
   ]
  },
  {
   "title": "Downstream Rate by Envoy HTTP Conn Manager Prefix [1h]",
   "type": "piechart",
   "description": "The distribution of downstream request rates by Envoy HTTP connection manager prefix.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(20,\n  sum(\n    rate(\n      envoy_http_downstream_rq_total{\n        cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n,\nenvoy_http_conn_manager_prefix=~\"$envoy_http_conn_manager_prefix\"\n\n      }[1h]\n    )\n  ) by (envoy_http_conn_manager_prefix)\n)\n",
     "legendFormat": "{{ envoy_http_conn_manager_prefix }}"
    }
   ]
  },
  {
   "title": "Upstream Rate by Pod [1h]",
   "type": "piechart",
   "description": "The distribution of upstream request rates by pod.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    envoy_cluster_upstream_rq_total{\n      cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n,\nenvoy_cluster_name=~\"$envoy_cluster_name\"\n\n    }[1h]\n  )\n) by (pod)\n",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  { "title": "Upstream", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Upstream Rate",
   "type": "timeseries",
   "description": "The upstream request rate over time.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    envoy_cluster_upstream_rq_total{\n      cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n,\nenvoy_cluster_name=~\"$envoy_cluster_name\"\n\n    }[$__rate_interval]\n  )\n)\n",
     "legendFormat": "Upstream"
    }
   ]
  },
  {
   "title": "Upstream Latency",
   "type": "timeseries",
   "description": "The upstream latency percentiles over time.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.5,\n  sum(\n    rate(\n      envoy_cluster_upstream_rq_time_bucket{\n        cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n,\nenvoy_cluster_name=~\"$envoy_cluster_name\"\n\n      }[$__rate_interval]\n    )\n  ) by (le)\n)\n",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum(\n    rate(\n      envoy_cluster_upstream_rq_time_bucket{\n        cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n,\nenvoy_cluster_name=~\"$envoy_cluster_name\"\n\n      }[$__rate_interval]\n    )\n  ) by (le)\n)\n",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum(\n    rate(\n      envoy_cluster_upstream_rq_time_bucket{\n        cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n,\nenvoy_cluster_name=~\"$envoy_cluster_name\"\n\n      }[$__rate_interval]\n    )\n  ) by (le)\n)\n",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Upstream Success Rate (Excluding 4xx errors)",
   "type": "timeseries",
   "description": "The upstream success rate over time, counting 5xx response codes as errors.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    envoy_cluster_upstream_rq_xx{\n      cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n,\nenvoy_cluster_name=~\"$envoy_cluster_name\"\n,\n      envoy_response_code_class!=\"5\"\n    }[$__rate_interval]\n  )\n)\n/\nsum(\n  rate(\n    envoy_cluster_upstream_rq_xx{\n      cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n,\nenvoy_cluster_name=~\"$envoy_cluster_name\"\n\n    }[$__rate_interval]\n  )\n)\n* 100\n",
     "legendFormat": "Success Rate"
    }
   ]
  },
  {
   "title": "Upstream Success Rate (Including 4xx errors)",
   "type": "timeseries",
   "description": "The upstream success rate over time, counting 4xx and 5xx response codes as errors.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    envoy_cluster_upstream_rq_xx{\n      cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n,\nenvoy_cluster_name=~\"$envoy_cluster_name\"\n,\n      envoy_response_code_class!~\"4|5\"\n    }[$__rate_interval]\n  )\n)\n/\nsum(\n  rate(\n    envoy_cluster_upstream_rq_xx{\n      cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n,\nenvoy_cluster_name=~\"$envoy_cluster_name\"\n\n    }[$__rate_interval]\n  )\n)\n* 100\n",
     "legendFormat": "Success Rate"
    }
   ]
  },
  {
   "title": "Upstream Overview [1h]",
   "type": "table",
   "description": "An overview table showing various upstream metrics by Envoy cluster name [1h].",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(40,\n  sum(\n    rate(\n      envoy_cluster_upstream_rq_total{\n        cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n,\nenvoy_cluster_name=~\"$envoy_cluster_name\"\n\n      }[1h]\n    )\n  ) by (envoy_cluster_name)\n)\n"
    },
    {
     "expr": "sum(\n  rate(\n    envoy_cluster_upstream_rq_xx{\n      cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n,\nenvoy_cluster_name=~\"$envoy_cluster_name\"\n,\n      envoy_response_code_class!=\"5\"\n    }[1h]\n  )\n) by (job, envoy_cluster_name)\n/\nsum(\n  rate(\n    envoy_cluster_upstream_rq_xx{\n      cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n,\nenvoy_cluster_name=~\"$envoy_cluster_name\"\n\n    }[1h]\n  )\n) by (job, envoy_cluster_name)\n* 100\nand on (envoy_cluster_name) (\n  topk(40,\n  sum(\n    rate(\n      envoy_cluster_upstream_rq_total{\n        cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n,\nenvoy_cluster_name=~\"$envoy_cluster_name\"\n\n      }[1h]\n    )\n  ) by (envoy_cluster_name)\n)\n\n)\n\n"
    },
    {
     "expr": "sum(\n  rate(\n    envoy_cluster_upstream_rq_xx{\n      cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n,\nenvoy_cluster_name=~\"$envoy_cluster_name\"\n,\n      envoy_response_code_class!~\"4|5\"\n    }[1h]\n  )\n) by (job, envoy_cluster_name)\n/\nsum(\n  rate(\n    envoy_cluster_upstream_rq_xx{\n      cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n,\nenvoy_cluster_name=~\"$envoy_cluster_name\"\n\n    }[1h]\n  )\n) by (job, envoy_cluster_name)\n* 100\nand on (envoy_cluster_name) (\n  topk(40,\n  sum(\n    rate(\n      envoy_cluster_upstream_rq_total{\n        cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n,\nenvoy_cluster_name=~\"$envoy_cluster_name\"\n\n      }[1h]\n    )\n  ) by (envoy_cluster_name)\n)\n\n)\n\n"
    },
    {
     "expr": "histogram_quantile(\n  0.5,\n  sum(\n    rate(\n      envoy_cluster_upstream_rq_time_bucket{\n        cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n,\nenvoy_cluster_name=~\"$envoy_cluster_name\"\n\n      }[1h]\n    )\n  ) by (le, job, envoy_cluster_name)\n)\nand on (envoy_cluster_name) (\n  topk(40,\n  sum(\n    rate(\n      envoy_cluster_upstream_rq_total{\n        cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n,\nenvoy_cluster_name=~\"$envoy_cluster_name\"\n\n      }[1h]\n    )\n  ) by (envoy_cluster_name)\n)\n\n)\n\n"
    },
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum(\n    rate(\n      envoy_cluster_upstream_rq_time_bucket{\n        cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n,\nenvoy_cluster_name=~\"$envoy_cluster_name\"\n\n      }[1h]\n    )\n  ) by (le, job, envoy_cluster_name)\n)\nand on (envoy_cluster_name) (\n  topk(40,\n  sum(\n    rate(\n      envoy_cluster_upstream_rq_total{\n        cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n,\nenvoy_cluster_name=~\"$envoy_cluster_name\"\n\n      }[1h]\n    )\n  ) by (envoy_cluster_name)\n)\n\n)\n\n"
    },
    {
     "expr": "sum(\n  avg_over_time(\n    envoy_cluster_upstream_cx_active{\n      cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n,\nenvoy_cluster_name=~\"$envoy_cluster_name\"\n\n    }[1h]\n  )\n) by (job, envoy_cluster_name)\nand on (envoy_cluster_name) (\n  topk(40,\n  sum(\n    rate(\n      envoy_cluster_upstream_rq_total{\n        cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n,\nenvoy_cluster_name=~\"$envoy_cluster_name\"\n\n      }[1h]\n    )\n  ) by (envoy_cluster_name)\n)\n\n)\n\n"
    },
    {
     "expr": "sum(\n  increase(\n    envoy_cluster_upstream_cx_destroy{\n      cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n,\nenvoy_cluster_name=~\"$envoy_cluster_name\"\n\n    }[1h]\n  )\n) by (job, envoy_cluster_name)\nand on (envoy_cluster_name) (\n  topk(40,\n  sum(\n    rate(\n      envoy_cluster_upstream_rq_total{\n        cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n,\nenvoy_cluster_name=~\"$envoy_cluster_name\"\n\n      }[1h]\n    )\n  ) by (envoy_cluster_name)\n)\n\n)\n\n"
    },
    {
     "expr": "sum(\n  envoy_cluster_membership_healthy{\n    cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n,\nenvoy_cluster_name=~\"$envoy_cluster_name\"\n\n  }\n) by (job, envoy_cluster_name)\n/\nsum(\n  envoy_cluster_membership_total{\n    cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n,\nenvoy_cluster_name=~\"$envoy_cluster_name\"\n\n  }\n) by (job, envoy_cluster_name)\n* 100\nand on (envoy_cluster_name) (\n  topk(40,\n  sum(\n    rate(\n      envoy_cluster_upstream_rq_total{\n        cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n,\nenvoy_cluster_name=~\"$envoy_cluster_name\"\n\n      }[1h]\n    )\n  ) by (envoy_cluster_name)\n)\n\n)\n\n"
    }
   ]
  },
  { "title": "Downstream", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Downstream Rate by Envoy HTTP Conn Manager Prefix",
   "type": "timeseries",
   "description": "The downstream request rate by Envoy HTTP connection manager prefix over time.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(20,\n  sum(\n    rate(\n      envoy_http_downstream_rq_total{\n        cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n,\nenvoy_http_conn_manager_prefix=~\"$envoy_http_conn_manager_prefix\"\n\n      }[$__rate_interval]\n    )\n  ) by (envoy_http_conn_manager_prefix)\n)\n",
     "legendFormat": "{{ envoy_http_conn_manager_prefix }}"
    }
   ]
  },
  {
   "title": "Downstream Latency",
   "type": "timeseries",
   "description": "The downstream latency percentiles over time.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.5,\n  sum(\n    rate(\n      envoy_http_downstream_rq_time_bucket{\n        cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n,\nenvoy_http_conn_manager_prefix=~\"$envoy_http_conn_manager_prefix\"\n\n      }[$__rate_interval]\n    )\n  ) by (le)\n)\n",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum(\n    rate(\n      envoy_http_downstream_rq_time_bucket{\n        cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n,\nenvoy_http_conn_manager_prefix=~\"$envoy_http_conn_manager_prefix\"\n\n      }[$__rate_interval]\n    )\n  ) by (le)\n)\n",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum(\n    rate(\n      envoy_http_downstream_rq_time_bucket{\n        cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n,\nenvoy_http_conn_manager_prefix=~\"$envoy_http_conn_manager_prefix\"\n\n      }[$__rate_interval]\n    )\n  ) by (le)\n)\n",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Downstream Success Rate (Excluding 4xx errors)",
   "type": "timeseries",
   "description": "The downstream success rate over time, counting 5xx response codes as errors.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    envoy_http_downstream_rq_xx{\n      cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n,\nenvoy_http_conn_manager_prefix=~\"$envoy_http_conn_manager_prefix\"\n,\n      envoy_response_code_class!=\"5\"\n    }[$__rate_interval]\n  )\n)\n/\nsum(\n  rate(\n    envoy_http_downstream_rq_xx{\n      cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n,\nenvoy_http_conn_manager_prefix=~\"$envoy_http_conn_manager_prefix\"\n\n    }[$__rate_interval]\n  )\n)\n* 100\n",
     "legendFormat": "Success Rate"
    }
   ]
  },
  {
   "title": "Downstream Success Rate (Including 4xx errors)",
   "type": "timeseries",
   "description": "The downstream success rate over time, counting 4xx and 5xx response codes as errors.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    envoy_http_downstream_rq_xx{\n      cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n,\nenvoy_http_conn_manager_prefix=~\"$envoy_http_conn_manager_prefix\"\n,\n      envoy_response_code_class!~\"4|5\"\n    }[$__rate_interval]\n  )\n)\n/\nsum(\n  rate(\n    envoy_http_downstream_rq_xx{\n      cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n,\nenvoy_http_conn_manager_prefix=~\"$envoy_http_conn_manager_prefix\"\n\n    }[$__rate_interval]\n  )\n)\n* 100\n",
     "legendFormat": "Success Rate"
    }
   ]
  },
  {
   "title": "Downstream Overview [1h]",
   "type": "table",
   "description": "An overview table showing various downstream metrics by Envoy HTTP connection manager prefix [1h].",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(40,\n  sum(\n    rate(\n      envoy_http_downstream_rq_total{\n        cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n,\nenvoy_http_conn_manager_prefix=~\"$envoy_http_conn_manager_prefix\"\n\n      }[1h]\n    )\n  ) by (envoy_http_conn_manager_prefix)\n)\n"
    },
    {
     "expr": "sum(\n  rate(\n    envoy_http_downstream_rq_xx{\n      cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n,\nenvoy_http_conn_manager_prefix=~\"$envoy_http_conn_manager_prefix\"\n,\n      envoy_response_code_class!=\"5\"\n    }[1h]\n  )\n) by (job, envoy_http_conn_manager_prefix)\n/\nsum(\n  rate(\n    envoy_http_downstream_rq_xx{\n      cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n,\nenvoy_http_conn_manager_prefix=~\"$envoy_http_conn_manager_prefix\"\n\n    }[1h]\n  )\n) by (job, envoy_http_conn_manager_prefix)\n* 100\nand on (envoy_http_conn_manager_prefix) (\n  topk(40,\n  sum(\n    rate(\n      envoy_http_downstream_rq_total{\n        cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n,\nenvoy_http_conn_manager_prefix=~\"$envoy_http_conn_manager_prefix\"\n\n      }[1h]\n    )\n  ) by (envoy_http_conn_manager_prefix)\n)\n\n)\n\n"
    },
    {
     "expr": "sum(\n  rate(\n    envoy_http_downstream_rq_xx{\n      cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n,\nenvoy_http_conn_manager_prefix=~\"$envoy_http_conn_manager_prefix\"\n,\n      envoy_response_code_class!~\"4|5\"\n    }[1h]\n  )\n) by (job, envoy_http_conn_manager_prefix)\n/\nsum(\n  rate(\n    envoy_http_downstream_rq_xx{\n      cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n,\nenvoy_http_conn_manager_prefix=~\"$envoy_http_conn_manager_prefix\"\n\n    }[1h]\n  )\n) by (job, envoy_http_conn_manager_prefix)\n* 100\nand on (envoy_http_conn_manager_prefix) (\n  topk(40,\n  sum(\n    rate(\n      envoy_http_downstream_rq_total{\n        cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n,\nenvoy_http_conn_manager_prefix=~\"$envoy_http_conn_manager_prefix\"\n\n      }[1h]\n    )\n  ) by (envoy_http_conn_manager_prefix)\n)\n\n)\n\n"
    },
    {
     "expr": "histogram_quantile(\n  0.5,\n  sum(\n    rate(\n      envoy_http_downstream_rq_time_bucket{\n        cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n,\nenvoy_http_conn_manager_prefix=~\"$envoy_http_conn_manager_prefix\"\n\n      }[1h]\n    )\n  ) by (le, job, envoy_http_conn_manager_prefix)\n)\nand on (envoy_http_conn_manager_prefix) (\n  topk(40,\n  sum(\n    rate(\n      envoy_http_downstream_rq_total{\n        cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n,\nenvoy_http_conn_manager_prefix=~\"$envoy_http_conn_manager_prefix\"\n\n      }[1h]\n    )\n  ) by (envoy_http_conn_manager_prefix)\n)\n\n)\n\n"
    },
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum(\n    rate(\n      envoy_http_downstream_rq_time_bucket{\n        cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n,\nenvoy_http_conn_manager_prefix=~\"$envoy_http_conn_manager_prefix\"\n\n      }[1h]\n    )\n  ) by (le, job, envoy_http_conn_manager_prefix)\n)\nand on (envoy_http_conn_manager_prefix) (\n  topk(40,\n  sum(\n    rate(\n      envoy_http_downstream_rq_total{\n        cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n,\nenvoy_http_conn_manager_prefix=~\"$envoy_http_conn_manager_prefix\"\n\n      }[1h]\n    )\n  ) by (envoy_http_conn_manager_prefix)\n)\n\n)\n\n"
    },
    {
     "expr": "sum(\n  avg_over_time(\n    envoy_http_downstream_cx_active{\n      cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n,\nenvoy_http_conn_manager_prefix=~\"$envoy_http_conn_manager_prefix\"\n\n    }[1h]\n  )\n) by (job, envoy_http_conn_manager_prefix)\nand on (envoy_http_conn_manager_prefix) (\n  topk(40,\n  sum(\n    rate(\n      envoy_http_downstream_rq_total{\n        cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n,\nenvoy_http_conn_manager_prefix=~\"$envoy_http_conn_manager_prefix\"\n\n      }[1h]\n    )\n  ) by (envoy_http_conn_manager_prefix)\n)\n\n)\n\n"
    },
    {
     "expr": "sum(\n  increase(\n    envoy_http_downstream_cx_destroy{\n      cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n,\nenvoy_http_conn_manager_prefix=~\"$envoy_http_conn_manager_prefix\"\n\n    }[1h]\n  )\n) by (job, envoy_http_conn_manager_prefix)\nand on (envoy_http_conn_manager_prefix) (\n  topk(40,\n  sum(\n    rate(\n      envoy_http_downstream_rq_total{\n        cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n,\nenvoy_http_conn_manager_prefix=~\"$envoy_http_conn_manager_prefix\"\n\n      }[1h]\n    )\n  ) by (envoy_http_conn_manager_prefix)\n)\n\n)\n\n"
    }
   ]
  },
  { "title": "SSL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "SSL Expirations by Envoy TLS Certificate",
   "type": "timeseries",
   "description": "The SSL certificate expiration times by Envoy TLS certificate over time.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "targets": [
    {
     "expr": "min(\n  envoy_listener_ssl_certificate_expiration_unix_time_seconds{\n    cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n\n  }\n) by (job, envoy_tls_certificate)\n* 1000\n",
     "legendFormat": "{{ envoy_tls_certificate }}"
    }
   ]
  }
 ]
}