{
 "title": "Presto coordinator",
 "tags": [ "presto-mixin" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(presto_metadata_DiscoveryNodeManager_ActiveResourceManagerCount{}, job)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(presto_metadata_DiscoveryNodeManager_ActiveResourceManagerCount{job=~\"$job\"}, cluster)"
   },
   {
    "name": "presto_cluster",
    "label": "Presto cluster",
    "query": "label_values(presto_metadata_DiscoveryNodeManager_ActiveResourceManagerCount{job=~\"$job\",cluster=~\"$cluster\"}, presto_cluster)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(presto_metadata_DiscoveryNodeManager_ActiveResourceManagerCount{job=~\"$job\",cluster=~\"$cluster\",presto_cluster=~\"$presto_cluster\"}, instance)"
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" }
  ]
 },
 "panels": [
  { "title": "Coordinator", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Non-heap memory usage",
   "type": "gauge",
   "description": "Non-heap memory usage",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg (jvm_nonheap_memory_used{job=~\"$job\",cluster=~\"$cluster\",presto_cluster=~\"$presto_cluster\",instance=~\"$instance\"} / clamp_min((jvm_nonheap_memory_used{job=~\"$job\",cluster=~\"$cluster\",presto_cluster=~\"$presto_cluster\",instance=~\"$instance\"} + jvm_nonheap_memory_committed{job=~\"$job\",cluster=~\"$cluster\",presto_cluster=~\"$presto_cluster\",instance=~\"$instance\"}), 1))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Heap memory usage",
   "type": "gauge",
   "description": "Heap memory usage",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg (jvm_heap_memory_used{job=~\"$job\",cluster=~\"$cluster\",presto_cluster=~\"$presto_cluster\",instance=~\"$instance\"} / clamp_min((jvm_heap_memory_used{job=~\"$job\",cluster=~\"$cluster\",presto_cluster=~\"$presto_cluster\",instance=~\"$instance\"} + jvm_heap_memory_committed{job=~\"$job\",cluster=~\"$cluster\",presto_cluster=~\"$presto_cluster\",instance=~\"$instance\"}), 1))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Error failures - one minute count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "presto_QueryManager_InternalFailures_OneMinute_Count{job=~\"$job\",cluster=~\"$cluster\",presto_cluster=~\"$presto_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - internal"
    }
   ]
  },
  {
   "title": "Normal query - one minute count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "presto_QueryManager_CompletedQueries_OneMinute_Count{job=~\"$job\",cluster=~\"$cluster\",presto_cluster=~\"$presto_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - completed"
    },
    {
     "expr": "presto_QueryManager_RunningQueries{job=~\"$job\",cluster=~\"$cluster\",presto_cluster=~\"$presto_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - running"
    },
    {
     "expr": "presto_QueryManager_StartedQueries_OneMinute_Count{job=~\"$job\",cluster=~\"$cluster\",presto_cluster=~\"$presto_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - started"
    }
   ]
  },
  {
   "title": "Abnormal query - one minute count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "presto_QueryManager_FailedQueries_OneMinute_Count{job=~\"$job\",cluster=~\"$cluster\",presto_cluster=~\"$presto_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - failed"
    },
    {
     "expr": "presto_QueryManager_AbandonedQueries_OneMinute_Count{job=~\"$job\",cluster=~\"$cluster\",presto_cluster=~\"$presto_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - abandoned"
    },
    {
     "expr": "presto_QueryManager_CanceledQueries_OneMinute_Count{job=~\"$job\",cluster=~\"$cluster\",presto_cluster=~\"$presto_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - canceled"
    }
   ]
  },
  {
   "title": "Normal query - one minute rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "presto_QueryManager_CompletedQueries_OneMinute_Rate{job=~\"$job\",cluster=~\"$cluster\",presto_cluster=~\"$presto_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - completed"
    },
    {
     "expr": "presto_QueryManager_RunningQueries{job=~\"$job\",cluster=~\"$cluster\",presto_cluster=~\"$presto_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - running"
    },
    {
     "expr": "presto_QueryManager_StartedQueries_OneMinute_Rate{job=~\"$job\",cluster=~\"$cluster\",presto_cluster=~\"$presto_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - started"
    }
   ]
  },
  {
   "title": "Abnormal query - one minute rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(presto_QueryManager_FailedQueries_TotalCount{job=~\"$job\",cluster=~\"$cluster\",presto_cluster=~\"$presto_cluster\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - failed"
    },
    {
     "expr": "rate(presto_QueryManager_AbandonedQueries_TotalCount{job=~\"$job\",cluster=~\"$cluster\",presto_cluster=~\"$presto_cluster\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - abandoned"
    },
    {
     "expr": "rate(presto_QueryManager_CanceledQueries_TotalCount{job=~\"$job\",cluster=~\"$cluster\",presto_cluster=~\"$presto_cluster\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - canceled"
    }
   ]
  },
  {
   "title": "Query execution time - one minute count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "presto_QueryManager_ExecutionTime_OneMinute_P50{job=~\"$job\",cluster=~\"$cluster\",presto_cluster=~\"$presto_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - p50"
    },
    {
     "expr": "presto_QueryManager_ExecutionTime_OneMinute_P75{job=~\"$job\",cluster=~\"$cluster\",presto_cluster=~\"$presto_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - p75"
    },
    {
     "expr": "presto_QueryManager_ExecutionTime_OneMinute_P95{job=~\"$job\",cluster=~\"$cluster\",presto_cluster=~\"$presto_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - p95"
    },
    {
     "expr": "presto_QueryManager_ExecutionTime_OneMinute_P99{job=~\"$job\",cluster=~\"$cluster\",presto_cluster=~\"$presto_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - p99"
    }
   ]
  },
  {
   "title": "CPU time consumed - one minute count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "presto_QueryManager_ConsumedCpuTimeSecs_OneMinute_Count{job=~\"$job\",cluster=~\"$cluster\",presto_cluster=~\"$presto_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU input throughput - one minute count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "presto_QueryManager_CpuInputByteRate_OneMinute_Total{job=~\"$job\",cluster=~\"$cluster\",presto_cluster=~\"$presto_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 41 } },
  {
   "title": "Garbage collection count / $__interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_count{job=~\"$job\",cluster=~\"$cluster\",presto_cluster=~\"$presto_cluster\",instance=~\"$instance\", name=\"G1 Young Generation\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Garbage collection duration",
   "type": "timeseries",
   "description": "The average duration for each garbage collection operation in the JVM.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "jvm_gc_duration{job=~\"$job\",cluster=~\"$cluster\",presto_cluster=~\"$presto_cluster\",instance=~\"$instance\", name=\"G1 Young Generation\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory committed",
   "type": "timeseries",
   "description": "The heap and non-heap memory committed by the JVM.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_heap_memory_committed{job=~\"$job\",cluster=~\"$cluster\",presto_cluster=~\"$presto_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - heap"
    },
    {
     "expr": "jvm_nonheap_memory_committed{job=~\"$job\",cluster=~\"$cluster\",presto_cluster=~\"$presto_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - non heap"
    }
   ]
  },
  {
   "title": "Memory used",
   "type": "timeseries",
   "description": "The heap and non-heap memory used by the JVM.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_heap_memory_used{job=~\"$job\",cluster=~\"$cluster\",presto_cluster=~\"$presto_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - heap"
    },
    {
     "expr": "jvm_nonheap_memory_used{job=~\"$job\",cluster=~\"$cluster\",presto_cluster=~\"$presto_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - non heap"
    }
   ]
  }
 ]
}