{
 "title": "Presto worker",
 "tags": [ "presto-mixin" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(presto_metadata_DiscoveryNodeManager_ActiveResourceManagerCount{}, job)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(presto_metadata_DiscoveryNodeManager_ActiveResourceManagerCount{job=~\"$job\"}, cluster)"
   },
   {
    "name": "presto_cluster",
    "label": "Presto cluster",
    "query": "label_values(presto_metadata_DiscoveryNodeManager_ActiveResourceManagerCount{job=~\"$job\",cluster=~\"$cluster\"}, presto_cluster)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(presto_metadata_DiscoveryNodeManager_ActiveResourceManagerCount{job=~\"$job\",cluster=~\"$cluster\",presto_cluster=~\"$presto_cluster\"}, instance)"
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" }
  ]
 },
 "panels": [
  { "title": "Worker", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Non-heap memory usage",
   "type": "gauge",
   "description": "Non-heap memory usage",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg (jvm_nonheap_memory_used{job=~\"$job\",cluster=~\"$cluster\",presto_cluster=~\"$presto_cluster\",instance=~\"$instance\"} / clamp_min((jvm_nonheap_memory_used{job=~\"$job\",cluster=~\"$cluster\",presto_cluster=~\"$presto_cluster\",instance=~\"$instance\"} + jvm_nonheap_memory_committed{job=~\"$job\",cluster=~\"$cluster\",presto_cluster=~\"$presto_cluster\",instance=~\"$instance\"}), 1))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Heap memory usage",
   "type": "gauge",
   "description": "Heap memory usage",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg (jvm_heap_memory_used{job=~\"$job\",cluster=~\"$cluster\",presto_cluster=~\"$presto_cluster\",instance=~\"$instance\"} / clamp_min((jvm_heap_memory_used{job=~\"$job\",cluster=~\"$cluster\",presto_cluster=~\"$presto_cluster\",instance=~\"$instance\"} + jvm_heap_memory_committed{job=~\"$job\",cluster=~\"$cluster\",presto_cluster=~\"$presto_cluster\",instance=~\"$instance\"}), 1))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Queued tasks",
   "type": "timeseries",
   "description": "The number of tasks that are being queued by the task executor.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "presto_TaskExecutor_ProcessorExecutor_QueuedTaskCount{job=~\"$job\",cluster=~\"$cluster\",presto_cluster=~\"$presto_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Failed & completed tasks",
   "type": "timeseries",
   "description": "The rate at which tasks have failed and completed.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(presto_TaskExecutor_ProcessorExecutor_FailedTaskCount{job=~\"$job\",cluster=~\"$cluster\",presto_cluster=~\"$presto_cluster\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - failed"
    },
    {
     "expr": "rate(presto_TaskExecutor_ProcessorExecutor_CompletedTaskCount{job=~\"$job\",cluster=~\"$cluster\",presto_cluster=~\"$presto_cluster\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - completed"
    }
   ]
  },
  {
   "title": "Output positions - one minute rate",
   "type": "timeseries",
   "description": "The rate of rows (or records) produced by an operation.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "presto_TaskManager_OutputPositions_OneMinute_Rate{job=~\"$job\",cluster=~\"$cluster\",presto_cluster=~\"$presto_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Executor pool size",
   "type": "timeseries",
   "description": "The pool size of the task notification executor.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "presto_TaskExecutor_ProcessorExecutor_PoolSize{job=~\"$job\",cluster=~\"$cluster\",presto_cluster=~\"$presto_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - task notification"
    },
    {
     "expr": "presto_TaskExecutor_ProcessorExecutor_CorePoolSize{job=~\"$job\",cluster=~\"$cluster\",presto_cluster=~\"$presto_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - process executor core"
    },
    {
     "expr": "presto_TaskExecutor_ProcessorExecutor_PoolSize{job=~\"$job\",cluster=~\"$cluster\",presto_cluster=~\"$presto_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - process executor"
    }
   ]
  },
  {
   "title": "Memory pool",
   "type": "timeseries",
   "description": "The amount of Presto memory available.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "presto_MemoryPool_general_FreeBytes{job=~\"$job\",cluster=~\"$cluster\",presto_cluster=~\"$presto_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - free"
    },
    {
     "expr": "presto_MemoryPool_reserved_FreeBytes{job=~\"$job\",cluster=~\"$cluster\",presto_cluster=~\"$presto_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - reserved free"
    }
   ]
  },
  {
   "title": "Data processing throughput - one minute rate",
   "type": "timeseries",
   "description": "The rate at which volumes of data are being processed.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "presto_TaskManager_InputDataSize_OneMinute_Rate{job=~\"$job\",cluster=~\"$cluster\",presto_cluster=~\"$presto_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - input"
    },
    {
     "expr": "presto_TaskManager_OutputDataSize_OneMinute_Rate{job=~\"$job\",cluster=~\"$cluster\",presto_cluster=~\"$presto_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - output"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 25 } },
  {
   "title": "Garbage collection count / $__interval",
   "type": "timeseries",
   "description": "The recent increase in the number of garbage collection events for the JVM.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_count{job=~\"$job\",cluster=~\"$cluster\",presto_cluster=~\"$presto_cluster\",instance=~\"$instance\", name=\"G1 Young Generation\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Garbage collection duration",
   "type": "timeseries",
   "description": "The average duration for each garbage collection operation in the JVM.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "jvm_gc_duration{job=~\"$job\",cluster=~\"$cluster\",presto_cluster=~\"$presto_cluster\",instance=~\"$instance\", name=\"G1 Young Generation\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory committed",
   "type": "timeseries",
   "description": "The heap and non-heap memory committed by the JVM.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_heap_memory_committed{job=~\"$job\",cluster=~\"$cluster\",presto_cluster=~\"$presto_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - heap"
    },
    {
     "expr": "jvm_nonheap_memory_committed{job=~\"$job\",cluster=~\"$cluster\",presto_cluster=~\"$presto_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - non heap"
    }
   ]
  },
  {
   "title": "Memory used",
   "type": "timeseries",
   "description": "The heap and non-heap memory used by the JVM.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_heap_memory_used{job=~\"$job\",cluster=~\"$cluster\",presto_cluster=~\"$presto_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - heap"
    },
    {
     "expr": "jvm_nonheap_memory_used{job=~\"$job\",cluster=~\"$cluster\",presto_cluster=~\"$presto_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - non heap"
    }
   ]
  }
 ]
}