{
 "title": "Cloudflare worker overview",
 "tags": [ "cloudflare-mixin" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(cloudflare_zone_requests_total{}, job)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(cloudflare_zone_requests_total{job=~\"$job\"}, cluster)"
   },
   {
    "name": "zone",
    "label": "Zone",
    "query": "label_values(cloudflare_zone_requests_total{job=~\"$job\",cluster=~\"$cluster\"}, zone)"
   },
   {
    "name": "script_name",
    "label": "Script",
    "query": "label_values(cloudflare_zone_requests_total{job=~\"$job\",cluster=~\"$cluster\",zone=~\"$zone\"}, script_name)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(cloudflare_zone_requests_total{job=~\"$job\",cluster=~\"$cluster\",zone=~\"$zone\",script_name=~\"$script_name\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Workers", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Worker CPU time quantiles",
   "type": "timeseries",
   "description": "CPU time consumed by the worker.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "cloudflare_worker_cpu_time{job=~\"$job\",cluster=~\"$cluster\",zone=~\"$zone\",script_name=~\"$script_name\",instance=~\"$instance\"}",
     "legendFormat": "{{ script_name }} - {{ quantile }}"
    }
   ]
  },
  {
   "title": "Worker duration quantiles",
   "type": "timeseries",
   "description": "Duration of worker execution.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "cloudflare_worker_duration{job=~\"$job\",cluster=~\"$cluster\",zone=~\"$zone\",script_name=~\"$script_name\",instance=~\"$instance\"}",
     "legendFormat": "{{ script_name }} - {{ quantile }}"
    }
   ]
  },
  {
   "title": "Worker requests",
   "type": "timeseries",
   "description": "Rate of requests to the worker.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(cloudflare_worker_requests_count{job=~\"$job\",cluster=~\"$cluster\",zone=~\"$zone\",script_name=~\"$script_name\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{ script_name }}"
    }
   ]
  },
  {
   "title": "Worker errors / $__interval",
   "type": "timeseries",
   "description": "Number of errors from the worker.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(cloudflare_worker_errors_count{job=~\"$job\",cluster=~\"$cluster\",zone=~\"$zone\",script_name=~\"$script_name\",instance=~\"$instance\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{ script_name }}"
    }
   ]
  }
 ]
}