{
 "title": "Apache HBase RegionServer overview",
 "tags": [ "apache-hbase-mixin" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(server_num_region_servers{}, job)"
   },
   {
    "name": "hbase_cluster",
    "label": "Apache HBase cluster",
    "query": "label_values(server_num_region_servers{job=~\"$job\"}, hbase_cluster)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(server_num_region_servers{job=~\"$job\",hbase_cluster=~\"$hbase_cluster\"}, instance)"
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" }
  ]
 },
 "panels": [
  { "title": "RegionServer overview", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Regions",
   "type": "stat",
   "description": "The number of regions hosted by the RegionServer.",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(job,hbase_cluster) (server_region_count{job=~\"$job\",hbase_cluster=~\"$hbase_cluster\",instance=~\"$instance\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Store files",
   "type": "stat",
   "description": "The number of store files on disk currently managed by the RegionServer.",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(job,hbase_cluster) (server_store_file_count{job=~\"$job\",hbase_cluster=~\"$hbase_cluster\",instance=~\"$instance\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Store file size",
   "type": "stat",
   "description": "The total size of the store files on disk managed by the RegionServer.",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(job,hbase_cluster) (server_store_file_size{job=~\"$job\",hbase_cluster=~\"$hbase_cluster\",instance=~\"$instance\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "RPC connections",
   "type": "stat",
   "description": "The number of open connections to the RegionServer.",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(job,hbase_cluster) (region_server_num_open_connections{job=~\"$job\",hbase_cluster=~\"$hbase_cluster\",instance=~\"$instance\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVM heap memory usage",
   "type": "timeseries",
   "description": "Heap memory usage for the JVM.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "jvm_metrics_mem_heap_used_m{job=~\"$job\",hbase_cluster=~\"$hbase_cluster\",instance=~\"$instance\", processname=\"RegionServer\"} / clamp_min(jvm_metrics_mem_heap_committed_m{job=~\"$job\",hbase_cluster=~\"$hbase_cluster\",instance=~\"$instance\", processname=\"RegionServer\"}, 1)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Requests received",
   "type": "timeseries",
   "description": "The rate of requests received by the RegionServer.",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(server_total_request_count{job=~\"$job\",hbase_cluster=~\"$hbase_cluster\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Requests overview",
   "type": "piechart",
   "description": "Requests received by the RegionServer, broken down by type.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(job,hbase_cluster) (rate(server_read_request_count{job=~\"$job\",hbase_cluster=~\"$hbase_cluster\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum by(job,hbase_cluster) (rate(server_write_request_count{job=~\"$job\",hbase_cluster=~\"$hbase_cluster\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "write"
    },
    {
     "expr": "sum by(job,hbase_cluster) (rate(server_cp_request_count{job=~\"$job\",hbase_cluster=~\"$hbase_cluster\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "copy"
    },
    {
     "expr": "sum by(job,hbase_cluster) (rate(server_filtered_read_request_count{job=~\"$job\",hbase_cluster=~\"$hbase_cluster\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "filtered read"
    },
    {
     "expr": "sum by(job,hbase_cluster) (rate(server_rpc_get_request_count{job=~\"$job\",hbase_cluster=~\"$hbase_cluster\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "rpc get"
    },
    {
     "expr": "sum by(job,hbase_cluster) (rate(server_rpc_scan_request_count{job=~\"$job\",hbase_cluster=~\"$hbase_cluster\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "rpc scan"
    },
    {
     "expr": "sum by(job,hbase_cluster) (rate(server_rpc_full_scan_request_count{job=~\"$job\",hbase_cluster=~\"$hbase_cluster\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "rpc full scan"
    },
    {
     "expr": "sum by(job,hbase_cluster) (rate(server_rpc_mutate_request_count{job=~\"$job\",hbase_cluster=~\"$hbase_cluster\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "rpc mutate"
    },
    {
     "expr": "sum by(job,hbase_cluster) (rate(server_rpc_multi_request_count{job=~\"$job\",hbase_cluster=~\"$hbase_cluster\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "rpc multi"
    }
   ]
  },
  {
   "title": "Region count",
   "type": "timeseries",
   "description": "The number of regions hosted by the RegionServer.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "server_region_count{job=~\"$job\",hbase_cluster=~\"$hbase_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "RPC connection count",
   "type": "timeseries",
   "description": "The number of open connections to the RegionServer.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "region_server_num_open_connections{job=~\"$job\",hbase_cluster=~\"$hbase_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Store file count",
   "type": "timeseries",
   "description": "The number of store files on disk currently managed by the RegionServer.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "server_store_file_count{job=~\"$job\",hbase_cluster=~\"$hbase_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Store file size",
   "type": "timeseries",
   "description": "The total size of the store files on disk managed by the RegionServer.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "server_store_file_size{job=~\"$job\",hbase_cluster=~\"$hbase_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Queued calls",
   "type": "timeseries",
   "description": "The number of calls waiting to be processed by the RegionServer.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(job,hbase_cluster) (region_server_num_calls_in_general_queue{job=~\"$job\",hbase_cluster=~\"$hbase_cluster\",instance=~\"$instance\"})",
     "legendFormat": "general"
    },
    {
     "expr": "sum by(job,hbase_cluster) (region_server_num_calls_in_replication_queue{job=~\"$job\",hbase_cluster=~\"$hbase_cluster\",instance=~\"$instance\"})",
     "legendFormat": "replication"
    },
    {
     "expr": "sum by(job,hbase_cluster) (region_server_num_calls_in_read_queue{job=~\"$job\",hbase_cluster=~\"$hbase_cluster\",instance=~\"$instance\"})",
     "legendFormat": "read"
    },
    {
     "expr": "sum by(job,hbase_cluster) (region_server_num_calls_in_write_queue{job=~\"$job\",hbase_cluster=~\"$hbase_cluster\",instance=~\"$instance\"})",
     "legendFormat": "write"
    },
    {
     "expr": "sum by(job,hbase_cluster) (region_server_num_calls_in_scan_queue{job=~\"$job\",hbase_cluster=~\"$hbase_cluster\",instance=~\"$instance\"})",
     "legendFormat": "scan"
    },
    {
     "expr": "sum by(job,hbase_cluster) (region_server_num_calls_in_priority_queue{job=~\"$job\",hbase_cluster=~\"$hbase_cluster\",instance=~\"$instance\"})",
     "legendFormat": "priority"
    }
   ]
  },
  {
   "title": "Slow operations",
   "type": "timeseries",
   "description": "The rate of operations that are slow, as determined by HBase.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(job,hbase_cluster) (rate(server_slow_append_count{job=~\"$job\",hbase_cluster=~\"$hbase_cluster\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "append"
    },
    {
     "expr": "sum by(job,hbase_cluster) (rate(server_slow_put_count{job=~\"$job\",hbase_cluster=~\"$hbase_cluster\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "put"
    },
    {
     "expr": "sum by(job,hbase_cluster) (rate(server_slow_delete_count{job=~\"$job\",hbase_cluster=~\"$hbase_cluster\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "delete"
    },
    {
     "expr": "sum by(job,hbase_cluster) (rate(server_slow_get_count{job=~\"$job\",hbase_cluster=~\"$hbase_cluster\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "get"
    },
    {
     "expr": "sum by(job,hbase_cluster) (rate(server_slow_increment_count{job=~\"$job\",hbase_cluster=~\"$hbase_cluster\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "increment"
    }
   ]
  },
  {
   "title": "Cache hit percentage",
   "type": "timeseries",
   "description": "The percent of time that requests hit the cache.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "server_block_cache_express_hit_percent{job=~\"$job\",hbase_cluster=~\"$hbase_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Authentications",
   "type": "timeseries",
   "description": "The rate of successful and unsuccessful authentications.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(job,hbase_cluster) (rate(region_server_authentication_successes{job=~\"$job\",hbase_cluster=~\"$hbase_cluster\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{hbase_cluster}} - rs success"
    },
    {
     "expr": "sum by(job,hbase_cluster) (rate(region_server_authentication_failures{job=~\"$job\",hbase_cluster=~\"$hbase_cluster\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{hbase_cluster}} - rs failure"
    }
   ]
  }
 ]
}