{
 "title": "Apache HBase cluster overview",
 "tags": [ "apache-hbase-mixin" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(server_num_region_servers{}, job)"
   },
   {
    "name": "hbase_cluster",
    "label": "Apache HBase cluster",
    "query": "label_values(server_num_region_servers{job=~\"$job\"}, hbase_cluster)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(server_num_region_servers{job=~\"$job\",hbase_cluster=~\"$hbase_cluster\"}, instance)"
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" }
  ]
 },
 "panels": [
  { "title": "Cluster overview", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Master status history",
   "type": "status-history",
   "description": "Displays the current active and backup masters.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max without (clusterid,deadregionservers,liveregionservers,servername,zookeeperquorum,isactivemaster) (server_num_region_servers{job=~\"$job\",hbase_cluster=~\"$hbase_cluster\",instance=~\"$instance\", isactivemaster=\"true\"} * 0  + 1 )",
     "legendFormat": "{{hbase_cluster}}"
    },
    {
     "expr": "(max without (clusterid,deadregionservers,liveregionservers,servername,zookeeperquorum,isactivemaster) (server_num_region_servers{job=~\"$job\",hbase_cluster=~\"$hbase_cluster\",instance=~\"$instance\", isactivemaster=\"false\"}) * 0)",
     "legendFormat": "{{hbase_cluster}}"
    }
   ]
  },
  {
   "title": "Live RegionServers",
   "type": "stat",
   "description": "Number of RegionServers that are currently live.",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "server_num_region_servers{job=~\"$job\",hbase_cluster=~\"$hbase_cluster\",instance=~\"$instance\", isactivemaster=\"true\"}",
     "legendFormat": "{{hbase_cluster}}"
    }
   ]
  },
  {
   "title": "Dead RegionServers",
   "type": "stat",
   "description": "Number of RegionServers that are currently dead.",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "server_num_dead_region_servers{job=~\"$job\",hbase_cluster=~\"$hbase_cluster\",instance=~\"$instance\", isactivemaster=\"true\"}",
     "legendFormat": "{{hbase_cluster}}"
    }
   ]
  },
  {
   "title": "Servers",
   "type": "table",
   "description": "Servers for a cluster.",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 9 },
   "targets": [
    {
     "expr": "label_replace(server_num_region_servers{job=~\"$job\",hbase_cluster=~\"$hbase_cluster\",instance=~\"$instance\"}, \"master_instance\", \"$1\", \"instance\", \"(.+)\")",
     "legendFormat": "{{hbase_cluster}}"
    },
    {
     "expr": "label_replace(server_num_reference_files{job=~\"$job\",hbase_cluster=~\"$hbase_cluster\",instance=~\"$instance\"}, \"region_server_instance\", \"$1\", \"instance\", \"(.+)\")",
     "legendFormat": "{{hbase_cluster}}"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "alertlist",
   "description": "Panel to report on the status of integration alerts.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by(job,hbase_cluster) (master_num_open_connections{job=~\"$job\",hbase_cluster=~\"$hbase_cluster\",instance=~\"$instance\"})",
     "legendFormat": "{{hbase_cluster}} - masters"
    }
   ]
  },
  {
   "title": "JVM heap memory usage",
   "type": "timeseries",
   "description": "Heap memory usage for the JVM.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "jvm_metrics_mem_heap_used_m{job=~\"$job\",hbase_cluster=~\"$hbase_cluster\",instance=~\"$instance\", processname=~\"Master\"} / clamp_min(jvm_metrics_mem_heap_committed_m{job=~\"$job\",hbase_cluster=~\"$hbase_cluster\",instance=~\"$instance\", processname=~\"Master\"}, 1)",
     "legendFormat": "{{hbase_cluster}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "description": "Number of open connections to the cluster.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(job,hbase_cluster) (master_num_open_connections{job=~\"$job\",hbase_cluster=~\"$hbase_cluster\",instance=~\"$instance\"})",
     "legendFormat": "{{hbase_cluster}} - masters"
    },
    {
     "expr": "sum by(job,hbase_cluster) (region_server_num_open_connections{job=~\"$job\",hbase_cluster=~\"$hbase_cluster\",instance=~\"$instance\"})",
     "legendFormat": "{{hbase_cluster}} - RegionServers"
    }
   ]
  },
  {
   "title": "Authentications",
   "type": "timeseries",
   "description": "Volume of successful and unsuccessful authentications.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(job,hbase_cluster) (rate(master_authentication_successes{job=~\"$job\",hbase_cluster=~\"$hbase_cluster\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{hbase_cluster}} - masters success"
    },
    {
     "expr": "sum by(job,hbase_cluster) (rate(master_authentication_failures{job=~\"$job\",hbase_cluster=~\"$hbase_cluster\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{hbase_cluster}} - masters failure"
    },
    {
     "expr": "sum by(job,hbase_cluster) (rate(region_server_authentication_successes{job=~\"$job\",hbase_cluster=~\"$hbase_cluster\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{hbase_cluster}} - rs success"
    },
    {
     "expr": "sum by(job,hbase_cluster) (rate(region_server_authentication_failures{job=~\"$job\",hbase_cluster=~\"$hbase_cluster\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{hbase_cluster}} - rs failure"
    }
   ]
  },
  {
   "title": "Master queue size",
   "type": "timeseries",
   "description": "The size of the queue of requests, operations, and tasks to be processed by the master.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "master_queue_size{job=~\"$job\",hbase_cluster=~\"$hbase_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{hbase_cluster}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Master queued calls",
   "type": "timeseries",
   "description": "The number of calls waiting to be processed by the master.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(job,hbase_cluster) (master_num_calls_in_general_queue{job=~\"$job\",hbase_cluster=~\"$hbase_cluster\",instance=~\"$instance\"})",
     "legendFormat": "{{hbase_cluster}} - general"
    },
    {
     "expr": "sum by(job,hbase_cluster) (master_num_calls_in_replication_queue{job=~\"$job\",hbase_cluster=~\"$hbase_cluster\",instance=~\"$instance\"})",
     "legendFormat": "{{hbase_cluster}} - replication"
    },
    {
     "expr": "sum by(job,hbase_cluster) (master_num_calls_in_read_queue{job=~\"$job\",hbase_cluster=~\"$hbase_cluster\",instance=~\"$instance\"})",
     "legendFormat": "{{hbase_cluster}} - read"
    },
    {
     "expr": "sum by(job,hbase_cluster) (master_num_calls_in_write_queue{job=~\"$job\",hbase_cluster=~\"$hbase_cluster\",instance=~\"$instance\"})",
     "legendFormat": "{{hbase_cluster}} - write"
    },
    {
     "expr": "sum by(job,hbase_cluster) (master_num_calls_in_scan_queue{job=~\"$job\",hbase_cluster=~\"$hbase_cluster\",instance=~\"$instance\"})",
     "legendFormat": "{{hbase_cluster}} - scan"
    },
    {
     "expr": "sum by(job,hbase_cluster) (master_num_calls_in_priority_queue{job=~\"$job\",hbase_cluster=~\"$hbase_cluster\",instance=~\"$instance\"})",
     "legendFormat": "{{hbase_cluster}} - priority"
    }
   ]
  },
  {
   "title": "Regions in transition",
   "type": "timeseries",
   "description": "The number of regions in transition for the cluster.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "assignment_manager_rit_count{job=~\"$job\",hbase_cluster=~\"$hbase_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{hbase_cluster}}"
    },
    {
     "expr": "assignment_manager_rit_count_over_threshold{job=~\"$job\",hbase_cluster=~\"$hbase_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{hbase_cluster}} - old"
    }
   ]
  },
  {
   "title": "Oldest region in transition",
   "type": "timeseries",
   "description": "The age of the longest region in transition for the master of the cluster.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "assignment_manager_rit_oldest_age{job=~\"$job\",hbase_cluster=~\"$hbase_cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{hbase_cluster}}"
    }
   ]
  }
 ]
}