{
 "title": "Apache ActiveMQ queue overview",
 "tags": [ "apache-activemq" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(activemq_memory_usage_ratio{}, job)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(activemq_memory_usage_ratio{job=~\"$job\"}, cluster)"
   },
   {
    "name": "activemq_cluster",
    "label": "ActiveMQ cluster",
    "query": "label_values(activemq_memory_usage_ratio{job=~\"$job\",cluster=~\"$cluster\"}, activemq_cluster)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(activemq_memory_usage_ratio{job=~\"$job\",cluster=~\"$cluster\",activemq_cluster=~\"$activemq_cluster\"}, instance)"
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" },
   {
    "name": "k_selector",
    "label": "Top queue count",
    "query": "2 : 2,4 : 4,6 : 6,8 : 8,10 : 10"
   },
   { "name": "name", "label": "Queue by name" }
  ]
 },
 "panels": [
  { "title": "Queues", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Queue count",
   "type": "stat",
   "description": "Number of active queues.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "count (activemq_queue_queue_size{job=~\"$job\",cluster=~\"$cluster\",activemq_cluster=~\"$activemq_cluster\",instance=~\"$instance\"})",
     "legendFormat": "{{activemq_cluster}} - {{ instance }} - {{ destination }}"
    }
   ]
  },
  {
   "title": "Total queue size",
   "type": "stat",
   "description": "Total number of messages in all queues.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "sum (activemq_queue_queue_size{job=~\"$job\",cluster=~\"$cluster\",activemq_cluster=~\"$activemq_cluster\",instance=~\"$instance\"})",
     "legendFormat": "{{activemq_cluster}} - {{ instance }} - {{ destination }}"
    }
   ]
  },
  {
   "title": "Total queue producers",
   "type": "stat",
   "description": "Total number of queue producers.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum (activemq_queue_producer_count{job=~\"$job\",cluster=~\"$cluster\",activemq_cluster=~\"$activemq_cluster\",instance=~\"$instance\"})",
     "legendFormat": "{{activemq_cluster}} - {{ instance }} - {{ destination }}"
    }
   ]
  },
  {
   "title": "Total queue consumers",
   "type": "stat",
   "description": "Total number of queue consumers.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "sum (activemq_queue_consumer_count{job=~\"$job\",cluster=~\"$cluster\",activemq_cluster=~\"$activemq_cluster\",instance=~\"$instance\"})",
     "legendFormat": "{{activemq_cluster}} - {{ instance }} - {{ destination }}"
    }
   ]
  },
  {
   "title": "Queue enqueue rate",
   "type": "timeseries",
   "description": "Rate of messages being enqueued to queues.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "/ sec" } },
   "targets": [
    {
     "expr": "topk by (job,cluster,activemq_cluster, instance) ($k_selector, rate(activemq_queue_enqueue_count{job=~\"$job\",cluster=~\"$cluster\",activemq_cluster=~\"$activemq_cluster\",instance=~\"$instance\", destination=~\".*$name.*\"}[$__rate_interval]))",
     "legendFormat": "{{activemq_cluster}} - {{ instance }} - {{ destination }}"
    }
   ]
  },
  {
   "title": "Queue dequeue rate",
   "type": "timeseries",
   "description": "Rate of messages being dequeued from queues.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "/ sec" } },
   "targets": [
    {
     "expr": "topk by (job,cluster,activemq_cluster, instance) ($k_selector, rate(activemq_queue_dequeue_count{job=~\"$job\",cluster=~\"$cluster\",activemq_cluster=~\"$activemq_cluster\",instance=~\"$instance\", destination=~\".*$name.*\"}[$__rate_interval]))",
     "legendFormat": "{{activemq_cluster}} - {{ instance }} - {{ destination }}"
    }
   ]
  },
  {
   "title": "Queue average enqueue time",
   "type": "timeseries",
   "description": "Average time to enqueue messages to queues.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk by (job,cluster,activemq_cluster, instance) ($k_selector, activemq_queue_average_enqueue_time{job=~\"$job\",cluster=~\"$cluster\",activemq_cluster=~\"$activemq_cluster\",instance=~\"$instance\", destination=~\".*$name.*\"})",
     "legendFormat": "{{activemq_cluster}} - {{ instance }} - {{ destination }}"
    }
   ]
  },
  {
   "title": "Queue expired rate",
   "type": "timeseries",
   "description": "Rate of messages expiring in queues.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "/ sec" } },
   "targets": [
    {
     "expr": "topk by (job,cluster,activemq_cluster, instance) ($k_selector, rate(activemq_queue_expired_count{job=~\"$job\",cluster=~\"$cluster\",activemq_cluster=~\"$activemq_cluster\",instance=~\"$instance\", destination=~\".*$name.*\"}[$__rate_interval]))",
     "legendFormat": "{{activemq_cluster}} - {{ instance }} - {{ destination }}"
    }
   ]
  },
  {
   "title": "Queue average message size",
   "type": "timeseries",
   "description": "Average size of messages in queues.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk by (job,cluster,activemq_cluster, instance) ($k_selector, activemq_queue_average_message_size{job=~\"$job\",cluster=~\"$cluster\",activemq_cluster=~\"$activemq_cluster\",instance=~\"$instance\", destination=~\".*$name.*\"})",
     "legendFormat": "{{activemq_cluster}} - {{ instance }} - {{ destination }}"
    }
   ]
  },
  {
   "title": "Queue summary",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "rate(activemq_queue_enqueue_count{job=~\"$job\",cluster=~\"$cluster\",activemq_cluster=~\"$activemq_cluster\",instance=~\"$instance\", destination=~\".*$name.*\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "rate(activemq_queue_dequeue_count{job=~\"$job\",cluster=~\"$cluster\",activemq_cluster=~\"$activemq_cluster\",instance=~\"$instance\", destination=~\".*$name.*\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "activemq_queue_average_enqueue_time{job=~\"$job\",cluster=~\"$cluster\",activemq_cluster=~\"$activemq_cluster\",instance=~\"$instance\", destination=~\".*$name.*\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "activemq_queue_average_message_size{job=~\"$job\",cluster=~\"$cluster\",activemq_cluster=~\"$activemq_cluster\",instance=~\"$instance\", destination=~\".*$name.*\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}