{
 "title": "Apache ActiveMQ cluster overview",
 "tags": [ "apache-activemq" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(activemq_memory_usage_ratio{}, job)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(activemq_memory_usage_ratio{job=~\"$job\"}, cluster)"
   },
   {
    "name": "activemq_cluster",
    "label": "ActiveMQ cluster",
    "query": "label_values(activemq_memory_usage_ratio{job=~\"$job\",cluster=~\"$cluster\"}, activemq_cluster)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(activemq_memory_usage_ratio{job=~\"$job\",cluster=~\"$cluster\",activemq_cluster=~\"$activemq_cluster\"}, instance)"
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" }
  ]
 },
 "panels": [
  { "title": "Cluster Overview", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Clusters",
   "type": "stat",
   "description": "Number of Apache ActiveMQ clusters.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "count(activemq_memory_usage_ratio{job=~\"$job\",cluster=~\"$cluster\",activemq_cluster=~\"$activemq_cluster\",instance=~\"$instance\"})",
     "legendFormat": "{{instance}}: Count"
    }
   ]
  },
  {
   "title": "Brokers",
   "type": "stat",
   "description": "Number of broker instances across clusters.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "count(activemq_memory_usage_ratio{job=~\"$job\",cluster=~\"$cluster\",activemq_cluster=~\"$activemq_cluster\",instance=~\"$instance\"})",
     "legendFormat": "{{instance}}: Brokers"
    }
   ]
  },
  {
   "title": "Producers",
   "type": "stat",
   "description": "Number of message producers active on destinations across clusters.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum (activemq_queue_producer_count{job=~\"$job\",cluster=~\"$cluster\",activemq_cluster=~\"$activemq_cluster\",instance=~\"$instance\", destination!~\"ActiveMQ.Advisory.*\"})",
     "legendFormat": "{{instance}}: Producers"
    }
   ]
  },
  {
   "title": "Consumers",
   "type": "stat",
   "description": "The number of consumers subscribed to destinations across clusters.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "sum (activemq_queue_consumer_count{job=~\"$job\",cluster=~\"$cluster\",activemq_cluster=~\"$activemq_cluster\",instance=~\"$instance\", destination!~\"ActiveMQ.Advisory.*\"})",
     "legendFormat": "{{instance}}: Consumers"
    }
   ]
  },
  {
   "title": "Enqueue / $__interval",
   "type": "timeseries",
   "description": "Number of messages that have been sent to destinations in a cluster.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (activemq_cluster, job) (increase(activemq_queue_enqueue_count{job=~\"$job\",cluster=~\"$cluster\",activemq_cluster=~\"$activemq_cluster\",instance=~\"$instance\"}[$__interval] offset $__interval)) + sum by (activemq_cluster, job) (increase(activemq_topic_enqueue_count{job=~\"$job\",cluster=~\"$cluster\",activemq_cluster=~\"$activemq_cluster\",instance=~\"$instance\", destination!~\"ActiveMQ.Advisory.*\"}[$__interval] offset $__interval))",
     "legendFormat": "{{ activemq_cluster }}"
    }
   ]
  },
  {
   "title": "Dequeue / $__interval",
   "type": "timeseries",
   "description": "Number of messages that have been acknowledged (and removed) from destinations in a cluster.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by (activemq_cluster, job) (increase(activemq_queue_dequeue_count{job=~\"$job\",cluster=~\"$cluster\",activemq_cluster=~\"$activemq_cluster\",instance=~\"$instance\"}[$__interval] offset $__interval)) + sum by (activemq_cluster, job) (increase(activemq_topic_dequeue_count{job=~\"$job\",cluster=~\"$cluster\",activemq_cluster=~\"$activemq_cluster\",instance=~\"$instance\", destination!~\"ActiveMQ.Advisory.*\"}[$__interval] offset $__interval))",
     "legendFormat": "{{ activemq_cluster }}"
    }
   ]
  },
  {
   "title": "Average temporary memory usage",
   "type": "bargauge",
   "description": "Average percentage of temporary memory used across clusters.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (activemq_cluster, job) (activemq_temp_usage_ratio{job=~\"$job\",cluster=~\"$cluster\",activemq_cluster=~\"$activemq_cluster\",instance=~\"$instance\"})",
     "legendFormat": "{{ activemq_cluster }}"
    }
   ]
  },
  {
   "title": "Average store memory usage",
   "type": "bargauge",
   "description": "Average percentage of store memory used across clusters.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (activemq_cluster, job) (activemq_store_usage_ratio{job=~\"$job\",cluster=~\"$cluster\",activemq_cluster=~\"$activemq_cluster\",instance=~\"$instance\"})",
     "legendFormat": "{{ activemq_cluster }}"
    }
   ]
  },
  {
   "title": "Average broker memory usage",
   "type": "bargauge",
   "description": "Average percentage of broker memory used across clusters.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (activemq_cluster, job) (activemq_memory_usage_ratio{job=~\"$job\",cluster=~\"$cluster\",activemq_cluster=~\"$activemq_cluster\",instance=~\"$instance\"})",
     "legendFormat": "{{ activemq_cluster }}"
    }
   ]
  }
 ]
}