{
 "title": "MSSQL overview",
 "tags": [ "mssql" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(mssql_io_stall_seconds_total{job=~\"integrations/mssql\"}, job)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(mssql_io_stall_seconds_total{job=~\"integrations/mssql\",job=~\"$job\"}, cluster)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(mssql_io_stall_seconds_total{job=~\"integrations/mssql\",job=~\"$job\",cluster=~\"$cluster\"}, instance)"
   },
   {
    "name": "db",
    "label": "Database",
    "query": "label_values(mssql_io_stall_seconds_total{job=~\"integrations/mssql\",job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}, db)"
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Connections",
   "type": "timeseries",
   "description": "The number of network connections to each database.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "connections" } },
   "targets": [
    {
     "expr": "mssql_connections{job=~\"integrations/mssql\",job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Batch requests",
   "type": "timeseries",
   "description": "Number of batch requests.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(mssql_batch_requests_total{job=~\"integrations/mssql\",job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Severe errors",
   "type": "timeseries",
   "description": "Number of severe errors that caused connections to be killed.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "errors" } },
   "targets": [
    {
     "expr": "increase(mssql_kill_connection_errors_total{job=~\"integrations/mssql\",job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Deadlocks",
   "type": "timeseries",
   "description": "Rate of deadlocks occurring over time.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "deadlocks" } },
   "targets": [
    {
     "expr": "rate(mssql_deadlocks_total{job=~\"integrations/mssql\",job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 17 } },
  {
   "title": "OS memory usage",
   "type": "timeseries",
   "description": "The amount of physical memory available and used by SQL Server.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "mssql_os_memory{job=~\"integrations/mssql\",job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} - {{ state }}"
    }
   ]
  },
  {
   "title": "Memory manager",
   "type": "timeseries",
   "description": "The committed memory and target committed memory for the SQL Server memory manager. See https://learn.microsoft.com/en-us/sql/relational-databases/performance-monitor/monitor-memory-usage?view=sql-server-ver16#isolating-memory-used-by-",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "mssql_server_total_memory_bytes{job=~\"integrations/mssql\",job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} - total"
    },
    {
     "expr": "mssql_server_target_memory_bytes{job=~\"integrations/mssql\",job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{ instance }} - target"
    }
   ]
  },
  {
   "title": "Committed memory utilization",
   "type": "gauge",
   "description": "The committed memory utilization",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * mssql_server_total_memory_bytes{job=~\"integrations/mssql\",job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"} / clamp_min(mssql_available_commit_memory_bytes{job=~\"integrations/mssql\",job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}, 1)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 34 } },
  {
   "title": "Database write stall duration",
   "type": "timeseries",
   "description": "The current stall (latency) for database writes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(mssql_io_stall_seconds_total{job=~\"integrations/mssql\",job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",db=~\"$db\", operation=\"write\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{ instance }} - {{ db }}"
    }
   ]
  },
  {
   "title": "Database read stall duration",
   "type": "timeseries",
   "description": "The current stall (latency) for database reads.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(mssql_io_stall_seconds_total{job=~\"integrations/mssql\",job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",db=~\"$db\", operation=\"read\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{ instance }} - {{ db }}"
    }
   ]
  },
  {
   "title": "Transaction log expansions",
   "type": "timeseries",
   "description": "Number of times the transaction log has been expanded for a database.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "expansions" } },
   "targets": [
    {
     "expr": "rate(mssql_log_growths_total{job=~\"integrations/mssql\",job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",db=~\"$db\"}[$__rate_interval])",
     "legendFormat": "{{ instance }} - {{ db }}"
    }
   ]
  }
 ]
}