{
 "title": "WSO2 Integration Cluster Metrics",
 "description": "This Dashboard provides an overview of WSO2 integration cluster deployment",
 "tags": [
  "wso2-enterprise-integrator-integration"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(wso2_integration_server_up, job)"
    }
   },
   {
    "name": "wso2_cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(wso2_integration_server_up, wso2_cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "WSO2 Integration Cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "node",
   "targets": [
    {}
   ]
  },
  {
   "title": "Node Count",
   "type": "stat",
   "description": "Displays the number of nodes connected to this cluster",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(wso2_integration_server_up{wso2_cluster=~\"$wso2_cluster\", job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Service Count",
   "type": "stat",
   "description": "Displays the number of services deployed in the cluster.",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(count by(service_name,service_type)(wso2_integration_service_up{wso2_cluster=~\"$wso2_cluster\", job=~\"$job\"}))",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Node List",
   "type": "table",
   "description": "Displays nodes that are deployed in this cluster",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "sum by(instance) (wso2_integration_server_up{wso2_cluster=~\"$wso2_cluster\", job=~\"$job\"}>0)*1000"
    }
   ]
  },
  {
   "title": "Service List",
   "type": "table",
   "description": "Displays services that are deployed in this cluster",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "max by(service_name,service_type) (wso2_integration_service_up{wso2_cluster=~\"$wso2_cluster\", job=~\"$job\"}>0)*1000",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Request Count",
   "type": "stat",
   "description": "Displays the total request count served by the cluster for the selected time period. Request which resulted in errors will be counted here too.",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((max_over_time({__name__ =~\"wso2_integration_.*_request_count_total\",wso2_cluster=~\"$wso2_cluster\", job=~\"$job\"}[$__range]))- (min_over_time({__name__ =~\"wso2_integration_.*_request_count_total\",wso2_cluster=~\"$wso2_cluster\", job=~\"$job\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Error Count",
   "type": "stat",
   "description": "Displays the total error count occurred in this cluster for the selected time period",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum((max_over_time({__name__ =~\"wso2_integration_.*_request_count_error_total\",wso2_cluster=~\"$wso2_cluster\", job=~\"$job\"}[$__range]))- (min_over_time({__name__ =~\"wso2_integration_.*_request_count_error_total\",wso2_cluster=~\"$wso2_cluster\", job=~\"$job\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "description": "Displays the request rate received by cluster during the selected time period. This will also include error requests. ",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate({__name__ =~\"wso2_integration_.*_request_count_total\",wso2_cluster=~\"$wso2_cluster\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "description": "Displays the error rate occurred at this cluster during the selected time period. ",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate({__name__ =~\"wso2_integration_.*_request_count_error_total\", wso2_cluster=~\"$wso2_cluster\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "timeseries",
   "description": "Displays 95th and 50th percentile of response times served by all nodes of this cluster",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate({__name__ =~\"wso2_integration_.*_latency_seconds\", le=~\".+\", wso2_cluster=~\"$wso2_cluster\", job=~\"$job\"}[$__rate_interval])) by (le))",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate({__name__ =~\"wso2_integration_.*_latency_seconds\", le=~\".+\", wso2_cluster=~\"$wso2_cluster\", job=~\"$job\"}[$__rate_interval])) by (le))",
     "legendFormat": "95th Percentile"
    }
   ]
  }
 ]
}