{
 "title": "Nomad jobs",
 "description": "Nomad jobs metrics",
 "tags": [ "nomad-integration" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(nomad_client_uptime, job)"
    }
   },
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "datacenter",
    "label": "DC",
    "query": {
     "query": "label_values(nomad_client_uptime, datacenter)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(nomad_client_uptime{datacenter=~\"$datacenter\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "instance",
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(nomad_client_allocs_cpu_total_percent{job=~\"$job\", instance=~\"$instance\"}) by(exported_job, task)",
     "legendFormat": "{{task}}"
    }
   ]
  },
  {
   "title": "CPU total ticks",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "timeticks" } },
   "targets": [
    {
     "expr": "avg(nomad_client_allocs_cpu_total_ticks{job=~\"$job\", instance=~\"$instance\"}) by (exported_job, task)",
     "legendFormat": "{{task}}"
    }
   ]
  },
  {
   "title": "RSS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(nomad_client_allocs_memory_rss{job=~\"$job\", instance=~\"$instance\"}) by(exported_job, task)",
     "legendFormat": "{{task}}"
    }
   ]
  },
  {
   "title": "Memory cache",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(nomad_client_allocs_memory_cache{job=~\"$job\", instance=~\"$instance\"}) by (exported_job, task)",
     "legendFormat": "{{task}}"
    }
   ]
  }
 ]
}