{
 "title": "Kubernetes / Autoscaling / Karpenter / Performance",
 "description": "A dashboard that monitors Karpenter and focuses on Karpenter performance. It is created using the [kubernetes-autoscaling-mixin](https://github.com/adinhodovic/kubernetes-autoscaling-mixin).",
 "tags": [
  "kubernetes",
  "autoscaling",
  "kubernetes-autoscaling-mixin",
  "karpenter"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(kube_pod_info{job=~\"kube-state-metrics\"}, cluster)"
   },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(karpenter_nodes_allocatable{cluster=\"$cluster\"}, job)"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster State Synced",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  karpenter_cluster_state_synced{\n    cluster=\"$cluster\",\n    job=~\"$job\",\n  }\n) by (job)\n"
    }
   ]
  },
  {
   "title": "Cluster State Node Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  karpenter_cluster_state_node_count{\n    cluster=\"$cluster\",\n    job=~\"$job\",\n  }\n) by (job)\n"
    }
   ]
  },
  {
   "title": "Cloud Provider Errors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(\n  sum(\n    increase(\n      karpenter_cloudprovider_errors_total{\n        cluster=\"$cluster\",\n        job=~\"$job\"\n      }[$__rate_interval]\n    )\n  ) by (job, provider, controller, method)\n)\n",
     "legendFormat": "{{ provider }} - {{ controller }} - {{ method }}"
    }
   ]
  },
  {
   "title": "Node Termination Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(\n  karpenter_nodes_termination_duration_seconds{\n    cluster=\"$cluster\",\n    job=~\"$job\",\n    quantile=\"0.5\"\n  }\n)\n",
     "legendFormat": "P50"
    },
    {
     "expr": "max(\n  karpenter_nodes_termination_duration_seconds{\n    cluster=\"$cluster\",\n    job=~\"$job\",\n    quantile=\"0.95\"\n  }\n)\n",
     "legendFormat": "P95"
    },
    {
     "expr": "max(\n  karpenter_nodes_termination_duration_seconds{\n    cluster=\"$cluster\",\n    job=~\"$job\",\n    quantile=\"0.99\"\n  }\n)\n",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Pods Startup Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(\n  karpenter_pods_startup_duration_seconds{\n    cluster=\"$cluster\",\n    job=~\"$job\",\n    quantile=\"0.5\"\n  }\n)\n",
     "legendFormat": "P50"
    },
    {
     "expr": "max(\n  karpenter_pods_startup_duration_seconds{\n    cluster=\"$cluster\",\n    job=~\"$job\",\n    quantile=\"0.95\"\n  }\n)\n",
     "legendFormat": "P95"
    },
    {
     "expr": "max(\n  karpenter_pods_startup_duration_seconds{\n    cluster=\"$cluster\",\n    job=~\"$job\",\n    quantile=\"0.99\"\n  }\n)\n",
     "legendFormat": "P99"
    }
   ]
  },
  { "title": "Interruption Queue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Interruption Received Messages",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    karpenter_interruption_received_messages_total{\n      cluster=\"$cluster\",\n      job=~\"$job\"\n    }[$__rate_interval]\n  )\n) by (job, message_type)\n",
     "legendFormat": "{{ message_type }}"
    }
   ]
  },
  {
   "title": "Interruption Deleted Messages",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    karpenter_interruption_deleted_messages_total{\n      cluster=\"$cluster\",\n      job=~\"$job\"\n    }[$__rate_interval]\n  )\n) by (job)\n",
     "legendFormat": "Deleted Messages"
    }
   ]
  },
  {
   "title": "Interruption Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50,\n  sum(\n    irate(\n      karpenter_interruption_message_queue_duration_seconds_bucket{\n        cluster=\"$cluster\",\n        job=~\"$job\"\n      }[$__rate_interval]\n    ) > 0\n  ) by (job, le)\n)\n",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95,\n  sum(\n    irate(\n      karpenter_interruption_message_queue_duration_seconds_bucket{\n        cluster=\"$cluster\",\n        job=~\"$job\"\n      }[$__rate_interval]\n    ) > 0\n  ) by (job, le)\n)\n",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99,\n  sum(\n    irate(\n      karpenter_interruption_message_queue_duration_seconds_bucket{\n        cluster=\"$cluster\",\n        job=~\"$job\"\n      }[$__rate_interval]\n    ) > 0\n  ) by (job, le)\n)\n",
     "legendFormat": "P99"
    }
   ]
  },
  { "title": "Work Queue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Work Queue Depth",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  karpenter_workqueue_depth{\n    cluster=\"$cluster\",\n    job=~\"$job\"\n  }\n) by (job)\n",
     "legendFormat": "Queue Depth"
    }
   ]
  },
  {
   "title": "Work Queue In Queue Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50,\n  sum(\n    irate(\n      karpenter_workqueue_queue_duration_seconds_bucket{\n        cluster=\"$cluster\",\n        job=~\"$job\"\n      }[$__rate_interval]\n    ) > 0\n  ) by (job, le)\n)\n",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95,\n  sum(\n    irate(\n      karpenter_workqueue_queue_duration_seconds_bucket{\n        cluster=\"$cluster\",\n        job=~\"$job\"\n      }[$__rate_interval]\n    ) > 0\n  ) by (job, le)\n)\n",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99,\n  sum(\n    irate(\n      karpenter_workqueue_queue_duration_seconds_bucket{\n        cluster=\"$cluster\",\n        job=~\"$job\"\n      }[$__rate_interval]\n    ) > 0\n  ) by (job, le)\n)\n",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Work Queue Work Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50,\n  sum(\n    irate(\n      karpenter_workqueue_work_duration_seconds_bucket{\n        cluster=\"$cluster\",\n        job=~\"$job\"\n      }[$__rate_interval]\n    ) > 0\n  ) by (job, le)\n)\n",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95,\n  sum(\n    irate(\n      karpenter_workqueue_work_duration_seconds_bucket{\n        cluster=\"$cluster\",\n        job=~\"$job\"\n      }[$__rate_interval]\n    ) > 0\n  ) by (job, le)\n)\n",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99,\n  sum(\n    irate(\n      karpenter_workqueue_work_duration_seconds_bucket{\n        cluster=\"$cluster\",\n        job=~\"$job\"\n      }[$__rate_interval]\n    ) > 0\n  ) by (job, le)\n)\n",
     "legendFormat": "P99"
    }
   ]
  },
  { "title": "Controller", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Controller Reconcile",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    controller_runtime_reconcile_total{\n      cluster=\"$cluster\",\n      job=~\"$job\"\n    }[$__rate_interval]\n  )\n) by (job, controller) > 0\n",
     "legendFormat": "{{ controller }}"
    }
   ]
  }
 ]
}