{
 "title": "Kubernetes / Autoscaling / Karpenter / Overview",
 "description": "A dashboard that monitors Karpenter and focuses on giving a overview for Karpenter. It is created using the [kubernetes-autoscaling-mixin](https://github.com/adinhodovic/kubernetes-autoscaling-mixin).",
 "tags": [
  "kubernetes",
  "autoscaling",
  "kubernetes-autoscaling-mixin",
  "karpenter"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(kube_pod_info{job=~\"kube-state-metrics\"}, cluster)"
   },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(karpenter_nodes_allocatable{cluster=\"$cluster\"}, job)"
   },
   {
    "name": "region",
    "label": "Region",
    "query": "label_values(karpenter_nodes_allocatable{cluster=\"$cluster\", job=~\"$job\"}, region)"
   },
   {
    "name": "zone",
    "label": "Zone",
    "query": "label_values(karpenter_nodes_allocatable{cluster=\"$cluster\", job=~\"$job\", region=~\"$region\"}, zone)"
   },
   {
    "name": "arch",
    "label": "Architecture",
    "query": "label_values(karpenter_nodes_allocatable{cluster=\"$cluster\", job=~\"$job\", region=~\"$region\", zone=~\"$zone\"}, arch)"
   },
   {
    "name": "os",
    "label": "Operating System",
    "query": "label_values(karpenter_nodes_allocatable{cluster=\"$cluster\", job=~\"$job\", region=~\"$region\", zone=~\"$zone\", arch=~\"$arch\"}, os)"
   },
   {
    "name": "instance_type",
    "label": "Instance Type",
    "query": "label_values(karpenter_nodes_allocatable{cluster=\"$cluster\", job=~\"$job\", region=~\"$region\", zone=~\"$zone\", arch=~\"$arch\", os=~\"$os\"}, instance_type)"
   },
   {
    "name": "capacity_type",
    "label": "Capacity Type",
    "query": "label_values(karpenter_nodes_allocatable{cluster=\"$cluster\", job=~\"$job\", region=~\"$region\", zone=~\"$zone\", arch=~\"$arch\", os=~\"$os\", instance_type=~\"$instance_type\"}, capacity_type)"
   },
   {
    "name": "nodepool",
    "label": "Node Pool",
    "query": "label_values(karpenter_nodes_allocatable{cluster=\"$cluster\", job=~\"$job\", region=~\"$region\", zone=~\"$zone\", arch=~\"$arch\", os=~\"$os\", instance_type=~\"$instance_type\", capacity_type=~\"$capacity_type\"}, nodepool)"
   }
  ]
 },
 "panels": [
  { "title": "Cluster Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  karpenter_nodepools_usage{\n    cluster=\"$cluster\",\n    job=~\"$job\",\n    nodepool=~\"$nodepool\",\n    resource_type=\"cpu\"\n  }\n)\n",
     "legendFormat": "Allocatable"
    },
    {
     "expr": "sum(\n  karpenter_nodes_total_pod_requests{\n    cluster=\"$cluster\",\n    job=~\"$job\",\n    resource_type=\"cpu\",\n    region=~\"$region\",\n    zone=~\"$zone\",\n    arch=~\"$arch\",\n    os=~\"$os\",\n    instance_type=~\"$instance_type\",\n    capacity_type=~\"$capacity_type\",\n    nodepool=~\"$nodepool\"\n  }\n) +\nsum(\n  karpenter_nodes_total_daemon_requests{\n    cluster=\"$cluster\",\n    job=~\"$job\",\n    resource_type=\"cpu\",\n    region=~\"$region\",\n    zone=~\"$zone\",\n    arch=~\"$arch\",\n    os=~\"$os\",\n    instance_type=~\"$instance_type\",\n    capacity_type=~\"$capacity_type\",\n    nodepool=~\"$nodepool\"\n  }\n)\n",
     "legendFormat": "Requested"
    }
   ]
  },
  {
   "title": "Cluster Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(\n  karpenter_nodepools_usage{\n    cluster=\"$cluster\",\n    job=~\"$job\",\n    nodepool=~\"$nodepool\",\n    resource_type=\"memory\"\n  }\n)\n",
     "legendFormat": "Allocatable"
    },
    {
     "expr": "sum(\n  karpenter_nodes_total_pod_requests{\n    cluster=\"$cluster\",\n    job=~\"$job\",\n    resource_type=\"memory\",\n    region=~\"$region\",\n    zone=~\"$zone\",\n    arch=~\"$arch\",\n    os=~\"$os\",\n    instance_type=~\"$instance_type\",\n    capacity_type=~\"$capacity_type\",\n    nodepool=~\"$nodepool\"\n  }\n) +\nsum(\n  karpenter_nodes_total_daemon_requests{\n    cluster=\"$cluster\",\n    job=~\"$job\",\n    resource_type=\"memory\",\n    region=~\"$region\",\n    zone=~\"$zone\",\n    arch=~\"$arch\",\n    os=~\"$os\",\n    instance_type=~\"$instance_type\",\n    capacity_type=~\"$capacity_type\",\n    nodepool=~\"$nodepool\"\n  }\n)\n",
     "legendFormat": "Requested"
    }
   ]
  },
  { "title": "Node Pool Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Node Pools",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  count(\n    karpenter_nodepools_allowed_disruptions{\n      cluster=\"$cluster\",\n      job=~\"$job\",\n    }\n  ) by (nodepool)\n)\n"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  count(\n    karpenter_nodes_allocatable{\n      cluster=\"$cluster\",\n      job=~\"$job\",\n      region=~\"$region\",\n      zone=~\"$zone\",\n      arch=~\"$arch\",\n      os=~\"$os\",\n      instance_type=~\"$instance_type\",\n      capacity_type=~\"$capacity_type\",\n      nodepool=~\"$nodepool\"\n    }\n  ) by (node_name)\n)\n"
    }
   ]
  },
  {
   "title": "Node Pool CPU Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  karpenter_nodepools_usage{\n    cluster=\"$cluster\",\n    job=~\"$job\",\n    nodepool=~\"$nodepool\",\n    resource_type=\"cpu\"\n  }\n)\n"
    }
   ]
  },
  {
   "title": "Node Pool Memory Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  karpenter_nodepools_usage{\n    cluster=\"$cluster\",\n    job=~\"$job\",\n    nodepool=~\"$nodepool\",\n    resource_type=\"memory\"\n  }\n)\n"
    }
   ]
  },
  {
   "title": "Node Pool CPU Limits",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  karpenter_nodepools_limit{\n    cluster=\"$cluster\",\n    job=~\"$job\",\n    nodepool=~\"$nodepool\",\n    resource_type=\"cpu\"\n  }\n)\n"
    }
   ]
  },
  {
   "title": "Node Pool Memory Limits",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  karpenter_nodepools_limit{\n    cluster=\"$cluster\",\n    job=~\"$job\",\n    nodepool=~\"$nodepool\",\n    resource_type=\"memory\"\n  }\n)\n"
    }
   ]
  },
  {
   "title": "Node Pool Usage % of Limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(\n  karpenter_nodepools_usage{\n    cluster=\"$cluster\",\n    job=~\"$job\",\n    nodepool=~\"$nodepool\",\n  }\n) by (nodepool, resource_type)\n/\nsum(\n  karpenter_nodepools_limit{\n    cluster=\"$cluster\",\n    job=~\"$job\",\n    nodepool=~\"$nodepool\",\n  }\n) by (nodepool, resource_type) * 100\n",
     "legendFormat": "{{ nodepool }} / {{ resource_type }}"
    }
   ]
  },
  {
   "title": "Nodes by Node Pool",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "count by (nodepool) (\n  count by (node_name, nodepool) (\n    karpenter_nodes_allocatable{\n      cluster=\"$cluster\",\n      job=~\"$job\",\n      region=~\"$region\",\n      zone=~\"$zone\",\n      arch=~\"$arch\",\n      os=~\"$os\",\n      instance_type=~\"$instance_type\",\n      capacity_type=~\"$capacity_type\",\n      nodepool=~\"$nodepool\"\n    }\n  )\n)\n",
     "legendFormat": "{{ nodepool }}"
    }
   ]
  },
  {
   "title": "Nodes by Instance Type",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 18 },
   "targets": [
    {
     "expr": "count by (instance_type) (\n  count by (node_name, instance_type) (\n    karpenter_nodes_allocatable{\n      cluster=\"$cluster\",\n      job=~\"$job\",\n      region=~\"$region\",\n      zone=~\"$zone\",\n      arch=~\"$arch\",\n      os=~\"$os\",\n      instance_type=~\"$instance_type\",\n      capacity_type=~\"$capacity_type\",\n      nodepool=~\"$nodepool\"\n    }\n  )\n)\n",
     "legendFormat": "{{ instance_type }}"
    }
   ]
  },
  {
   "title": "Nodes by Capacity Type",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "expr": "count by (capacity_type) (\n  count by (node_name, capacity_type) (\n    karpenter_nodes_allocatable{\n      cluster=\"$cluster\",\n      job=~\"$job\",\n      region=~\"$region\",\n      zone=~\"$zone\",\n      arch=~\"$arch\",\n      os=~\"$os\",\n      instance_type=~\"$instance_type\",\n      capacity_type=~\"$capacity_type\",\n      nodepool=~\"$nodepool\"\n    }\n  )\n)\n",
     "legendFormat": "{{ capacity_type }}"
    }
   ]
  },
  {
   "title": "Nodes by Region",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "count by (region) (\n  count by (node_name, region) (\n    karpenter_nodes_allocatable{\n      cluster=\"$cluster\",\n      job=~\"$job\",\n      region=~\"$region\",\n      zone=~\"$zone\",\n      arch=~\"$arch\",\n      os=~\"$os\",\n      instance_type=~\"$instance_type\",\n      capacity_type=~\"$capacity_type\",\n      nodepool=~\"$nodepool\"\n    }\n  )\n)\n",
     "legendFormat": "{{ region }}"
    }
   ]
  },
  {
   "title": "Nodes by Zone",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 23 },
   "targets": [
    {
     "expr": "count by (zone) (\n  count by (node_name, zone) (\n    karpenter_nodes_allocatable{\n      cluster=\"$cluster\",\n      job=~\"$job\",\n      nodepool=~\"$nodepool\",\n      zone=~\"$zone\",\n      arch=~\"$arch\",\n      os=~\"$os\",\n      instance_type=~\"$instance_type\",\n      capacity_type=~\"$capacity_type\",\n      nodepool=~\"$nodepool\"\n    }\n  )\n)\n",
     "legendFormat": "{{ zone }}"
    }
   ]
  },
  {
   "title": "Nodes by Arch",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "count by (arch) (\n  count by (node_name, arch) (\n    karpenter_nodes_allocatable{\n      cluster=\"$cluster\",\n      job=~\"$job\",\n      nodepool=~\"$nodepool\",\n      zone=~\"$zone\",\n      arch=~\"$arch\",\n      os=~\"$os\",\n      instance_type=~\"$instance_type\",\n      capacity_type=~\"$capacity_type\",\n      nodepool=~\"$nodepool\"\n    }\n  )\n)\n",
     "legendFormat": "{{ arch }}"
    }
   ]
  },
  {
   "title": "Nodes by OS",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 23 },
   "targets": [
    {
     "expr": "count by (os) (\n  count by (node_name, os) (\n    karpenter_nodes_allocatable{\n      cluster=\"$cluster\",\n      job=~\"$job\",\n      region=~\"$region\",\n      zone=~\"$zone\",\n      arch=~\"$arch\",\n      os=~\"$os\",\n      instance_type=~\"$instance_type\",\n      capacity_type=~\"$capacity_type\",\n      nodepool=~\"$nodepool\"\n    }\n  )\n)\n",
     "legendFormat": "{{ os }}"
    }
   ]
  },
  { "title": "Pod Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Pod CPU Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  karpenter_nodes_total_pod_requests{\n    cluster=\"$cluster\",\n    job=~\"$job\",\n    resource_type=\"cpu\",\n    region=~\"$region\",\n    zone=~\"$zone\",\n    arch=~\"$arch\",\n    os=~\"$os\",\n    instance_type=~\"$instance_type\",\n    capacity_type=~\"$capacity_type\",\n    nodepool=~\"$nodepool\"\n  }\n) +\nsum(\n  karpenter_nodes_total_daemon_requests{\n    cluster=\"$cluster\",\n    job=~\"$job\",\n    resource_type=\"cpu\",\n    region=~\"$region\",\n    zone=~\"$zone\",\n    arch=~\"$arch\",\n    os=~\"$os\",\n    instance_type=~\"$instance_type\",\n    capacity_type=~\"$capacity_type\",\n    nodepool=~\"$nodepool\"\n  }\n)\n"
    }
   ]
  },
  {
   "title": "Pod Memory Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  karpenter_nodes_total_pod_requests{\n    cluster=\"$cluster\",\n    job=~\"$job\",\n    resource_type=\"memory\",\n    region=~\"$region\",\n    zone=~\"$zone\",\n    arch=~\"$arch\",\n    os=~\"$os\",\n    instance_type=~\"$instance_type\",\n    capacity_type=~\"$capacity_type\",\n    nodepool=~\"$nodepool\"\n  }\n) +\nsum(\n  karpenter_nodes_total_daemon_requests{\n    cluster=\"$cluster\",\n    job=~\"$job\",\n    resource_type=\"memory\",\n    region=~\"$region\",\n    zone=~\"$zone\",\n    arch=~\"$arch\",\n    os=~\"$os\",\n    instance_type=~\"$instance_type\",\n    capacity_type=~\"$capacity_type\",\n    nodepool=~\"$nodepool\"\n  }\n)\n"
    }
   ]
  },
  {
   "title": "Pod CPU Limits",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  karpenter_nodes_total_pod_limits{\n    cluster=\"$cluster\",\n    job=~\"$job\",\n    resource_type=\"cpu\",\n    region=~\"$region\",\n    zone=~\"$zone\",\n    arch=~\"$arch\",\n    os=~\"$os\",\n    instance_type=~\"$instance_type\",\n    capacity_type=~\"$capacity_type\",\n    nodepool=~\"$nodepool\"\n  }\n) +\nsum(\n  karpenter_nodes_total_daemon_limits{\n    cluster=\"$cluster\",\n    job=~\"$job\",\n    resource_type=\"cpu\",\n    region=~\"$region\",\n    zone=~\"$zone\",\n    arch=~\"$arch\",\n    os=~\"$os\",\n    instance_type=~\"$instance_type\",\n    capacity_type=~\"$capacity_type\",\n    nodepool=~\"$nodepool\"\n  }\n)\n"
    }
   ]
  },
  {
   "title": "Pod Memory Limits",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  karpenter_nodes_total_pod_limits{\n    cluster=\"$cluster\",\n    job=~\"$job\",\n    resource_type=\"memory\",\n    region=~\"$region\",\n    zone=~\"$zone\",\n    arch=~\"$arch\",\n    os=~\"$os\",\n    instance_type=~\"$instance_type\",\n    capacity_type=~\"$capacity_type\",\n    nodepool=~\"$nodepool\"\n  }\n) +\nsum(\n  karpenter_nodes_total_daemon_limits{\n    cluster=\"$cluster\",\n    job=~\"$job\",\n    resource_type=\"memory\",\n    region=~\"$region\",\n    zone=~\"$zone\",\n    arch=~\"$arch\",\n    os=~\"$os\",\n    instance_type=~\"$instance_type\",\n    capacity_type=~\"$capacity_type\",\n    nodepool=~\"$nodepool\"\n  }\n)\n"
    }
   ]
  },
  {
   "title": "Pods by Node Pool",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum(\n    karpenter_pods_state{\n      cluster=\"$cluster\",\n      job=~\"$job\",\n      nodepool=~\"$nodepool\"\n    }\n) by (nodepool)\n",
     "legendFormat": "{{ nodepool }}"
    }
   ]
  },
  {
   "title": "Pods by Instance Type",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 32 },
   "targets": [
    {
     "expr": "sum(\n    karpenter_pods_state{\n      cluster=\"$cluster\",\n      job=~\"$job\",\n      nodepool=~\"$nodepool\"\n    }\n) by (instance_type)\n",
     "legendFormat": "{{ instance_type }}"
    }
   ]
  },
  {
   "title": "Pods by Capacity Type",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 32 },
   "targets": [
    {
     "expr": "sum(\n    karpenter_pods_state{\n      cluster=\"$cluster\",\n      job=~\"$job\",\n      nodepool=~\"$nodepool\"\n    }\n) by (capacity_type)\n",
     "legendFormat": "{{ capacity_type }}"
    }
   ]
  },
  { "title": "Node Pools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Node Pools",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  karpenter_nodepools_usage{\n    cluster=\"$cluster\",\n    job=~\"$job\",\n    nodepool=~\"$nodepool\",\n    resource_type=\"cpu\"\n  }\n) by (job, namespace, nodepool)\n"
    },
    {
     "expr": "sum(\n  karpenter_nodes_allocatable{\n    cluster=\"$cluster\",\n    job=~\"$job\",\n    nodepool=~\"$nodepool\",\n    resource_type=\"cpu\"\n  }\n) by (job, namespace, nodepool)\n"
    },
    {
     "expr": "sum(\n  karpenter_nodepools_limit{\n    cluster=\"$cluster\",\n    job=~\"$job\",\n    nodepool=~\"$nodepool\",\n    resource_type=\"cpu\"\n  }\n) by (job, namespace, nodepool)\n"
    },
    {
     "expr": "sum(\n  karpenter_nodepools_usage{\n    cluster=\"$cluster\",\n    job=~\"$job\",\n    nodepool=~\"$nodepool\",\n    resource_type=\"memory\"\n  }\n) by (job, namespace, nodepool)\n"
    },
    {
     "expr": "sum(\n  karpenter_nodes_allocatable{\n    cluster=\"$cluster\",\n    job=~\"$job\",\n    nodepool=~\"$nodepool\",\n    resource_type=\"memory\"\n  }\n) by (job, namespace, nodepool)\n"
    },
    {
     "expr": "sum(\n  karpenter_nodepools_limit{\n    cluster=\"$cluster\",\n    job=~\"$job\",\n    nodepool=~\"$nodepool\",\n    resource_type=\"memory\"\n  }\n) by (job, namespace, nodepool)\n"
    },
    {
     "expr": "sum(\n  karpenter_nodepools_usage{\n    cluster=\"$cluster\",\n    job=~\"$job\",\n    nodepool=~\"$nodepool\",\n    resource_type=\"nodes\"\n  }\n) by (job, namespace, nodepool)\n"
    },
    {
     "expr": "sum(\n  karpenter_nodepools_limit{\n    cluster=\"$cluster\",\n    job=~\"$job\",\n    nodepool=~\"$nodepool\",\n    resource_type=\"nodes\"\n  }\n) by (job, namespace, nodepool)\n"
    },
    {
     "expr": "sum(\n  karpenter_nodepools_usage{\n    cluster=\"$cluster\",\n    job=~\"$job\",\n    nodepool=~\"$nodepool\",\n    resource_type=\"pods\"\n  }\n) by (job, namespace, nodepool)\n"
    },
    {
     "expr": "sum(\n  karpenter_nodepools_limit{\n    cluster=\"$cluster\",\n    job=~\"$job\",\n    nodepool=~\"$nodepool\",\n    resource_type=\"pods\"\n  }\n) by (job, namespace, nodepool)\n"
    },
    {
     "expr": "sum(\n  karpenter_nodepools_usage{\n    cluster=\"$cluster\",\n    job=~\"$job\",\n    nodepool=~\"$nodepool\",\n    resource_type=\"ephemeral_storage\"\n  }\n) by (job, namespace, nodepool)\n"
    },
    {
     "expr": "sum(\n  karpenter_nodepools_limit{\n    cluster=\"$cluster\",\n    job=~\"$job\",\n    nodepool=~\"$nodepool\",\n    resource_type=\"ephemeral_storage\"\n  }\n) by (job, namespace, nodepool)\n"
    }
   ]
  },
  { "title": "Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Nodes",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(\n  (\n    sum(\n      karpenter_nodes_total_pod_requests{\n        cluster=\"$cluster\",\n        job=~\"$job\",\n        resource_type=\"cpu\",\n        region=~\"$region\",\n        zone=~\"$zone\",\n        arch=~\"$arch\",\n        os=~\"$os\",\n        instance_type=~\"$instance_type\",\n        capacity_type=~\"$capacity_type\",\n        nodepool=~\"$nodepool\"\n      }\n    ) by (node_name, nodepool, instance_type, instance_memory, instance_cpu, instance_network_bandwidth, region, zone, os, capacity_type, arch)\n    +\n    sum(\n      karpenter_nodes_total_daemon_requests{\n        cluster=\"$cluster\",\n        job=~\"$job\",\n        resource_type=\"cpu\",\n        region=~\"$region\",\n        zone=~\"$zone\",\n        arch=~\"$arch\",\n        os=~\"$os\",\n        instance_type=~\"$instance_type\",\n        capacity_type=~\"$capacity_type\",\n        nodepool=~\"$nodepool\"\n      }\n    ) by (node_name, nodepool, instance_type, instance_memory, instance_cpu, instance_network_bandwidth, region, zone, os, capacity_type, arch)\n  ) /\n  sum(\n    karpenter_nodes_allocatable{\n      cluster=\"$cluster\",\n      job=~\"$job\",\n      resource_type=\"cpu\",\n      region=~\"$region\",\n      zone=~\"$zone\",\n      arch=~\"$arch\",\n      os=~\"$os\",\n      instance_type=~\"$instance_type\",\n      capacity_type=~\"$capacity_type\",\n      nodepool=~\"$nodepool\"\n    }\n  ) by (node_name, nodepool, instance_type, instance_memory, instance_cpu, instance_network_bandwidth, region, zone, os, capacity_type, arch)\n) * 100\n"
    },
    {
     "expr": "(\n  (\n    sum(\n      karpenter_nodes_total_pod_requests{\n        cluster=\"$cluster\",\n        job=~\"$job\",\n        resource_type=\"memory\",\n        region=~\"$region\",\n        zone=~\"$zone\",\n        arch=~\"$arch\",\n        os=~\"$os\",\n        instance_type=~\"$instance_type\",\n        capacity_type=~\"$capacity_type\",\n        nodepool=~\"$nodepool\"\n      }\n    ) by (node_name, nodepool, instance_type, instance_memory, instance_memory, instance_network_bandwidth, region, zone, os, capacity_type, arch)\n    +\n    sum(\n      karpenter_nodes_total_daemon_requests{\n        cluster=\"$cluster\",\n        job=~\"$job\",\n        resource_type=\"memory\",\n        region=~\"$region\",\n        zone=~\"$zone\",\n        arch=~\"$arch\",\n        os=~\"$os\",\n        instance_type=~\"$instance_type\",\n        capacity_type=~\"$capacity_type\",\n        nodepool=~\"$nodepool\"\n      }\n    ) by (node_name, nodepool, instance_type, instance_memory, instance_memory, instance_network_bandwidth, region, zone, os, capacity_type, arch)\n  ) /\n  sum(\n    karpenter_nodes_allocatable{\n      cluster=\"$cluster\",\n      job=~\"$job\",\n      resource_type=\"memory\",\n      region=~\"$region\",\n      zone=~\"$zone\",\n      arch=~\"$arch\",\n      os=~\"$os\",\n      instance_type=~\"$instance_type\",\n      capacity_type=~\"$capacity_type\",\n      nodepool=~\"$nodepool\"\n    }\n  ) by (node_name, nodepool, instance_type, instance_memory, instance_memory, instance_network_bandwidth, region, zone, os, capacity_type, arch)\n) * 100\n"
    }
   ]
  }
 ]
}