{
 "title": "Kubernetes / Autoscaling / Pod Disruption Budget",
 "description": "A dashboard that monitors Kubernetes and focuses on giving a overview for pod disruption budgets. It is created using the [Kubernetes / Autoscaling-mixin](https://github.com/adinhodovic/kubernetes-autoscaling-mixin).",
 "tags": [
  "kubernetes",
  "autoscaling",
  "kubernetes-autoscaling-mixin",
  "kubernetes-core"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(kube_horizontalpodautoscaler_metadata_generation{}, job)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_poddisruptionbudget_status_current_healthy{job=~\"$job\"}, namespace)"
   },
   {
    "name": "pdb",
    "label": "Pod Disruption Budget",
    "query": "label_values(kube_poddisruptionbudget_status_current_healthy{job=~\"$job\", namespace=~\"$namespace\"}, poddisruptionbudget)"
   }
  ]
 },
 "panels": [
  { "title": "$namespace Namespace Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Summary",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(\n  sum(\n    kube_poddisruptionbudget_status_pod_disruptions_allowed{\n      job=~\"$job\",\n      namespace=~\"$namespace\"\n    }\n  ) by (job, namespace, poddisruptionbudget)\n)\n"
    },
    {
     "expr": "round(\n  sum(\n    kube_poddisruptionbudget_status_desired_healthy{\n      job=~\"$job\",\n      namespace=~\"$namespace\"\n    }\n  ) by (job, namespace, poddisruptionbudget)\n)\n"
    },
    {
     "expr": "round(\n  sum(\n    kube_poddisruptionbudget_status_current_healthy{\n      job=~\"$job\",\n      namespace=~\"$namespace\"\n    }\n  ) by (job, namespace, poddisruptionbudget)\n)\n"
    },
    {
     "expr": "round(\n  sum(\n    kube_poddisruptionbudget_status_expected_pods{\n      job=~\"$job\",\n      namespace=~\"$namespace\"\n    }\n  ) by (job, namespace, poddisruptionbudget)\n)\n"
    }
   ]
  },
  { "title": "$pdb Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Disruptions Allowed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(\n  sum(\n    kube_poddisruptionbudget_status_pod_disruptions_allowed{\n      job=~\"$job\",\n      namespace=~\"$namespace\",\n      poddisruptionbudget=~\"$pdb\"\n    }\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Desired Healthy",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(\n  sum(\n    kube_poddisruptionbudget_status_desired_healthy{\n      job=~\"$job\",\n      namespace=~\"$namespace\",\n      poddisruptionbudget=~\"$pdb\"\n    }\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Currently Healthy",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(\n  sum(\n    kube_poddisruptionbudget_status_current_healthy{\n      job=~\"$job\",\n      namespace=~\"$namespace\",\n      poddisruptionbudget=~\"$pdb\"\n    }\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Expected Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(\n  sum(\n    kube_poddisruptionbudget_status_expected_pods{\n      job=~\"$job\",\n      namespace=~\"$namespace\",\n      poddisruptionbudget=~\"$pdb\"\n    }\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(\n  sum(\n    kube_poddisruptionbudget_status_pod_disruptions_allowed{\n      job=~\"$job\",\n      namespace=~\"$namespace\",\n      poddisruptionbudget=~\"$pdb\"\n    }\n  )\n)\n",
     "legendFormat": "Disruptions Allowed"
    },
    {
     "expr": "round(\n  sum(\n    kube_poddisruptionbudget_status_desired_healthy{\n      job=~\"$job\",\n      namespace=~\"$namespace\",\n      poddisruptionbudget=~\"$pdb\"\n    }\n  )\n)\n",
     "legendFormat": "Desired Healthy"
    },
    {
     "expr": "round(\n  sum(\n    kube_poddisruptionbudget_status_current_healthy{\n      job=~\"$job\",\n      namespace=~\"$namespace\",\n      poddisruptionbudget=~\"$pdb\"\n    }\n  )\n)\n",
     "legendFormat": "Currently Healthy"
    },
    {
     "expr": "round(\n  sum(\n    kube_poddisruptionbudget_status_expected_pods{\n      job=~\"$job\",\n      namespace=~\"$namespace\",\n      poddisruptionbudget=~\"$pdb\"\n    }\n  )\n)\n",
     "legendFormat": "Expected Pods"
    }
   ]
  }
 ]
}