{
 "title": "Kubernetes / Autoscaling / Cluster Autoscaler",
 "description": "A dashboard that monitors Kubernetes and focuses on giving a overview for cluster autoscaler. It is created using the [kubernetes-autoscaling-mixin](https://github.com/adinhodovic/kubernetes-autoscaling-mixin).",
 "tags": [
  "kubernetes",
  "autoscaling",
  "kubernetes-autoscaling-mixin",
  "cluster-autoscaler"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(kube_pod_info{job=~\"kube-state-metrics\"}, cluster)"
   },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(cluster_autoscaler_last_activity{cluster=\"$cluster\"}, job)"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(\n  sum(\n    cluster_autoscaler_nodes_count{\n      cluster=\"$cluster\",\n      job=~\"$job\"\n    }\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Max Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(\n  sum(\n    cluster_autoscaler_max_nodes_count{\n      cluster=\"$cluster\",\n      job=~\"$job\"\n    }\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Node Groups",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(\n  sum(\n    cluster_autoscaler_node_groups_count{\n      cluster=\"$cluster\",\n      job=~\"$job\"\n    }\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Healthy Nodes",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(\n  sum(\n    cluster_autoscaler_nodes_count{\n      cluster=\"$cluster\",\n      job=~\"$job\",\n      state=\"ready\"\n    }\n  ) /\n  sum(\n    cluster_autoscaler_nodes_count{\n      cluster=\"$cluster\",\n      job=~\"$job\"\n    }\n  ) * 100\n)\n"
    }
   ]
  },
  {
   "title": "Safe To Scale",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(\n  sum(\n    cluster_autoscaler_cluster_safe_to_autoscale{\n      cluster=\"$cluster\",\n      job=~\"$job\"\n    }\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Unscheduled Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(\n  sum(\n    cluster_autoscaler_unschedulable_pods_count{\n      cluster=\"$cluster\",\n      job=~\"$job\"\n    }\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Last Scale Down",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - sum(\n  cluster_autoscaler_last_activity{\n    cluster=\"$cluster\",\n    job=~\"$job\",\n    activity=\"scaleDown\"\n  }\n)\n"
    }
   ]
  },
  {
   "title": "Last Scale Up",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - sum(\n  cluster_autoscaler_last_activity{\n    cluster=\"$cluster\",\n    job=~\"$job\",\n    activity=\"scaleUp\"\n  }\n)\n"
    }
   ]
  },
  {
   "title": "Pod Activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(\n  sum(\n    increase(\n      cluster_autoscaler_unschedulable_pods_count{\n        cluster=\"$cluster\",\n        job=~\"$job\"\n      }[2m]\n    )\n  ) by (type)\n)\n",
     "legendFormat": "{{ type }}"
    },
    {
     "expr": "round(\n  sum(\n    increase(\n      cluster_autoscaler_evicted_pods_total{\n        cluster=\"$cluster\",\n        job=~\"$job\"\n      }[2m]\n    )\n  )\n)\n",
     "legendFormat": "Evicted Pods"
    }
   ]
  },
  {
   "title": "Node Activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(\n  sum(\n    cluster_autoscaler_nodes_count{\n      cluster=\"$cluster\",\n      job=~\"$job\"\n    }\n  ) by (state)\n)\n",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "Autoscaling Activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(\n  sum(\n    cluster_autoscaler_nodes_count{\n      cluster=\"$cluster\",\n      job=~\"$job\"\n    }\n  )\n)\n",
     "legendFormat": "Total Nodes"
    },
    {
     "expr": "round(\n  sum(\n    cluster_autoscaler_unneeded_nodes_count{\n      cluster=\"$cluster\",\n      job=~\"$job\"\n    }\n  )\n)\n",
     "legendFormat": "Unneeded Nodes"
    },
    {
     "expr": "round(\n  sum(\n    increase(\n      cluster_autoscaler_scaled_up_nodes_total{\n        cluster=\"$cluster\",\n        job=~\"$job\"\n      }[2m]\n    )\n  )\n)\n",
     "legendFormat": "Scaled Up Nodes"
    },
    {
     "expr": "round(\n  sum(\n    increase(\n      cluster_autoscaler_scaled_down_nodes_total{\n        cluster=\"$cluster\",\n        job=~\"$job\"\n      }[2m]\n    )\n  )\n)\n",
     "legendFormat": "Scaled Down Nodes"
    }
   ]
  }
 ]
}