groups:
- name: GrafanaAlerts
  rules:
  - alert: GrafanaRequestsFailing
    annotations:
      message: '{{ $labels.namespace }}/{{ $labels.job }}/{{ $labels.handler }} is
        experiencing {{ $value | humanize }}% errors'
    expr: |
      100 * sum without (status_code) (namespace_job_handler_statuscode:grafana_http_request_duration_seconds_count:rate5m{handler!~"/api/datasources/proxy/:id.*|/api/ds/query|/api/tsdb/query", status_code=~"5.."})
      /
      sum without (status_code) (namespace_job_handler_statuscode:grafana_http_request_duration_seconds_count:rate5m{handler!~"/api/datasources/proxy/:id.*|/api/ds/query|/api/tsdb/query"})
      > 50
    for: 5m
    labels:
      severity: warning
