{
 "title": "WSO2 Streaming Integrator Overall Statistics",
 "tags": [
  "wso2",
  "prometheus",
  "siddhi",
  "streaming-integrator"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(siddhi_stream_throughput_total,job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(siddhi_stream_throughput_total{job=~\"$job\"},instance)"
    }
   },
   {
    "name": "app",
    "label": "Appname",
    "query": {
     "query": "label_values(siddhi_stream_throughput_total{job=~\"$job\",instance=~\"$instance\"}, app)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Inputs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(siddhi_total_reads{job=~\"$job\",instance=~\"$instance\",app=~\"$app\",type=~\"cdc|file|kafka|http\"}) "
    }
   ]
  },
  {
   "title": "Overview Statistics",
   "type": "table",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "sum(siddhi_total_reads{job=~\"$job\",instance=~\"$instance\",app=~\"$app\",type=~\"cdc|file|kafka|http\"}) by (app)"
    },
    {
     "expr": "sum by(app) (rate(siddhi_total_reads{job=~\"$job\",instance=~\"$instance\",app=~\"$app\",type=~\"cdc|file|kafka|http\"}[$__rate_interval]))"
    },
    {
     "expr": "sum(siddhi_total_writes{job=~\"$job\",instance=~\"$instance\",app=~\"$app\",type=~\"rdbms|file|kafka|http\"}) by (app)"
    },
    {
     "expr": "sum (rate(siddhi_total_writes{job=~\"$job\",instance=~\"$instance\",app=~\"$app\",type=~\"rdbms|file|kafka|http\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Total Outputs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(siddhi_total_writes{job=~\"$job\",instance=~\"$instance\",app=~\"$app\",type=~\"rdbms|file|kafka|http\"})"
    }
   ]
  },
  {
   "title": "(Consume/Publish)/Sec",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(siddhi_total_reads{job=~\"$job\",instance=~\"$instance\",app=~\"$app\",type=~\"cdc|file|kafka|http\"}[$__rate_interval]))",
     "legendFormat": "Inputs"
    },
    {
     "expr": "sum(rate(siddhi_total_writes{job=~\"$job\",instance=~\"$instance\",app=~\"$app\",type=~\"file|rdbms|kafka|http\"}[$__rate_interval]))",
     "legendFormat": "Outputs"
    }
   ]
  }
 ]
}