{
 "title": "Django / Overview",
 "description": "A dashboard that monitors Django which focuses on giving a overview for the system (requests, db, cache). The dashboards were generated using [Django-mixin](https://github.com/adinhodovic/django-mixin). Open issues and create feature requests in the repository.",
 "tags": [
  "django",
  "django-mixin"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(django_http_responses_total_by_status_view_method_total{}, cluster)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(django_http_responses_total_by_status_view_method_total{cluster=\"$cluster\"}, namespace)"
   },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(django_http_responses_total_by_status_view_method_total{cluster=\"$cluster\", namespace=\"$namespace\"}, job)"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request Volume",
   "type": "stat",
   "description": "The number of requests received per second.",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "round(\n  sum(\n    rate(\n      django_http_requests_total_by_view_transport_method_total{\n        cluster=\"$cluster\",\nnamespace=\"$namespace\",\njob=~\"$job\"\n,\nview!~\"<unnamed view>|health_check.views.HealthCheckView|prometheus-django-metrics\"\n\n      }[$__rate_interval]\n    )\n  ), 0.001\n)\n"
    }
   ]
  },
  {
   "title": "Database Ops",
   "type": "stat",
   "description": "The number of database operations (queries) executed per second.",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum (\n  rate (\n    django_db_execute_total {\n      cluster=\"$cluster\",\nnamespace=\"$namespace\",\njob=~\"$job\"\n\n    }[$__rate_interval]\n  )\n) by (namespace, job)\n"
    }
   ]
  },
  {
   "title": "Cache Hitrate [30m]",
   "type": "stat",
   "description": "The ratio of cache hits to total cache requests over the last 30 minutes. A higher hit rate indicates better cache performance.",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum (\n  rate (\n    django_cache_get_hits_total {\n      cluster=\"$cluster\",\nnamespace=\"$namespace\",\njob=~\"$job\"\n\n    }[30m]\n  )\n) by (namespace, job)\n/\nsum (\n  rate (\n    django_cache_get_total {\n      cluster=\"$cluster\",\nnamespace=\"$namespace\",\njob=~\"$job\"\n\n    }[30m]\n  )\n) by (namespace, job)\n"
    }
   ]
  },
  {
   "title": "Responses",
   "type": "timeseries",
   "description": "The number of HTTP responses sent per second, categorized by status code classes.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "round(\n  sum(\n    rate(\n      django_http_responses_total_by_status_view_method_total{\n        cluster=\"$cluster\",\nnamespace=\"$namespace\",\njob=~\"$job\"\n,\nview!~\"<unnamed view>|health_check.views.HealthCheckView|prometheus-django-metrics\"\n,\n        status=~\"2.*\",\n      }[$__rate_interval]\n    ) > 0\n  ) by (job), 0.001\n)\n",
     "legendFormat": "2xx"
    },
    {
     "expr": "round(\n  sum(\n    rate(\n      django_http_responses_total_by_status_view_method_total{\n        cluster=\"$cluster\",\nnamespace=\"$namespace\",\njob=~\"$job\"\n,\nview!~\"<unnamed view>|health_check.views.HealthCheckView|prometheus-django-metrics\"\n,\n        status=~\"3.*\",\n      }[$__rate_interval]\n    ) > 0\n  ) by (job), 0.001\n)\n",
     "legendFormat": "3xx"
    },
    {
     "expr": "round(\n  sum(\n    rate(\n      django_http_responses_total_by_status_view_method_total{\n        cluster=\"$cluster\",\nnamespace=\"$namespace\",\njob=~\"$job\"\n,\nview!~\"<unnamed view>|health_check.views.HealthCheckView|prometheus-django-metrics\"\n,\n        status=~\"4.*\",\n      }[$__rate_interval]\n    ) > 0\n  ) by (job), 0.001\n)\n",
     "legendFormat": "4xx"
    },
    {
     "expr": "round(\n  sum(\n    rate(\n      django_http_responses_total_by_status_view_method_total{\n        cluster=\"$cluster\",\nnamespace=\"$namespace\",\njob=~\"$job\"\n,\nview!~\"<unnamed view>|health_check.views.HealthCheckView|prometheus-django-metrics\"\n,\n        status=~\"5.*\",\n      }[$__rate_interval]\n    ) > 0\n  ) by (job), 0.001\n)\n",
     "legendFormat": "5xx"
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Migrations Applied",
   "type": "stat",
   "description": "The total number of database migrations that have been applied.",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max (\n  django_migrations_applied_total {\n    cluster=\"$cluster\",\nnamespace=\"$namespace\",\njob=~\"$job\"\n\n  }\n) by (namespace, job)\n"
    }
   ]
  },
  {
   "title": "Migrations Unapplied",
   "type": "stat",
   "description": "The total number of database migrations that are pending and have not yet been applied.",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max (\n  django_migrations_unapplied_total {\n    cluster=\"$cluster\",\nnamespace=\"$namespace\",\njob=~\"$job\"\n\n  }\n) by (namespace, job)\n"
    }
   ]
  },
  {
   "title": "Database Connections",
   "type": "timeseries",
   "description": "The number of new database connections established, grouped by database vendor. Monitoring connection trends can help identify potential bottlenecks or capacity issues.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(\n  sum(\n    increase(\n      django_db_new_connections_total{\n        cluster=\"$cluster\",\nnamespace=\"$namespace\",\njob=~\"$job\"\n\n      }[$__rate_interval]\n    ) > 0\n  ) by (namespace, job, vendor)\n)\n",
     "legendFormat": "{{ vendor }}"
    }
   ]
  },
  {
   "title": "Database Latency",
   "type": "timeseries",
   "description": "The latency of database queries at various percentiles, grouped by database vendor. This helps identify performance issues and outliers in database response times.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50,\n  sum(\n    irate(\n      django_db_query_duration_seconds_bucket{\n        cluster=\"$cluster\",\nnamespace=\"$namespace\",\njob=~\"$job\"\n\n      }[$__rate_interval]\n    ) > 0\n  ) by (vendor, namespace, job, le)\n)\n",
     "legendFormat": "50 - {{ vendor }}"
    },
    {
     "expr": "histogram_quantile(0.95,\n  sum(\n    irate(\n      django_db_query_duration_seconds_bucket{\n        cluster=\"$cluster\",\nnamespace=\"$namespace\",\njob=~\"$job\"\n\n      }[$__rate_interval]\n    ) > 0\n  ) by (vendor, namespace, job, le)\n)\n",
     "legendFormat": "95 - {{ vendor }}"
    },
    {
     "expr": "histogram_quantile(0.99,\n  sum(\n    irate(\n      django_db_query_duration_seconds_bucket{\n        cluster=\"$cluster\",\nnamespace=\"$namespace\",\njob=~\"$job\"\n\n      }[$__rate_interval]\n    ) > 0\n  ) by (vendor, namespace, job, le)\n)\n",
     "legendFormat": "99 - {{ vendor }}"
    },
    {
     "expr": "histogram_quantile(0.999,\n  sum(\n    irate(\n      django_db_query_duration_seconds_bucket{\n        cluster=\"$cluster\",\nnamespace=\"$namespace\",\njob=~\"$job\"\n\n      }[$__rate_interval]\n    ) > 0\n  ) by (vendor, namespace, job, le)\n)\n",
     "legendFormat": "99.9 - {{ vendor }}"
    }
   ]
  },
  {
   "title": "Top Database Errors (1w)",
   "type": "table",
   "description": "A table displaying the top 10 most frequent database error types over the past week. This helps identify recurring issues that may need attention.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(\n  topk(10,\n    sum(\n      increase(\n        django_db_errors_total{\n          cluster=\"$cluster\",\nnamespace=\"$namespace\",\njob=~\"$job\"\n\n        }[1w]\n      ) > 0\n    ) by (type)\n  )\n)\n"
    }
   ]
  },
  { "title": "Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Cache Get Operations",
   "type": "timeseries",
   "description": "The number of cache get operations, categorized by hits and misses, grouped by cache backend. This helps assess cache performance and effectiveness.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    django_cache_get_hits_total{\n      cluster=\"$cluster\",\nnamespace=\"$namespace\",\njob=~\"$job\"\n\n    }[$__rate_interval]\n  ) > 0\n) by (namespace, job, backend)\n",
     "legendFormat": "Hit - {{ backend }}"
    },
    {
     "expr": "sum(\n  rate(\n    django_cache_get_misses_total{\n      cluster=\"$cluster\",\nnamespace=\"$namespace\",\njob=~\"$job\"\n\n    }[$__rate_interval]\n  ) > 0\n) by (namespace, job, backend)\n",
     "legendFormat": "Miss - {{ backend }}"
    }
   ]
  }
 ]
}