{
 "title": "Apache Solr cluster overview",
 "tags": [ "apache-solr-mixin" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(solr_metrics_jvm_os_cpu_load{}, job)"
   },
   {
    "name": "solr_cluster",
    "label": "Solr cluster",
    "query": "label_values(solr_metrics_jvm_os_cpu_load{job=~\"$job\"}, solr_cluster)"
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" },
   { "name": "k", "label": "Top node count", "query": "5 : 5,10 : 10,20 : 20,50 : 50" },
   {
    "name": "solr_collection",
    "label": "Collection",
    "query": "label_values(solr_metrics_core_errors_total{job=~\"$job\",solr_cluster=~\"$solr_cluster\"}, collection)"
   },
   {
    "name": "solr_core",
    "label": "Core",
    "query": "label_values(solr_metrics_core_errors_total{job=~\"$job\",solr_cluster=~\"$solr_cluster\"}, core)"
   }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Live nodes",
   "type": "stat",
   "description": "Number of live nodes in the Solr cluster.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "min by (job,solr_cluster) (\n  solr_collections_live_nodes{job=~\"$job\",solr_cluster=~\"$solr_cluster\"}\n)",
     "legendFormat": "{{solr_cluster}}"
    }
   ]
  },
  {
   "title": "Zookeeper status",
   "type": "table",
   "description": "Status of ZooKeeper, integral for cluster coordination.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "solr_zookeeper_status{job=~\"$job\",solr_cluster=~\"$solr_cluster\"}",
     "legendFormat": "{{zk_host}}"
    }
   ]
  },
  {
   "title": "Zookeeper ensemble size",
   "type": "timeseries",
   "description": "Size of the ZooKeeper ensemble.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "solr_zookeeper_ensemble_size{job=~\"$job\",solr_cluster=~\"$solr_cluster\"}",
     "legendFormat": "{{zk_host}}"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "alertlist",
   "description": "Panel to report on the status of firing alerts.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Running shards",
   "type": "stat",
   "description": "Percent of running shards in the cluster.",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * sum by (job,solr_cluster) (solr_collections_shard_state{job=~\"$job\",solr_cluster=~\"$solr_cluster\"}) / count by (job,solr_cluster) (solr_collections_shard_state{job=~\"$job\",solr_cluster=~\"$solr_cluster\"})",
     "legendFormat": "{{solr_cluster}}"
    }
   ]
  },
  {
   "title": "Shard status",
   "type": "table",
   "description": "Shows the state of various shards in the cluster.",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "solr_collections_shard_state{job=~\"$job\",solr_cluster=~\"$solr_cluster\"}",
     "legendFormat": "{{shard}}"
    }
   ]
  },
  {
   "title": "Running replicas",
   "type": "stat",
   "description": "Shows the total percent of running shards in the cluster.",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * sum by (job,solr_cluster) (solr_collections_replica_state{job=~\"$job\",solr_cluster=~\"$solr_cluster\"}) / count by (job,solr_cluster) (solr_collections_replica_state{job=~\"$job\",solr_cluster=~\"$solr_cluster\"})",
     "legendFormat": "{{solr_cluster}}"
    }
   ]
  },
  {
   "title": "Replica status",
   "type": "table",
   "description": "State of replicas within a Solr collection.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "solr_collections_replica_state{job=~\"$job\",solr_cluster=~\"$solr_cluster\"}",
     "legendFormat": "{{core}}"
    }
   ]
  },
  { "title": "Top metrics", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 13 } },
  {
   "title": "Top nodes by CPU load",
   "type": "timeseries",
   "description": "CPU load caused by the JVM.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk($k,\n  avg by (job,solr_cluster,base_url) (\n  100 * solr_metrics_jvm_os_cpu_load{item=\"systemCpuLoad\", job=~\"$job\",solr_cluster=~\"$solr_cluster\"}\n)\n)",
     "legendFormat": "{{base_url}}"
    }
   ]
  },
  {
   "title": "Top nodes by heap memory usage",
   "type": "timeseries",
   "description": "Top nodes by the JVM heap memory usage.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk($k,\n  100 * avg by (job,solr_cluster,base_url) (sum without(item)(solr_metrics_jvm_memory_heap_bytes{item=\"used\", job=~\"$job\",solr_cluster=~\"$solr_cluster\"}) / clamp_min(sum without(item)(solr_metrics_jvm_memory_heap_bytes{item=\"max\", job=~\"$job\",solr_cluster=~\"$solr_cluster\"}), 1))\n)",
     "legendFormat": "{{base_url}}"
    }
   ]
  },
  {
   "title": "Top cores by mean queries",
   "type": "timeseries",
   "description": "Top cores by the average rate of query processing in the cluster.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk($k,\n  avg by (job,solr_cluster,base_url,collection,core,searchHandler) (\n  solr_metrics_core_query_mean_rate{category=\"QUERY\", job=~\"$job\",solr_cluster=~\"$solr_cluster\",collection=~\"$solr_collection\", core=~\"$solr_core\"}\n)\n)",
     "legendFormat": "{{collection}} - {{core}} - {{searchHandler}}"
    }
   ]
  },
  {
   "title": "Top cores by update handlers / $__interval",
   "type": "timeseries",
   "description": "Counts the increase in document additions over the specified interval.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk($k,\n  avg by (job,solr_cluster,base_url,collection,core) (\n  increase(solr_metrics_core_update_handler_adds_total{job=~\"$job\",solr_cluster=~\"$solr_cluster\",collection=~\"$solr_collection\", core=~\"$solr_core\"}[$__interval:] offset -$__interval)\n)\n)",
     "legendFormat": "{{collection}} - {{core}}"
    }
   ]
  },
  {
   "title": "Top cores by index size",
   "type": "timeseries",
   "description": "Top cores by the Solr index size.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk($k,\n  avg by (job,solr_cluster,base_url,collection,core) (\n  solr_metrics_core_index_size_bytes{job=~\"$job\",solr_cluster=~\"$solr_cluster\",collection=~\"$solr_collection\", core=~\"$solr_core\"}\n)\n)",
     "legendFormat": "{{collection}} - {{core}}"
    }
   ]
  },
  {
   "title": "Top cores by cache hit ratio",
   "type": "timeseries",
   "description": "Cache hit ratio for documentCache, filterCache, and queryResultCache.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "bottomk($k,\n  avg by (job,solr_cluster,type,base_url,collection,core) (\n  100 * solr_metrics_core_searcher_cache_ratio{type=~\"documentCache|filterCache|queryResultCache\", job=~\"$job\",solr_cluster=~\"$solr_cluster\",collection=~\"$solr_collection\", core=~\"$solr_core\"}\n)\n)",
     "legendFormat": "{{collection}} - {{core}} - {{type}}"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 32 } },
  {
   "title": "Top cores by core errors / $__interval",
   "type": "timeseries",
   "description": "Top cores by Solr core errors.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk($k,\n  avg by (job,solr_cluster,collection,core,baseurl) (\n  increase(solr_metrics_core_errors_total{job=~\"$job\",solr_cluster=~\"$solr_cluster\",collection=~\"$solr_collection\", core=~\"$solr_core\"}[$__interval:] offset -$__interval)\n)\n)",
     "legendFormat": "{{collection}} - {{core}}"
    }
   ]
  },
  {
   "title": "Top nodes by node errors / $__interval",
   "type": "timeseries",
   "description": "Top nodes by Solr node errors.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk($k,\n  avg by (job,solr_cluster,base_url,collection) (\n  increase(solr_metrics_node_errors_total{job=~\"$job\",solr_cluster=~\"$solr_cluster\"}[$__interval:] offset -$__interval)\n)\n)",
     "legendFormat": "{{base_url}}"
    }
   ]
  }
 ]
}