{
 "title": "Apache Solr resource monitoring",
 "tags": [ "apache-solr-mixin" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(solr_metrics_jvm_os_cpu_load{}, job)"
   },
   {
    "name": "solr_cluster",
    "label": "Solr cluster",
    "query": "label_values(solr_metrics_jvm_os_cpu_load{job=~\"$job\"}, solr_cluster)"
   },
   {
    "name": "base_url",
    "label": "Instance",
    "query": "label_values(solr_metrics_jvm_os_cpu_load{job=~\"$job\",solr_cluster=~\"$solr_cluster\"}, base_url)"
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Connections",
   "type": "timeseries",
   "description": "Number of connections to the Solr node.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "\n  avg by (job,solr_cluster,base_url,item) (\n  solr_metrics_node_connections{job=~\"$job\",solr_cluster=~\"$solr_cluster\",base_url=~\"$base_url\"}\n)\n > 0",
     "legendFormat": "{{base_url}} - {{item}}"
    }
   ]
  },
  {
   "title": "Threads / $__interval",
   "type": "timeseries",
   "description": "Total number of tasks submitted and completed in the thread pool.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "\n  avg by (job,solr_cluster,base_url) (\n  increase(solr_metrics_node_thread_pool_submitted_total{executor=\"updateOnlyExecutor\", job=~\"$job\",solr_cluster=~\"$solr_cluster\",base_url=~\"$base_url\"}[$__interval:] offset -$__interval)\n)\n > 0",
     "legendFormat": "{{base_url}} - submitted"
    },
    {
     "expr": "\n  avg by (job,solr_cluster,base_url) (\n  increase(solr_metrics_node_thread_pool_completed_total{executor=\"updateOnlyExecutor\", job=~\"$job\",solr_cluster=~\"$solr_cluster\",base_url=~\"$base_url\"}[$__interval:] offset -$__interval)\n)\n > 0",
     "legendFormat": "{{base_url}} - completed"
    }
   ]
  },
  {
   "title": "Node core FS usage",
   "type": "timeseries",
   "description": "Disk space used by Solr node's root file system.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "\n  avg by (job,solr_cluster,base_url,item) (\n  solr_metrics_node_core_root_fs_bytes{job=~\"$job\",solr_cluster=~\"$solr_cluster\",base_url=~\"$base_url\"}\n)\n > 0",
     "legendFormat": "{{base_url}} - {{item}}"
    }
   ]
  },
  {
   "title": "File descriptors",
   "type": "timeseries",
   "description": "Number of open file descriptors.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "\n  avg by (job,solr_cluster,base_url,item) (\n  solr_metrics_jvm_os_file_descriptors{job=~\"$job\",solr_cluster=~\"$solr_cluster\",base_url=~\"$base_url\"}\n)\n > 0",
     "legendFormat": "{{base_url}} - {{item}}"
    }
   ]
  },
  { "title": "JVM metrics", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 13 } },
  {
   "title": "Garbage collections / $__interval",
   "type": "timeseries",
   "description": "Counts the total number of garbage collection events.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "\n  avg by (job,solr_cluster,base_url,item) (\n  increase(solr_metrics_jvm_gc_total{job=~\"$job\",solr_cluster=~\"$solr_cluster\",base_url=~\"$base_url\"}[$__interval:] offset -$__interval)\n)\n > 0",
     "legendFormat": "{{base_url}} - {{item}}"
    }
   ]
  },
  {
   "title": "Garbage collection time / $__interval",
   "type": "timeseries",
   "description": "Total time spent in garbage collection.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (job,solr_cluster,base_url,item) (increase(solr_metrics_jvm_gc_seconds_total{job=~\"$job\",solr_cluster=~\"$solr_cluster\",base_url=~\"$base_url\"}[$__interval:] offset -$__interval) / clamp_min(increase(solr_metrics_jvm_gc_total{job=~\"$job\",solr_cluster=~\"$solr_cluster\",base_url=~\"$base_url\"}[$__interval:] offset -$__interval), 1)) > 0",
     "legendFormat": "{{base_url}} - {{item}}"
    }
   ]
  },
  {
   "title": "CPU load",
   "type": "timeseries",
   "description": "CPU load caused by the JVM.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "\n  avg by (job,solr_cluster,base_url) (\n  100 * solr_metrics_jvm_os_cpu_load{item=\"systemCpuLoad\", job=~\"$job\",solr_cluster=~\"$solr_cluster\",base_url=~\"$base_url\"}\n)\n > 0",
     "legendFormat": "{{base_url}}"
    }
   ]
  },
  {
   "title": "OS memory",
   "type": "timeseries",
   "description": "The operating system's virtual committed memory, free physical memory and total physical memory usage.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "\n  avg by (job,solr_cluster,base_url) (\n  solr_metrics_jvm_os_memory_bytes{item=\"freePhysicalMemorySize\", job=~\"$job\",solr_cluster=~\"$solr_cluster\",base_url=~\"$base_url\"}\n)\n > 0",
     "legendFormat": "{{base_url}} - free physical"
    },
    {
     "expr": "\n  avg by (job,solr_cluster,base_url) (\n  solr_metrics_jvm_os_memory_bytes{item=\"totalPhysicalMemorySize\", job=~\"$job\",solr_cluster=~\"$solr_cluster\",base_url=~\"$base_url\"}\n)\n > 0",
     "legendFormat": "{{base_url}} - total physical"
    },
    {
     "expr": "\n  avg by (job,solr_cluster,base_url) (\n  solr_metrics_jvm_os_memory_bytes{item=\"committedVirtualMemorySize\", job=~\"$job\",solr_cluster=~\"$solr_cluster\",base_url=~\"$base_url\"}\n)\n > 0",
     "legendFormat": "{{base_url}} - committed virtual"
    }
   ]
  },
  {
   "title": "Memory used",
   "type": "timeseries",
   "description": "The heap and non-heap memory used by the JVM.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "\n  avg by (job,solr_cluster,base_url) (\n  solr_metrics_jvm_memory_heap_bytes{item=\"used\", job=~\"$job\",solr_cluster=~\"$solr_cluster\",base_url=~\"$base_url\"}\n)\n > 0",
     "legendFormat": "{{base_url}} - heap"
    },
    {
     "expr": "\n  avg by (job,solr_cluster,base_url) (\n  solr_metrics_jvm_memory_non_heap_bytes{item=\"used\", job=~\"$job\",solr_cluster=~\"$solr_cluster\",base_url=~\"$base_url\"}\n)\n > 0",
     "legendFormat": "{{base_url}} - non-heap"
    }
   ]
  },
  {
   "title": "Memory committed",
   "type": "timeseries",
   "description": "The heap and non-heap memory committed by the JVM.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "\n  avg by (job,solr_cluster,base_url) (\n  solr_metrics_jvm_memory_heap_bytes{item=\"committed\", job=~\"$job\",solr_cluster=~\"$solr_cluster\",base_url=~\"$base_url\"}\n)\n > 0",
     "legendFormat": "{{base_url}} - heap"
    },
    {
     "expr": "\n  avg by (job,solr_cluster,base_url) (\n  solr_metrics_jvm_memory_non_heap_bytes{item=\"committed\", job=~\"$job\",solr_cluster=~\"$solr_cluster\",base_url=~\"$base_url\"}\n)\n > 0",
     "legendFormat": "{{base_url}} - non-heap"
    }
   ]
  },
  { "title": "Jetty metrics", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 32 } },
  {
   "title": "Requests  / $__interval",
   "type": "timeseries",
   "description": "Total number of requests received by Jetty.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "\n  avg by (job,solr_cluster,base_url,method) (\n  increase(solr_metrics_jetty_requests_total{job=~\"$job\",solr_cluster=~\"$solr_cluster\",base_url=~\"$base_url\"}[$__interval:] offset -$__interval)\n)\n > 0",
     "legendFormat": "{{base_url}} - {{method}}"
    }
   ]
  },
  {
   "title": "Responses  / $__interval",
   "type": "timeseries",
   "description": "Total number of responses generated by Jetty.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "\n  avg by (job,solr_cluster,base_url,status) (\n  increase(solr_metrics_jetty_response_total{job=~\"$job\",solr_cluster=~\"$solr_cluster\",base_url=~\"$base_url\"}[$__interval:] offset -$__interval)\n)\n > 0",
     "legendFormat": "{{base_url}} - {{status}}"
    }
   ]
  },
  {
   "title": "Dispatches  / $__interval",
   "type": "timeseries",
   "description": "Total count of dispatches handled by Jetty.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "\n  avg by (job,solr_cluster,base_url) (\n  increase(solr_metrics_jetty_dispatches_total{job=~\"$job\",solr_cluster=~\"$solr_cluster\",base_url=~\"$base_url\"}[$__interval:] offset -$__interval)\n)\n > 0",
     "legendFormat": "{{base_url}}"
    }
   ]
  }
 ]
}