{
 "title": "Jenkins",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": "label_values(up, job)" },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(up{job=~\"$job\"}, instance)"
   },
   { "name": "prefix", "label": "Prefix", "query": "default" }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total executors",
   "type": "stat",
   "description": "Total number of job executors",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "jenkins_executor_count_value{job=~\"$job\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Executors by state",
   "type": "piechart",
   "description": "Shows distribution of executors by their current state",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jenkins_executor_free_value{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "free"
    },
    {
     "expr": "jenkins_executor_in_use_value{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "in-use"
    }
   ]
  },
  {
   "title": "Job success rate",
   "type": "stat",
   "description": "Rate of jobs that are successful over the specified interval.",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(jenkins_runs_success_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Job failure rate",
   "type": "stat",
   "description": "Rate of jobs failing over the specified interval.",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(jenkins_runs_failure_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Build nodes online",
   "type": "gauge",
   "description": "Percentage of build nodes online",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "jenkins_node_online_value{job=~\"$job\", instance=~\"$instance\"}/jenkins_node_count_value{job=~\"$job\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Plugins by state",
   "type": "bargauge",
   "description": "Plugins grouped by different states.",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jenkins_plugins_active{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "active"
    },
    {
     "expr": "jenkins_plugins_inactive{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "inactive"
    },
    {
     "expr": "jenkins_plugins_failed{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "failed"
    },
    {
     "expr": "jenkins_plugins_withUpdate{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "with update"
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Least healthy jobs",
   "type": "table",
   "description": "Bottom 5 least healthiest jobs.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "bottomk(5, avg by (jenkins_job) ({__name__=~\"$prefix\\\\_?jenkins_builds_health_score\", job=~\"$job\", instance=~\"$instance\"}))"
    },
    {
     "expr": "sum by (jenkins_job) ({__name__=~\"$prefix\\\\_?jenkins_builds_failed_build_count\", job=~\"$job\", instance=~\"$instance\"}) and on (jenkins_job) bottomk(5, avg by (jenkins_job) ({__name__=~\"$prefix\\\\_?jenkins_builds_health_score\", job=~\"$job\", instance=~\"$instance\"}))"
    },
    {
     "expr": "sum by (jenkins_job) ({__name__=~\"$prefix\\\\_?jenkins_builds_success_build_count\", job=~\"$job\", instance=~\"$instance\"}) and on (jenkins_job) bottomk(5, avg by (jenkins_job) ({__name__=~\"$prefix\\\\_?jenkins_builds_health_score\", job=~\"$job\", instance=~\"$instance\"}))"
    },
    {
     "expr": "sum by (jenkins_job) ({__name__=~\"$prefix\\\\_jenkins_builds_failed_build_count|$prefix\\\\_?jenkins_builds_success_build_count\", job=~\"$job\", instance=~\"$instance\"}) and on (jenkins_job) bottomk(5, avg by (jenkins_job) ({__name__=~\"$prefix\\\\_?jenkins_builds_health_score\", job=~\"$job\", instance=~\"$instance\"}))"
    }
   ]
  },
  {
   "title": "Latest build duration by job",
   "type": "timeseries",
   "description": "Latest duration of the jobs",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max by (jenkins_job) ({__name__=~\"$prefix\\\\_?jenkins_builds_last_build_duration_milliseconds\", job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{jenkins_job}}"
    }
   ]
  },
  {
   "title": "Top 5 slowest jobs",
   "type": "table",
   "description": "List of the top 5 slowest jobs.",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(5, max by (jenkins_job) ({__name__=~\"$prefix\\\\_?jenkins_builds_last_build_duration_milliseconds\", job=~\"$job\", instance=~\"$instance\"}))"
    }
   ]
  },
  {
   "title": "Job queue by state",
   "type": "timeseries",
   "description": "Queued jobs grouped by state.",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jenkins_queue_stuck_value{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Stuck"
    },
    {
     "expr": "jenkins_queue_blocked_value{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Blocked"
    },
    {
     "expr": "jenkins_queue_pending_value{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Pending"
    },
    {
     "expr": "jenkins_queue_buildable_value{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Buildable"
    }
   ]
  },
  {
   "title": "Web UI",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Web request rate by status",
   "type": "timeseries",
   "description": "Total web requests group by different HTTP status codes.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(http_responseCodes_ok_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "200 {{instance}}"
    },
    {
     "expr": "rate(http_responseCodes_created_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "201 {{instance}}"
    },
    {
     "expr": "rate(http_responseCodes_noContent_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "204 {{instance}}"
    },
    {
     "expr": "rate(http_responseCodes_notModified_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "304 {{instance}}"
    },
    {
     "expr": "rate(http_responseCodes_badRequest_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "400 {{instance}}"
    },
    {
     "expr": "rate(http_responseCodes_forbidden_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "403 {{instance}}"
    },
    {
     "expr": "rate(http_responseCodes_notFound_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "404 {{instance}}"
    },
    {
     "expr": "rate(http_responseCodes_serverError_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "500 {{instance}}"
    },
    {
     "expr": "rate(http_responseCodes_serviceUnavailable_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "503 {{instance}}"
    },
    {
     "expr": "rate(http_responseCodes_other_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "other {{instance}}"
    }
   ]
  },
  {
   "title": "HTTP request duration by quantile",
   "type": "bargauge",
   "description": "Shows a distribution of HTTP request durations by quantile.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "http_requests{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  }
 ]
}