{
 "title": "OpenSearch node overview",
 "tags": [ "opensearch-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(opensearch_os_cpu_percent{cluster!=\"\"}, job)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(opensearch_os_cpu_percent{cluster!=\"\",job=~\"$job\"}, cluster)"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(opensearch_os_cpu_percent{cluster!=\"\",job=~\"$job\",cluster=~\"$cluster\"}, node)"
   }
  ]
 },
 "panels": [
  {
   "title": "Roles timeline",
   "type": "status-history",
   "description": "OpenSearch node roles over time.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max by (node,role) (\n    max_over_time(opensearch_node_role_bool{cluster!=\"\",job=~\"$job\",cluster=~\"$cluster\",node=~\"$node\", role=\"data\"}[1m]) == 1\n) * 2\n",
     "legendFormat": "{{node}}"
    },
    {
     "expr": "max by (node,role) (\n    max_over_time(opensearch_node_role_bool{cluster!=\"\",job=~\"$job\",cluster=~\"$cluster\",node=~\"$node\", role=\"master\"}[1m]) == 1\n) * 3\n",
     "legendFormat": "{{node}}"
    },
    {
     "expr": "max by (node,role) (\n    max_over_time(opensearch_node_role_bool{cluster!=\"\",job=~\"$job\",cluster=~\"$cluster\",node=~\"$node\", role=\"ingest\"}[1m]) == 1\n) * 4\n",
     "legendFormat": "{{node}}"
    },
    {
     "expr": "max by (node,role) (\n    max_over_time(opensearch_node_role_bool{cluster!=\"\",job=~\"$job\",cluster=~\"$cluster\",node=~\"$node\", role=\"cluster_manager\"}[1m]) == 1\n) * 5\n",
     "legendFormat": "{{node}}"
    },
    {
     "expr": "max by (node,role) (\n    max_over_time(opensearch_node_role_bool{cluster!=\"\",job=~\"$job\",cluster=~\"$cluster\",node=~\"$node\", role=\"remote_cluster_client\"}[1m]) == 1\n) * 6\n",
     "legendFormat": "{{node}}"
    }
   ]
  },
  { "title": "Node health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Node CPU usage",
   "type": "timeseries",
   "description": "CPU usage percentage of the node's Operating System.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "opensearch_os_cpu_percent{cluster!=\"\",job=~\"$job\",cluster=~\"$cluster\",node=~\"$node\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Node memory usage",
   "type": "timeseries",
   "description": "Memory usage percentage of the node for the Operating System and OpenSearch",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "opensearch_os_mem_used_percent{cluster!=\"\",job=~\"$job\",cluster=~\"$cluster\",node=~\"$node\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Node I/O",
   "type": "timeseries",
   "description": "Node file system read and write data.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(job,cluster,node) (rate(opensearch_fs_io_total_read_bytes{cluster!=\"\",job=~\"$job\",cluster=~\"$cluster\",node=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{node}} - read"
    },
    {
     "expr": "sum by(job,cluster,node) (rate(opensearch_fs_io_total_write_bytes{cluster!=\"\",job=~\"$job\",cluster=~\"$cluster\",node=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{node}} - write"
    }
   ]
  },
  {
   "title": "Node open connections",
   "type": "timeseries",
   "description": "Number of open connections for the selected node.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 2 },
   "targets": [
    {
     "expr": "sum by (job,cluster,node) (opensearch_transport_server_open_number{cluster!=\"\",job=~\"$job\",cluster=~\"$cluster\",node=~\"$node\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Node disk usage",
   "type": "timeseries",
   "description": "Disk usage percentage of the selected node.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (100 * opensearch_fs_path_free_bytes{cluster!=\"\",job=~\"$job\",cluster=~\"$cluster\",node=~\"$node\"} / clamp_min(opensearch_fs_path_total_bytes{cluster!=\"\",job=~\"$job\",cluster=~\"$cluster\",node=~\"$node\"}, 1))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Node memory swap",
   "type": "timeseries",
   "description": "Percentage of swap space used by OpenSearch and the Operating System on the selected node.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * opensearch_os_swap_used_bytes{cluster!=\"\",job=~\"$job\",cluster=~\"$cluster\",node=~\"$node\"} / clamp_min((opensearch_os_swap_used_bytes{cluster!=\"\",job=~\"$job\",cluster=~\"$cluster\",node=~\"$node\"} + opensearch_os_swap_free_bytes{cluster!=\"\",job=~\"$job\",cluster=~\"$cluster\",node=~\"$node\"}), 1)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Node network traffic",
   "type": "timeseries",
   "description": "Node network traffic sent and received.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by (job,cluster,node) (rate(opensearch_transport_tx_bytes_count{cluster!=\"\",job=~\"$job\",cluster=~\"$cluster\",node=~\"$node\"}[$__rate_interval])) * 8",
     "legendFormat": "{{node}} - sent"
    },
    {
     "expr": "sum by (job,cluster,node) (rate(opensearch_transport_rx_bytes_count{cluster!=\"\",job=~\"$job\",cluster=~\"$cluster\",node=~\"$node\"}[$__rate_interval])) * 8",
     "legendFormat": "{{node}} - received"
    }
   ]
  },
  {
   "title": "Circuit breakers",
   "type": "timeseries",
   "description": "Circuit breakers tripped on the selected node by type",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "trips" } },
   "targets": [
    {
     "expr": "sum by(name, job,cluster,node) (increase(opensearch_circuitbreaker_tripped_count{cluster!=\"\",job=~\"$job\",cluster=~\"$cluster\",node=~\"$node\"}[$__interval:]))",
     "legendFormat": "{{node}} - {{ name }}"
    }
   ]
  },
  { "title": "Node JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "JVM heap used vs. committed",
   "type": "timeseries",
   "description": "The amount of heap memory used vs committed on the selected node.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (job,cluster,node) (opensearch_jvm_mem_heap_used_bytes{cluster!=\"\",job=~\"$job\",cluster=~\"$cluster\",node=~\"$node\"})",
     "legendFormat": "{{node}} - used"
    },
    {
     "expr": "sum by (job,cluster,node) (opensearch_jvm_mem_heap_committed_bytes{cluster!=\"\",job=~\"$job\",cluster=~\"$cluster\",node=~\"$node\"})",
     "legendFormat": "{{node}} - commited"
    }
   ]
  },
  {
   "title": "JVM non-heap used vs. committed",
   "type": "timeseries",
   "description": "The amount of non-heap memory used vs committed on the selected node.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (job,cluster,node) (opensearch_jvm_mem_nonheap_used_bytes{cluster!=\"\",job=~\"$job\",cluster=~\"$cluster\",node=~\"$node\"})",
     "legendFormat": "{{node}} - used"
    },
    {
     "expr": "sum by (job,cluster,node) (opensearch_jvm_mem_nonheap_committed_bytes{cluster!=\"\",job=~\"$job\",cluster=~\"$cluster\",node=~\"$node\"})",
     "legendFormat": "{{node}} - commited"
    }
   ]
  },
  {
   "title": "JVM threads",
   "type": "timeseries",
   "description": "The number of threads running in the JVM on the selected node.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "threads" } },
   "targets": [
    {
     "expr": "sum by (job,cluster,node) (opensearch_jvm_threads_number{cluster!=\"\",job=~\"$job\",cluster=~\"$cluster\",node=~\"$node\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "JVM buffer pools",
   "type": "timeseries",
   "description": "The number of buffer pools available on the selected node.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "buffer pools" } },
   "targets": [
    {
     "expr": "sum by( job,cluster,node, bufferpool) (opensearch_jvm_bufferpool_number{cluster!=\"\",job=~\"$job\",cluster=~\"$cluster\",node=~\"$node\"})",
     "legendFormat": "{{node}} - {{bufferpool}}"
    }
   ]
  },
  {
   "title": "JVM uptime",
   "type": "timeseries",
   "description": "The uptime of the JVM in seconds on the selected node.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(job,cluster,node) (opensearch_jvm_uptime_seconds{cluster!=\"\",job=~\"$job\",cluster=~\"$cluster\",node=~\"$node\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "JVM garbage collections",
   "type": "timeseries",
   "description": "The number of garbage collection operations on the selected node.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "operations" } },
   "targets": [
    {
     "expr": "sum by (job,cluster,node) (increase(opensearch_jvm_gc_collection_count{cluster!=\"\",job=~\"$job\",cluster=~\"$cluster\",node=~\"$node\"}[$__interval:]))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "JVM garbage collection time",
   "type": "timeseries",
   "description": "The amount of time spent on garbage collection on the selected node.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (job,cluster,node) (increase(opensearch_jvm_gc_collection_time_seconds{cluster!=\"\",job=~\"$job\",cluster=~\"$cluster\",node=~\"$node\"}[$__interval:]))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "JVM buffer pool usage",
   "type": "timeseries",
   "description": "The percent used of JVM buffer pool memory.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (sum by (job,cluster,node, bufferpool) (opensearch_jvm_bufferpool_used_bytes{cluster!=\"\",job=~\"$job\",cluster=~\"$cluster\",node=~\"$node\"})) / clamp_min((sum by (job, bufferpool, cluster) (opensearch_jvm_bufferpool_total_capacity_bytes{cluster!=\"\",job=~\"$job\",cluster=~\"$cluster\",node=~\"$node\"})),1)",
     "legendFormat": "{{node}} - {{bufferpool}}"
    }
   ]
  },
  { "title": "Thread pools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Thread pool threads",
   "type": "timeseries",
   "description": "The number of threads in the thread pool for the selected node",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "threads" } },
   "targets": [
    {
     "expr": "sum by(job,cluster,node) ((opensearch_threadpool_threads_number{cluster!=\"\",job=~\"$job\",cluster=~\"$cluster\",node=~\"$node\"}))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Thread pool tasks",
   "type": "timeseries",
   "description": "The number of tasks in the thread pool for the selected node.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "tasks" } },
   "targets": [
    {
     "expr": "sum by (job,cluster,node) (opensearch_threadpool_tasks_number{cluster!=\"\",job=~\"$job\",cluster=~\"$cluster\",node=~\"$node\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Error logs panel",
   "type": "logs",
   "description": "The recent error logs being reported by OpenSearch.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "{cluster!=\"\",job=~\"$job\",cluster=~\"$cluster\",node=~\"$node\"} |~ \"\""
    }
   ]
  }
 ]
}