{
 "title": "Harbor",
 "tags": [ "Integration - Harbor" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "Project", "query": { "query": "label_values(project_name)" } },
   { "name": "job", "label": "job", "query": { "query": "label_values(job)" } },
   { "name": "cluster", "label": "cluster", "query": { "query": "label_values(cluster)" } }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": {
    "content": "# ![harborimage](https://goharbor.io/img/logos/harbor-horizontal-color.png)"
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "bargauge",
   "description": "Current status of Harbor components",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "harbor_up{job=~\"$job\", cluster=~\"$cluster\"}",
     "legendFormat": "{{component}}"
    }
   ]
  },
  {
   "title": "Harbor Version",
   "type": "table",
   "description": "Version information about your Harbor instance\t",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "max(harbor_system_info{job=~\"$job\", cluster=~\"$cluster\"}) by (harbor_version)"
    }
   ]
  },
  {
   "title": "Projects",
   "type": "stat",
   "description": "Total number of public and private projects",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(harbor_project_total{job=~\"$job\", cluster=~\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Images",
   "type": "stat",
   "description": "Total number of images in Harbor",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(harbor_project_artifact_total{job=~\"$job\", artifact_type=\"IMAGE\", cluster=~\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Charts",
   "type": "stat",
   "description": "Total number of Charts in Harbor",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(harbor_project_artifact_total{job=~\"$job\", artifact_type=\"CHART\", cluster=~\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Artifacts pulled",
   "type": "bargauge",
   "description": "Number of artifacts pulled in a project",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(harbor_artifact_pulled{job=~\"$job\", project_name=~\"$Project\", cluster=~\"$cluster\"}[$__range])",
     "legendFormat": "{{project_name}}"
    }
   ]
  },
  { "title": "Harbor Core", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "description": "Rate of requests, grouped by request type",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(harbor_core_http_request_total{job=~\"$job\", cluster=~\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "In-flight requests",
   "type": "timeseries",
   "description": "The total number of In-flight requests",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "harbor_core_http_inflight_requests{job=~\"$job\", cluster=~\"$cluster\"}",
     "legendFormat": "In-flight"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "timeseries",
   "description": "The time duration of the requests",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(harbor_core_http_request_duration_seconds{job=~\"$job\", cluster=~\"$cluster\"}  >0) by (quantile)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Users & Projects", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Project Quota Usage",
   "type": "gauge",
   "description": "Percentage of total used resources of a project\tby Quota set in a project",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "harbor_project_quota_usage_byte{job=~\"$job\", cluster=~\"$cluster\", project_name=~\"$Project\"}/ harbor_project_quota_byte{job=~\"$job\", project_name=~\"$Project\"} ",
     "legendFormat": "{{project_name}}"
    }
   ]
  },
  {
   "title": "Members",
   "type": "stat",
   "description": "Total number of members in a project",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "harbor_project_member_total{job=~\"$job\", project_name=~\"$Project\", cluster=~\"$cluster\"}",
     "legendFormat": "{{project_name}}"
    }
   ]
  },
  {
   "title": "Artifacts by Project",
   "type": "marcusolsson-treemap-panel",
   "description": "Amount of Artifacts grouped by project",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "harbor_project_artifact_total{job=~\"$job\",project_name=~\"$Project\", cluster=~\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Repositories",
   "type": "gauge",
   "description": "Total number of repositories in a project",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "harbor_project_repo_total{job=~\"$job\",project_name=~\"$Project\", cluster=~\"$cluster\"}",
     "legendFormat": "{{project_name}}"
    }
   ]
  },
  { "title": "Registry", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "HTTP Error Rate",
   "type": "timeseries",
   "description": "HTTP Error Rate of Requests",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(registry_http_requests_total{code=~\"4..|5..\",job=~\"$job\", cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Registry Storage Action",
   "type": "timeseries",
   "description": "The number of seconds that the storage action take",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "registry_storage_action_seconds_bucket{job=~\"$job\", cluster=~\"$cluster\"}",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Registry Request Size",
   "type": "timeseries",
   "description": "The HTTP request sizes in bytes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "registry_http_request_size_bytes_bucket{job=~\"$job\", cluster=~\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Registry Response Size",
   "type": "timeseries",
   "description": "The HTTP response sizes in bytes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "registry_http_response_size_bytes_bucket{job=~\"$job\", cluster=~\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Registry Request Duration",
   "type": "timeseries",
   "description": "The HTTP request latencies in seconds",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "registry_http_request_duration_seconds_bucket{job=~\"$job\", cluster=~\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "In-flight HTTP requests",
   "type": "status-history",
   "description": "The in-flight HTTP requests\tof Registry",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "registry_http_in_flight_requests{job=~\"$job\", cluster=~\"$cluster\"}",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  { "title": "JobService", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "JobService Workers",
   "type": "table",
   "description": "Count of JobService Workers",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "harbor_jobservice_info{job=~\"$job\", cluster=~\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Tasks",
   "type": "barchart",
   "description": "The number of processed tasks per job type",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "harbor_jobservice_task_total{job=~\"$job\", cluster=~\"$cluster\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "JobService Task Process Time",
   "type": "status-history",
   "description": "The duration of the task processing time",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "harbor_jobservice_task_process_time_seconds{job=~\"$job\", quantile=\"0.9\", cluster=~\"$cluster\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Tasks Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 } },
  {
   "title": "Task Queue Size",
   "type": "timeseries",
   "description": "The total number of tasks per type in the queue",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "harbor_task_queue_size{job=~\"$job\", cluster=~\"$cluster\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Task Queue Latency",
   "type": "timeseries",
   "description": "How long ago the next job to be processed was enqueued per type",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "harbor_task_queue_latency{job=~\"$job\", cluster=~\"$cluster\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Task Concurrency",
   "type": "timeseries",
   "description": "Total number of concurrent tasks per type on a pool",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "harbor_task_concurrency{job=~\"$job\", cluster=~\"$cluster\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Scheduled tasks",
   "type": "barchart",
   "description": "Number of scheduled tasks",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "harbor_task_scheduled_total{job=~\"$job\", cluster=~\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}