{
 "title": "Couchbase cluster overview",
 "tags": [ "couchbase-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(kv_mem_used_bytes{job=~\"integrations/couchbase\"}, job)"
   },
   {
    "name": "couchbase_cluster",
    "label": "Couchbase_cluster",
    "query": "label_values(kv_mem_used_bytes{job=~\"integrations/couchbase\",job=~\"$job\"}, couchbase_cluster)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(kv_mem_used_bytes{job=~\"integrations/couchbase\",job=~\"$job\",couchbase_cluster=~\"$couchbase_cluster\"}, instance)"
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" }
  ]
 },
 "panels": [
  {
   "title": "Top nodes by memory usage",
   "type": "timeseries",
   "description": "Top nodes by memory usage across the Couchbase cluster.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk(5, sum by(job,couchbase_cluster,instance) (sys_mem_actual_used{job=~\"integrations/couchbase\",job=~\"$job\",couchbase_cluster=~\"$couchbase_cluster\",instance=~\"$instance\"})) / (sum by(job,couchbase_cluster,instance) (clamp_min(sys_mem_actual_free{job=~\"integrations/couchbase\",job=~\"$job\",couchbase_cluster=~\"$couchbase_cluster\",instance=~\"$instance\"}, 1)) + sum by(job,couchbase_cluster,instance) (sys_mem_actual_used{job=~\"integrations/couchbase\",job=~\"$job\",couchbase_cluster=~\"$couchbase_cluster\",instance=~\"$instance\"}))",
     "legendFormat": "{{couchbase_cluster}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Top nodes by HTTP requests",
   "type": "timeseries",
   "description": "Rate of HTTP requests handled by the cluster manager for the top nodes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(5, sum by(job,couchbase_cluster,instance) (rate(cm_http_requests_total{job=~\"integrations/couchbase\",job=~\"$job\",couchbase_cluster=~\"$couchbase_cluster\",instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "{{couchbase_cluster}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Top nodes by query service requests",
   "type": "timeseries",
   "description": "Rate of N1QL requests processed by the query service for the top nodes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(5, sum by(job,couchbase_cluster,instance) (rate(n1ql_requests{job=~\"integrations/couchbase\",job=~\"$job\",couchbase_cluster=~\"$couchbase_cluster\",instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "{{couchbase_cluster}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Top nodes by index average scan latency",
   "type": "timeseries",
   "description": "Average time to serve an index service scan request for the top nodes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "topk(5, avg by(job,couchbase_cluster,instance) (index_avg_scan_latency{job=~\"integrations/couchbase\",job=~\"$job\",couchbase_cluster=~\"$couchbase_cluster\",instance=~\"$instance\"}))",
     "legendFormat": "{{couchbase_cluster}} - {{instance}}"
    }
   ]
  },
  {
   "title": "XDCR replication rate",
   "type": "timeseries",
   "description": "Rate of replication through the Cross Data Center Replication feature.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(job,couchbase_cluster,instance) (rate(xdcr_data_replicated_bytes{job=~\"integrations/couchbase\",job=~\"$job\",couchbase_cluster=~\"$couchbase_cluster\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{couchbase_cluster}}"
    }
   ]
  },
  {
   "title": "XDCR docs received",
   "type": "timeseries",
   "description": "The rate of mutations received by this cluster.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "mut/sec" } },
   "targets": [
    {
     "expr": "sum by(job,couchbase_cluster) (rate(xdcr_docs_received_from_dcp_total{job=~\"integrations/couchbase\",job=~\"$job\",couchbase_cluster=~\"$couchbase_cluster\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{couchbase_cluster}}"
    }
   ]
  },
  {
   "title": "Local backup size",
   "type": "bargauge",
   "description": "Size of the local backup for a node.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "targets": [
    {
     "expr": "sum by(job,couchbase_cluster,instance) (backup_data_size{job=~\"integrations/couchbase\",job=~\"$job\",couchbase_cluster=~\"$couchbase_cluster\",instance=~\"$instance\"})",
     "legendFormat": "{{couchbase_cluster}} - {{instance}}"
    }
   ]
  },
  { "title": "Buckets", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 24, "y": 24 } },
  {
   "title": "Top buckets by memory used",
   "type": "timeseries",
   "description": "Memory used for the top buckets across the cluster.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "topk(5, sum by(bucket, job,couchbase_cluster) (kv_mem_used_bytes{job=~\"integrations/couchbase\",job=~\"$job\",couchbase_cluster=~\"$couchbase_cluster\",instance=~\"$instance\"}))",
     "legendFormat": "{{couchbase_cluster}} - {{bucket}}"
    }
   ]
  },
  {
   "title": "Top buckets by disk used",
   "type": "bargauge",
   "description": "Disk used for the top buckets across the cluster.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "topk(5, sum by(job,couchbase_cluster, bucket) (couch_docs_actual_disk_size{job=~\"integrations/couchbase\",job=~\"$job\",couchbase_cluster=~\"$couchbase_cluster\",instance=~\"$instance\"}))",
     "legendFormat": "{{couchbase_cluster}} - {{bucket}}"
    }
   ]
  },
  {
   "title": "Top buckets by operations",
   "type": "timeseries",
   "description": "Rate of operations for the busiest buckets across the cluster.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk(5, sum by(job,couchbase_cluster, bucket) (rate(kv_ops{job=~\"integrations/couchbase\",job=~\"$job\",couchbase_cluster=~\"$couchbase_cluster\",instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "{{couchbase_cluster}} - {{bucket}}"
    }
   ]
  },
  {
   "title": "Top buckets by operations failed",
   "type": "timeseries",
   "description": "Rate of operations failed for the most problematic buckets across the cluster.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk(5, sum by(job,couchbase_cluster, bucket) (rate(kv_ops_failed{job=~\"integrations/couchbase\",job=~\"$job\",couchbase_cluster=~\"$couchbase_cluster\",instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "{{couchbase_cluster}} - {{bucket}}"
    }
   ]
  },
  {
   "title": "Top buckets by vBuckets count",
   "type": "bargauge",
   "description": "The number of vBuckets for the top buckets across the cluster.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(5, sum by(job,couchbase_cluster, bucket) (kv_num_vbuckets{job=~\"integrations/couchbase\",job=~\"$job\",couchbase_cluster=~\"$couchbase_cluster\",instance=~\"$instance\"}))",
     "legendFormat": "{{couchbase_cluster}} - {{bucket}}"
    }
   ]
  },
  {
   "title": "Top buckets by vBucket queue memory",
   "type": "timeseries",
   "description": "Memory occupied by the queue for a virtual bucket for the top buckets across the cluster.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "topk(5, sum by(job,couchbase_cluster, bucket) (kv_vb_queue_memory_bytes{job=~\"integrations/couchbase\",job=~\"$job\",couchbase_cluster=~\"$couchbase_cluster\",instance=~\"$instance\"}))",
     "legendFormat": "{{couchbase_cluster}} - {{bucket}}"
    }
   ]
  }
 ]
}