{
 "title": "MongoDB Atlas performance overview",
 "description": "Overview of MongoDB Atlas performance metrics.",
 "tags": [ "mongodb-atlas-mixin" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(mongodb_network_bytesIn{}, job)"
   },
   {
    "name": "cl_name",
    "label": "Atlas cluster",
    "query": "label_values(mongodb_network_bytesIn{job=~\"$job\"}, cl_name)"
   },
   {
    "name": "instance",
    "label": "Node",
    "query": "label_values(mongodb_network_bytesIn{job=~\"$job\",cl_name=~\"$cl_name\"}, instance)"
   },
   {
    "name": "rs_nm",
    "label": "Replica set",
    "query": "label_values(mongodb_network_bytesIn, rs_nm)"
   }
  ]
 },
 "panels": [
  { "title": "Memory and hardware", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Memory",
   "type": "timeseries",
   "description": "The amount of RAM and virtual memory being used by the database process.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "mongodb_mem_resident{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\", rs_nm=~\"$rs_nm\"}",
     "legendFormat": "{{instance}} - RAM"
    },
    {
     "expr": "mongodb_mem_virtual{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\", rs_nm=~\"$rs_nm\"}",
     "legendFormat": "{{instance}} - virtual"
    }
   ]
  },
  {
   "title": "Hardware CPU interrupt service time / $__interval",
   "type": "timeseries",
   "description": "The amount of time spent servicing CPU interrupts.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "increase(hardware_system_cpu_irq_milliseconds{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 9 } },
  {
   "title": "Disk space",
   "type": "timeseries",
   "description": "The amount of free and used disk space on this node's hardware.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "hardware_disk_metrics_disk_space_free_bytes{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - free"
    },
    {
     "expr": "hardware_disk_metrics_disk_space_used_bytes{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - used"
    }
   ]
  },
  {
   "title": "Disk space utilization",
   "type": "timeseries",
   "description": "The disk space utilization for this node's hardware.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(hardware_disk_metrics_disk_space_used_bytes{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\"}) / clamp_min((hardware_disk_metrics_disk_space_free_bytes{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\"}) + (hardware_disk_metrics_disk_space_used_bytes{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\"}), 1)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 18 } },
  {
   "title": "Network requests",
   "type": "timeseries",
   "description": "The rate of distinct requests the node has received.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(mongodb_network_numRequests{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\", rs_nm=~\"$rs_nm\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Slow network requests",
   "type": "timeseries",
   "description": "The rate of slow DNS and SSL operations received by this node.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(mongodb_network_numSlowDNSOperations{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\", rs_nm=~\"$rs_nm\"}[$__rate_interval]) > 0",
     "legendFormat": "{{instance}} - DNS"
    },
    {
     "expr": "rate(mongodb_network_numSlowSSLOperations{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\", rs_nm=~\"$rs_nm\"}[$__rate_interval]) > 0",
     "legendFormat": "{{instance}} - SSL"
    }
   ]
  },
  {
   "title": "Network throughput",
   "type": "timeseries",
   "description": "The rate of bytes sent and received by the node over a network connection.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(mongodb_network_bytesIn{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\", rs_nm=~\"$rs_nm\"}[$__rate_interval]) > 0",
     "legendFormat": "{{instance}} - received"
    },
    {
     "expr": "rate(mongodb_network_bytesOut{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\", rs_nm=~\"$rs_nm\"}[$__rate_interval]) > 0",
     "legendFormat": "{{instance}} - sent"
    }
   ]
  },
  { "title": "Hardware I/O", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 35 } },
  {
   "title": "Hardware I/O",
   "type": "timeseries",
   "description": "The rate of read and write I/O's processed by this node.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "rate(hardware_disk_metrics_read_count{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - reads"
    },
    {
     "expr": "hardware_disk_metrics_write_count{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - writes"
    }
   ]
  },
  {
   "title": "Hardware I/O wait time / $__interval",
   "type": "timeseries",
   "description": "The amount of time the node has spent waiting for read and write I/O's to process.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "increase(hardware_disk_metrics_read_time_milliseconds{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{instance}} - read"
    },
    {
     "expr": "increase(hardware_disk_metrics_write_time_milliseconds{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{instance}} - write"
    }
   ]
  }
 ]
}