{
 "title": "MongoDB Atlas sharding overview",
 "description": "Overview of MongoDB Atlas sharding metrics.",
 "tags": [ "mongodb-atlas-mixin" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(mongodb_network_bytesIn{}, job)"
   },
   {
    "name": "cl_name",
    "label": "Atlas cluster",
    "query": "label_values(mongodb_network_bytesIn{job=~\"$job\"}, cl_name)"
   },
   {
    "name": "instance",
    "label": "Node",
    "query": "label_values(mongodb_network_bytesIn{job=~\"$job\",cl_name=~\"$cl_name\"}, instance)"
   },
   {
    "name": "rs_nm",
    "label": "Replica set",
    "query": "label_values(mongodb_network_bytesIn, rs_nm)"
   }
  ]
 },
 "panels": [
  { "title": "General sharding statistics", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Stale configs / $__interval",
   "type": "timeseries",
   "description": "Number of times that a thread hit a stale config exception and triggered a metadata refresh.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(mongodb_shardingStatistics_countStaleConfigErrors{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\", rs_nm=~\"$rs_nm\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Chunk migrations / $__interval",
   "type": "timeseries",
   "description": "Chunk migration frequency for this node.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(mongodb_shardingStatistics_countRecipientMoveChunkStarted{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\", rs_nm=~\"$rs_nm\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Docs cloned / $__interval",
   "type": "timeseries",
   "description": "The number of documents cloned on this node when it acted as primary for the donor and acted as primary for the recipient.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(mongodb_shardingStatistics_countDocsClonedOnDonor{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\", rs_nm=~\"$rs_nm\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - donor"
    },
    {
     "expr": "increase(mongodb_shardingStatistics_countDocsClonedOnRecipient{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\", rs_nm=~\"$rs_nm\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{instance}} - recipient"
    }
   ]
  },
  {
   "title": "Critical section time / $__interval",
   "type": "timeseries",
   "description": "The time taken by the catch-up and update metadata phases of a range migration, by this node.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "increase(mongodb_shardingStatistics_totalCriticalSectionTimeMillis{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\", rs_nm=~\"$rs_nm\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Catalog cache", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 17 } },
  {
   "title": "Refreshes started / $__interval",
   "type": "timeseries",
   "description": "The number of incremental and full refreshes that have started.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(mongodb_shardingStatistics_catalogCache_countIncrementalRefreshesStarted{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\", rs_nm=~\"$rs_nm\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - incremental"
    },
    {
     "expr": "rate(mongodb_shardingStatistics_catalogCache_countFullRefreshesStarted{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\", rs_nm=~\"$rs_nm\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - full"
    }
   ]
  },
  {
   "title": "Refreshes failed / $__interval",
   "type": "timeseries",
   "description": "The number of full and incremental refreshes that have failed.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(mongodb_shardingStatistics_catalogCache_countFailedRefreshes{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\", rs_nm=~\"$rs_nm\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cache stale configs / $__interval",
   "type": "timeseries",
   "description": "The number of times that a thread hit a stale config exception for the catalog cache and triggered a metadata refresh.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(mongodb_shardingStatistics_catalogCache_countStaleConfigErrors{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\", rs_nm=~\"$rs_nm\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cache entries / $__interval",
   "type": "timeseries",
   "description": "The number of database and collection entries that are currently in the catalog cache.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(mongodb_shardingStatistics_catalogCache_numDatabaseEntries{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\", rs_nm=~\"$rs_nm\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - database"
    },
    {
     "expr": "rate(mongodb_shardingStatistics_catalogCache_numCollectionEntries{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\", rs_nm=~\"$rs_nm\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - collection"
    }
   ]
  },
  {
   "title": "Cache refresh time / $__interval",
   "type": "timeseries",
   "description": "The amount of time that threads had to wait for a refresh of the metadata.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(mongodb_shardingStatistics_catalogCache_totalRefreshWaitTimeMicros{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\", rs_nm=~\"$rs_nm\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cache operations blocked",
   "type": "timeseries",
   "description": "The rate of operations that are blocked by a refresh of the catalog cache. Specific to mongos nodes found under replica set \"none\".",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(mongodb_shardingStatistics_catalogCache_operationsBlockedByRefresh_countAllOperations{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\", rs_nm=~\"$rs_nm\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Shard operations", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 34 } },
  {
   "title": "All shards",
   "type": "timeseries",
   "description": "The rate of CRUD operations and aggregation commands run that targeted all shards. Specific to mongos nodes found under replica set \"none\".",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(mongodb_shardingStatistics_numHostsTargeted_find_allShards{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\", rs_nm=~\"$rs_nm\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - find"
    },
    {
     "expr": "rate(mongodb_shardingStatistics_numHostsTargeted_insert_allShards{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\", rs_nm=~\"$rs_nm\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - insert"
    },
    {
     "expr": "rate(mongodb_shardingStatistics_numHostsTargeted_update_allShards{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\", rs_nm=~\"$rs_nm\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - update"
    },
    {
     "expr": "rate(mongodb_shardingStatistics_numHostsTargeted_delete_allShards{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\", rs_nm=~\"$rs_nm\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - delete"
    },
    {
     "expr": "rate(mongodb_shardingStatistics_numHostsTargeted_aggregate_allShards{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\", rs_nm=~\"$rs_nm\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - aggregate"
    }
   ]
  },
  {
   "title": "Many shards",
   "type": "timeseries",
   "description": "The rate of CRUD operations and aggregation commands run that targeted more than 1 shard. Specific to mongos nodes found under replica set \"none\".",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(mongodb_shardingStatistics_numHostsTargeted_find_manyShards{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\", rs_nm=~\"$rs_nm\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - find"
    },
    {
     "expr": "rate(mongodb_shardingStatistics_numHostsTargeted_insert_manyShards{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\", rs_nm=~\"$rs_nm\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - insert"
    },
    {
     "expr": "rate(mongodb_shardingStatistics_numHostsTargeted_update_manyShards{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\", rs_nm=~\"$rs_nm\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - update"
    },
    {
     "expr": "rate(mongodb_shardingStatistics_numHostsTargeted_delete_manyShards{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\", rs_nm=~\"$rs_nm\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - delete"
    },
    {
     "expr": "rate(mongodb_shardingStatistics_numHostsTargeted_aggregate_manyShards{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\", rs_nm=~\"$rs_nm\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - aggregate"
    }
   ]
  },
  {
   "title": "One shard",
   "type": "timeseries",
   "description": "The rate of CRUD operations and aggregation commands run that targeted 1 shard. Specific to mongos nodes found under replica set \"none\".",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(mongodb_shardingStatistics_numHostsTargeted_find_oneShard{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\", rs_nm=~\"$rs_nm\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - find"
    },
    {
     "expr": "rate(mongodb_shardingStatistics_numHostsTargeted_insert_oneShard{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\", rs_nm=~\"$rs_nm\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - insert"
    },
    {
     "expr": "rate(mongodb_shardingStatistics_numHostsTargeted_update_oneShard{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\", rs_nm=~\"$rs_nm\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - update"
    },
    {
     "expr": "rate(mongodb_shardingStatistics_numHostsTargeted_delete_oneShard{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\", rs_nm=~\"$rs_nm\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - delete"
    },
    {
     "expr": "rate(mongodb_shardingStatistics_numHostsTargeted_aggregate_oneShard{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\", rs_nm=~\"$rs_nm\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - aggregate"
    }
   ]
  },
  {
   "title": "Unsharded",
   "type": "timeseries",
   "description": "The rate of CRUD operations and aggregation commands run on an unsharded collection. Specific to mongos nodes found under replica set \"none\".",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(mongodb_shardingStatistics_numHostsTargeted_find_unsharded{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\", rs_nm=~\"$rs_nm\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - find"
    },
    {
     "expr": "rate(mongodb_shardingStatistics_numHostsTargeted_insert_unsharded{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\", rs_nm=~\"$rs_nm\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - insert"
    },
    {
     "expr": "rate(mongodb_shardingStatistics_numHostsTargeted_update_unsharded{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\", rs_nm=~\"$rs_nm\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - update"
    },
    {
     "expr": "rate(mongodb_shardingStatistics_numHostsTargeted_delete_unsharded{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\", rs_nm=~\"$rs_nm\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - delete"
    },
    {
     "expr": "rate(mongodb_shardingStatistics_numHostsTargeted_aggregate_unsharded{job=~\"$job\",cl_name=~\"$cl_name\",instance=~\"$instance\", rs_nm=~\"$rs_nm\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - aggregate"
    }
   ]
  }
 ]
}