{
 "title": "Varnish overview",
 "tags": [ "varnish-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(varnish_main_sessions{}, job)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(varnish_main_sessions{job=~\"$job\"}, cluster)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(varnish_main_sessions{job=~\"$job\",cluster=~\"$cluster\"}, instance)"
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" }
  ]
 },
 "panels": [
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Cache hit rate",
   "type": "gauge",
   "description": "Rate of cache hits to misses.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg((rate(varnish_main_cache_hit{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__rate_interval]) / clamp_min(rate(varnish_main_cache_hit{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__rate_interval]) + rate(varnish_main_cache_miss{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__rate_interval]), 1))) by () * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Frontend requests",
   "type": "stat",
   "description": "The rate of requests sent to the Varnish Cache frontend.",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "req" } },
   "targets": [
    {
     "expr": "rate(varnish_main_client_req{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Backend requests",
   "type": "stat",
   "description": "The requests sent to the Varnish Cache backends over the last $__interval.",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "req" } },
   "targets": [
    {
     "expr": "sum by () (rate(varnish_main_backend_req{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Sessions rate",
   "type": "stat",
   "description": "The rate of total sessions created in the Varnish Cache instance.",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "/ sec" } },
   "targets": [
    {
     "expr": "sum by () (irate(varnish_main_sessions_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cache hits",
   "type": "stat",
   "description": "The rate of cache hits.",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by () (rate(varnish_main_cache_hit{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cache hit pass",
   "type": "stat",
   "description": "Rate of cache hits for pass objects (fulfilled requests that are not cached).",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by () (rate(varnish_main_cache_hitpass{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Session queue length",
   "type": "stat",
   "description": "Length of session queue waiting for threads.",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by () (varnish_main_thread_queue_len{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Pools",
   "type": "stat",
   "description": "Number of thread pools.",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by () (varnish_main_pools{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 5 } },
  {
   "title": "Backend connections",
   "type": "timeseries",
   "description": "Rate of recycled, reused, busy, unhealthy, and accepted backend connections by Varnish Cache.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "conn" } },
   "targets": [
    {
     "expr": "increase(varnish_main_backend_conn{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{instance}} - Accepted"
    },
    {
     "expr": "increase(varnish_main_backend_recycle{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{instance}} - Recycled"
    },
    {
     "expr": "increase(varnish_main_backend_reuse{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{instance}} - Reused"
    },
    {
     "expr": "increase(varnish_main_backend_busy{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{instance}} - Busy"
    },
    {
     "expr": "increase(varnish_main_backend_unhealthy{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{instance}} - Unhealthy"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "timeseries",
   "description": "Rate of new connected, queued, and dropped sessions.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "sess" } },
   "targets": [
    {
     "expr": "increase(varnish_main_sessions{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",type=\"conn\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{instance}} - Connected"
    },
    {
     "expr": "increase(varnish_main_sessions{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",type=\"queued\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{instance}} - Queued"
    },
    {
     "expr": "increase(varnish_main_sessions{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",type=\"dropped\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{instance}} - Dropped"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "description": "Rate of frontend and backend requests received.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "req" } },
   "targets": [
    {
     "expr": "increase(varnish_main_client_req{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{instance}} - Frontend"
    },
    {
     "expr": "increase(varnish_main_backend_req{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{instance}} - Backend"
    }
   ]
  },
  {
   "title": "Cache hit ratio",
   "type": "timeseries",
   "description": "Ratio of cache hits to cache misses.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (instance, job) ((rate(varnish_main_cache_hit{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__rate_interval]) / clamp_min(rate(varnish_main_cache_hit{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__rate_interval]) + rate(varnish_main_cache_miss{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__rate_interval]), 1))) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory used",
   "type": "timeseries",
   "description": "Bytes allocated from Varnish Cache storage.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "varnish_sma_g_bytes{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",type=\"s0\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cache events",
   "type": "timeseries",
   "description": "Rate of expired and LRU (least recently used) nuked objects.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "increase(varnish_main_n_expired{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{instance}} - Expired"
    },
    {
     "expr": "increase(varnish_main_n_lru_nuked{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{instance}} - Nuked"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "description": "Rate for the response bytes of header and body for frontend and backends.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "increase(varnish_main_s_resp_hdrbytes{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{instance}} - Frontend header"
    },
    {
     "expr": "increase(varnish_main_s_resp_bodybytes{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{instance}} - Frontend body"
    },
    {
     "expr": "rate(varnish_backend_beresp_hdrbytes{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - {{backend}} - Backend header"
    },
    {
     "expr": "rate(varnish_backend_beresp_bodybytes{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - {{backend}} - Backend body"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "description": "Number of failed, created, limited, and current threads.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(varnish_main_threads_failed{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{instance}} - Failed"
    },
    {
     "expr": "increase(varnish_main_threads_created{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{instance}} - Created"
    },
    {
     "expr": "increase(varnish_main_threads_limited{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{instance}} - Limited"
    },
    {
     "expr": "varnish_main_threads{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - Total"
    }
   ]
  }
 ]
}