{
 "title": "HAProxy / Overview",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "job",
    "query": "label_values(haproxy_process_start_time_seconds, job)"
   },
   {
    "name": "instance",
    "query": "label_values(haproxy_process_start_time_seconds{job=~\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Headline", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Process uptime",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - haproxy_process_start_time_seconds{instance=~\"$instance\",job=~\"$job\"}",
     "refID": "A"
    }
   ]
  },
  {
   "title": "Current connections",
   "type": "stat",
   "description": "Number of active sessions",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "haproxy_process_current_connections{instance=~\"$instance\",job=~\"$job\"}",
     "refID": "A"
    }
   ]
  },
  {
   "title": "Memory allocated",
   "type": "stat",
   "description": "Total amount of memory allocated in pools",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "haproxy_process_pool_allocated_bytes{instance=~\"$instance\",job=~\"$job\"}",
     "refID": "A"
    }
   ]
  },
  {
   "title": "Memory used",
   "type": "stat",
   "description": "Total amount of memory used in pools",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "haproxy_process_pool_used_bytes{instance=~\"$instance\",job=~\"$job\"}",
     "refID": "A"
    }
   ]
  },
  { "title": "Frontend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "haproxy_frontend_status{instance=~\"$instance\",job=~\"$job\"}",
     "refID": "A"
    }
   ]
  },
  { "title": "Backend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "haproxy_backend_status{instance=~\"$instance\",job=~\"$job\"}",
     "refID": "A"
    }
   ]
  },
  { "title": "Configuration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Processes",
   "type": "stat",
   "description": "Configured number of processes",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "haproxy_process_nbproc{instance=~\"$instance\",job=~\"$job\"}",
     "refID": "A"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "stat",
   "description": "Configured number of threads",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 3 },
   "targets": [
    {
     "expr": "haproxy_process_nbthread{instance=~\"$instance\",job=~\"$job\"}",
     "refID": "A"
    }
   ]
  },
  {
   "title": "Connections limit",
   "type": "stat",
   "description": "Configured maximum number of concurrent connections",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 3 },
   "targets": [
    {
     "expr": "haproxy_process_max_connections{instance=~\"$instance\",job=~\"$job\"}",
     "refID": "A"
    }
   ]
  },
  {
   "title": "File descriptors limit",
   "type": "stat",
   "description": "Maximum number of open file descriptors",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 3 },
   "targets": [
    {
     "expr": "haproxy_process_max_fds{instance=~\"$instance\",job=~\"$job\"}",
     "refID": "A"
    }
   ]
  },
  {
   "title": "Socket limit",
   "type": "stat",
   "description": "Maximum number of open sockets",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "haproxy_process_max_sockets{instance=~\"$instance\",job=~\"$job\"}",
     "refID": "A"
    }
   ]
  },
  {
   "title": "Memory limit",
   "type": "stat",
   "description": "Per-process memory limit",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "haproxy_process_max_memory_bytes{instance=~\"$instance\",job=~\"$job\"}",
     "refID": "A"
    }
   ]
  },
  {
   "title": "Pipe limit",
   "type": "stat",
   "description": "Maximum number of pipes",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "haproxy_process_max_pipes{instance=~\"$instance\",job=~\"$job\"}",
     "refID": "A"
    }
   ]
  },
  {
   "title": "Connection rate limit",
   "type": "stat",
   "description": "Maximum number of connections per second",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 7 },
   "targets": [
    {
     "expr": "haproxy_process_limit_connection_rate{instance=~\"$instance\",job=~\"$job\"}",
     "refID": "A"
    }
   ]
  },
  {
   "title": "Session rate limit",
   "type": "stat",
   "description": "Maximum number of sessions per second",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "haproxy_process_limit_session_rate{instance=~\"$instance\",job=~\"$job\"}",
     "refID": "A"
    }
   ]
  },
  {
   "title": "SSL session rate limit",
   "type": "stat",
   "description": "Maximum number of SSL sessions per second",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 11 },
   "targets": [
    {
     "expr": "haproxy_process_limit_ssl_rate{instance=~\"$instance\",job=~\"$job\"}",
     "refID": "A"
    }
   ]
  }
 ]
}