{
 "title": "Squid overview",
 "tags": [ "squid" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(squid_client_http_requests_total{}, job)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(squid_client_http_requests_total{job=~\"$job\"}, cluster)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(squid_client_http_requests_total{job=~\"$job\",cluster=~\"$cluster\"}, instance)"
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" }
  ]
 },
 "panels": [
  { "title": "Client", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Client requests",
   "type": "timeseries",
   "description": "The request rate of client.",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(squid_client_http_requests_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Client request errors",
   "type": "timeseries",
   "description": "The number of client HTTP errors.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "errors/s" } },
   "targets": [
    {
     "expr": "rate(squid_client_http_errors_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Client cache hit ratio",
   "type": "timeseries",
   "description": "The client cache hit ratio.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(rate(squid_client_http_hits_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__rate_interval]) / clamp_min(rate(squid_client_http_requests_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__rate_interval]),1)) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Client request sent throughput",
   "type": "timeseries",
   "description": "The throughput of client HTTP data sent.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "rate(squid_client_http_kbytes_out_kbytes_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Client HTTP received throughput",
   "type": "timeseries",
   "description": "The throughput of client HTTP data received.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "rate(squid_client_http_kbytes_in_kbytes_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Client cache hit throughput",
   "type": "timeseries",
   "description": "The throughput of client cache hit.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "rate(squid_client_http_hit_kbytes_out_bytes_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "HTTP request service time",
   "type": "timeseries",
   "description": "HTTP request service time percentiles.",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "squid_HTTP_Requests_All_50{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}",
     "legendFormat": "50%"
    },
    {
     "expr": "squid_HTTP_Requests_All_75{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}",
     "legendFormat": "75%"
    },
    {
     "expr": "squid_HTTP_Requests_All_95{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}",
     "legendFormat": "95%"
    }
   ]
  },
  {
   "title": "Cache hit service time",
   "type": "timeseries",
   "description": "Cache hits service time percentiles.",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "squid_Cache_Hits_50{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}",
     "legendFormat": "50%"
    },
    {
     "expr": "squid_Cache_Hits_75{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}",
     "legendFormat": "75%"
    },
    {
     "expr": "squid_Cache_Hits_95{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}",
     "legendFormat": "95%"
    }
   ]
  },
  {
   "title": "Cache misses service time",
   "type": "timeseries",
   "description": "Cache misses service time percentiles.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "squid_Cache_Misses_50{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}",
     "legendFormat": "50%"
    },
    {
     "expr": "squid_Cache_Misses_75{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}",
     "legendFormat": "75%"
    },
    {
     "expr": "squid_Cache_Misses_95{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}",
     "legendFormat": "95%"
    }
   ]
  },
  { "title": "Server", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 33 } },
  {
   "title": "Server requests",
   "type": "timeseries",
   "description": "The number of HTTP, FTP, and other server requests.",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(squid_server_ftp_requests_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "FTP"
    },
    {
     "expr": "rate(squid_server_http_requests_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "HTTP"
    },
    {
     "expr": "rate(squid_server_other_requests_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "other"
    }
   ]
  },
  {
   "title": "Server request errors",
   "type": "timeseries",
   "description": "The number of HTTP, FTP, and other server request errors.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "errors/s" } },
   "targets": [
    {
     "expr": "rate(squid_server_ftp_errors_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "FTP"
    },
    {
     "expr": "rate(squid_server_http_errors_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "HTTP"
    },
    {
     "expr": "rate(squid_server_other_errors_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "other"
    }
   ]
  },
  {
   "title": "Server request sent throughput",
   "type": "timeseries",
   "description": "The number of HTTP, FTP, and other server sent throughput.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "rate(squid_server_ftp_kbytes_out_kbytes_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "FTP"
    },
    {
     "expr": "rate(squid_server_http_kbytes_out_kbytes_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "HTTP"
    },
    {
     "expr": "rate(squid_server_other_kbytes_out_kbytes_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "other"
    }
   ]
  },
  {
   "title": "Server object swap",
   "type": "timeseries",
   "description": "The number of objects read from disk and the number of objects saved to disk.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(squid_swap_ins_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - read"
    },
    {
     "expr": "rate(squid_swap_outs_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - saved"
    }
   ]
  },
  {
   "title": "DNS lookup service time",
   "type": "timeseries",
   "description": "DNS lookup service time percentiles",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "squid_DNS_Lookups_50{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}",
     "legendFormat": "50%"
    },
    {
     "expr": "squid_DNS_Lookups_75{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}",
     "legendFormat": "75%"
    },
    {
     "expr": "squid_DNS_Lookups_95{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}",
     "legendFormat": "95%"
    }
   ]
  },
  {
   "title": "Server received throughput",
   "type": "timeseries",
   "description": "The number of HTTP, FTP, and other server throughput.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "rate(squid_server_ftp_kbytes_in_kbytes_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "FTP"
    },
    {
     "expr": "rate(squid_server_http_kbytes_in_kbytes_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "HTTP"
    },
    {
     "expr": "rate(squid_server_other_kbytes_in_kbytes_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "other"
    }
   ]
  }
 ]
}