{
 "title": "SNMP overview",
 "tags": [ "snmp" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values({__name__=~\"sysUpTime\"}, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values({__name__=~\"sysUpTime\",job=~\"$job\"}, instance)"
   },
   {
    "name": "ifName",
    "label": "IfName",
    "query": "label_values({__name__=~\"ifOperStatus\",job=~\"$job\",instance=~\"$instance\"}, ifName)"
   },
   { "name": "adhoc", "label": "Ad hoc filters" },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" }
  ]
 },
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "System name",
   "type": "stat",
   "description": "System name.\n",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job,instance,sysName) (\n  sysName{job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{instance}}: System name"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "description": "System version.\n",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job,instance,version) (\n  label_replace(\n  ciscoImageString{ciscoImageString=~\"CW_VERSION.+\", job=~\"$job\",instance=~\"$instance\"}, \"version\", \"$1\", \"ciscoImageString\", \"CW_VERSION\\\\$(.+)\\\\$\"\n)\n\n)\nor ignoring(version)\nsum by (job,instance,version) (\n  label_replace(sysDescr{sysDescr=~\".+JUNOS.+\", job=~\"$job\",instance=~\"$instance\"}, \"version\", \"$1\", \"sysDescr\", \".+JUNOS (.+?) .+\")\n)\nor ignoring(version)\nsum by (job,instance,version) (\n  label_replace(sysDescr{sysDescr=~\".+Version.+\", job=~\"$job\",instance=~\"$instance\"}, \"version\", \"$1\", \"sysDescr\", \".+Version (.+?) .+\")\n)",
     "legendFormat": "{{instance}}: Version"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "The time since the network management portion of the system was last re-initialized.\n",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "(\n  sum by (job,instance) (\n  sysUpTime{job=~\"$job\",instance=~\"$instance\"}\n)\n)/100",
     "legendFormat": "{{instance}}: Uptime"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "description": "CPU usage.",
   "gridPos": { "h": 5, "w": 7, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (job,instance) (\n  cpmCPUTotal1minRev{job=~\"$job\",instance=~\"$instance\"}\n)\nor\navg by (job,instance) (\n  hrProcessorLoad{hrDeviceType=\"1.3.6.1.2.1.25.3.1.3\",job=~\"$job\",instance=~\"$instance\"}\n)\nor\navg by (job,instance) (\n  jnxOperatingCPU{jnxOperatingContentsIndex=\"9\", job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{instance}}: CPU utilization"
    }
   ]
  },
  {
   "title": "Memory utilization",
   "type": "timeseries",
   "description": "Memory utilization.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (job,instance) (\n  # NX-OS:\n(\n  cpmCPUMemoryUsed{job=~\"$job\",instance=~\"$instance\"}\n  /\n  (cpmCPUMemoryUsed{job=~\"$job\",instance=~\"$instance\"} + cpmCPUMemoryFree{job=~\"$job\",instance=~\"$instance\"}) * 100\n)\nor\n# cisco CISCO-ENHANCED-MEMPOOL-MIB\n# cempMemPoolType=\"10\" - virtual memory, i.e in ASA(v).\n(\n  (\n    cempMemPoolUsed{job=~\"$job\",instance=~\"$instance\"}\n    /\n    (cempMemPoolUsed{job=~\"$job\",instance=~\"$instance\"} + cempMemPoolFree{job=~\"$job\",instance=~\"$instance\"}) * 100\n  ) * on (instance, cempMemPoolIndex, entPhysicalIndex) group_left () \n        (cempMemPoolType{job=~\"$job\",instance=~\"$instance\"} == 10)/10\n)\nor\n# cisco firmwares that supports only CISCO-MEMORY-POOL-MIB\n# ciscoMemoryPoolType=\"1\" - Processor\n(ciscoMemoryPoolUsed{ciscoMemoryPoolType=\"1\", job=~\"$job\",instance=~\"$instance\"}\n/\n(ciscoMemoryPoolUsed{ciscoMemoryPoolType=\"1\", job=~\"$job\",instance=~\"$instance\"} + ciscoMemoryPoolFree{ciscoMemoryPoolType=\"1\", job=~\"$job\",instance=~\"$instance\"}) * 100)\n\n)\nor\navg by (job,instance) (\n  hrStorageUsed{hrStorageDescr!~\".*(?i:(cache|buffer)).*\", hrStorageType=\"1.3.6.1.2.1.25.2.1.2\", job=~\"$job\",instance=~\"$instance\"}/hrStorageSize{hrStorageDescr!~\".*(?i:(cache|buffer)).*\", hrStorageType=\"1.3.6.1.2.1.25.2.1.2\", job=~\"$job\",instance=~\"$instance\"}*100\n\n)\nor\navg by (job,instance) (\n  hrStorageUsed{hrStorageDescr=\"main memory\",hrStorageIndex=\"65536\", job=~\"$job\",instance=~\"$instance\"}/hrStorageSize{hrStorageDescr=\"main memory\",hrStorageIndex=\"65536\", job=~\"$job\",instance=~\"$instance\"}*100\n\n)\nor\navg by (job,instance) (\n  jnxOperatingBuffer{jnxOperatingContentsIndex=\"9\", job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{instance}}: Memory utilization"
    }
   ]
  },
  { "title": "Network interfaces", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 6 } },
  {
   "title": "Interfaces",
   "type": "table",
   "description": "status (sum): Interface operational status(ifOperStatus).\n  \n\nadmin status (sum): The desired state of the interface. \nThe testing(3) state indicates that no operational\npackets can be passed.\n  \n\nSpeed (sum): An estimate of the interface's current bandwidth in units of 1,000,000 bits per second.\nIf this object reports a value of `n' then the speed of the interface is somewhere in the range of `n-500,000' to `n+499,999'.\nFor interfaces which do not vary in bandwidth or for those where no accurate estimation can be made, this object should contain the nominal bandwidth.\nFor a sub-layer which has no concept of bandwidth, this object should be zero.\n  \n\nType (sum): The type of interface, distinguished according to the physical/link protocol(s) immediately `below' the network layer in the protocol stack.\n  \n\npromiscuous mode (sum): This object has a value of false(2) if this interface only accepts packets/frames that are addressed to this station. \nThis object has a value of true(1) when the station accepts all packets/frames transmitted on the media.\nThe value true(1) is only legal on certain types of media. \nIf legal, setting this object to a value of true(1) may require the interface to be reset before becoming effective. \nThe value of ifPromiscuousMode does not affect the reception of broadcast and multicast packets/frames by the interface.\n  \n\nconnector (sum): This object has the value 'true(1)' if the interface sublayer has a physical connector and the value 'false(2)' otherwise.\n  \n\nMTU (sum): Maximum transmission unit (MTU).\n  \n\nLast change (sum): Interface last change.\n  \n\nMAC (sum): MAC.\n",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (job,instance,ifName,ifAlias,ifDescr) (\n  ifOperStatus{job=~\"$job\",instance=~\"$instance\",ifName=~\"$ifName\"}\n)",
     "legendFormat": "{{ifName}}: status ({{ifAlias}} {{ifDescr}})"
    },
    {
     "expr": "sum by (job,instance,ifName,ifAlias,ifDescr) (\n  ifAdminStatus{job=~\"$job\",instance=~\"$instance\",ifName=~\"$ifName\"}\n)",
     "legendFormat": "{{ifName}}: admin status ({{ifAlias}} {{ifDescr}})"
    },
    {
     "expr": "(\n  sum by (job,instance,ifName,ifAlias,ifDescr) (\n  ifHighSpeed{job=~\"$job\",instance=~\"$instance\",ifName=~\"$ifName\"}\n)\n)*1000000",
     "legendFormat": "{{ifName}}: Speed ({{ifAlias}} {{ifDescr}})"
    },
    {
     "expr": "sum by (job,instance,ifName,ifAlias,ifDescr,ifType) (\n  ifType_info{job=~\"$job\",instance=~\"$instance\",ifName=~\"$ifName\"}\n)",
     "legendFormat": "{{ifName}}: Type ({{ifAlias}} {{ifDescr}})"
    },
    {
     "expr": "sum by (job,instance,ifName,ifAlias,ifDescr) (\n  ifPromiscuousMode{job=~\"$job\",instance=~\"$instance\",ifName=~\"$ifName\"}\n)",
     "legendFormat": "{{ifName}}: promiscuous mode ({{ifAlias}} {{ifDescr}})"
    },
    {
     "expr": "sum by (job,instance,ifName,ifAlias,ifDescr) (\n  ifConnectorPresent{job=~\"$job\",instance=~\"$instance\",ifName=~\"$ifName\"}\n)",
     "legendFormat": "{{ifName}}: connector ({{ifAlias}} {{ifDescr}})"
    },
    {
     "expr": "sum by (job,instance,ifName,ifAlias,ifDescr) (\n  ifMtu{job=~\"$job\",instance=~\"$instance\",ifName=~\"$ifName\"}\n)",
     "legendFormat": "{{ifName}}: MTU ({{ifAlias}} {{ifDescr}})"
    },
    {
     "expr": "# ignore when ifLastCHange == 0 as invalid\nsum by (job,instance,ifName,ifAlias,ifDescr) (\n  (sysUpTime{job=~\"$job\",instance=~\"$instance\"} - on(job,instance) group_right () (ifLastChange{job=~\"$job\",instance=~\"$instance\",ifName=~\"$ifName\"})!=0)\n)/100\n",
     "legendFormat": "{{ifName}}: Last change ({{ifAlias}} {{ifDescr}})"
    },
    {
     "expr": "sum by (job,instance,ifName,ifAlias,ifDescr,ifPhysAddress) (\n  ifPhysAddress{job=~\"$job\",instance=~\"$instance\",ifName=~\"$ifName\"}\n)",
     "legendFormat": "{{ifName}}: MAC ({{ifAlias}} {{ifDescr}})"
    }
   ]
  },
  {
   "title": "Network traffic",
   "type": "timeseries",
   "description": "transmitted (sum): Network interface traffic out.\n  \n\nreceived (sum): Network interface traffic in.\n",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "topk(25,\n  \n  (\n  sum by (job,instance,ifName,ifAlias,ifDescr) (\n  irate(ifHCOutOctets{job=~\"$job\",instance=~\"$instance\",ifName=~\"$ifName\"} [$__rate_interval])\n)\n)*8\n\n# set max limit to workaround for TB-PB/sec spikes when counters are overloaded too quickly on very busy interfaces.\n<100*10^9\n)",
     "legendFormat": "{{ifName}}: transmitted ({{ifAlias}} {{ifDescr}})"
    },
    {
     "expr": "topk(25,\n  \n  (\n  sum by (job,instance,ifName,ifAlias,ifDescr) (\n  irate(ifHCInOctets{job=~\"$job\",instance=~\"$instance\",ifName=~\"$ifName\"}[$__rate_interval])\n)\n)*8\n\n# set max limit to workaround for TB-PB/sec spikes when counters are overloaded too quickly on very busy interfaces.\n<100*10^9\n)",
     "legendFormat": "{{ifName}}: received ({{ifAlias}} {{ifDescr}})"
    }
   ]
  },
  {
   "title": "Network errors",
   "type": "timeseries",
   "description": "errors in (sum): Network interface errors in.\n  \n\nerrors out (sum): Network interface errors out.\n",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "topk(25,\n  (\n  sum by (job,instance,ifName,ifAlias,ifDescr) (\n  irate(ifInErrors{job=~\"$job\",instance=~\"$instance\",ifName=~\"$ifName\"}[$__rate_interval])\n)\n)>0\n)",
     "legendFormat": "{{ifName}}: errors in ({{ifAlias}} {{ifDescr}})"
    },
    {
     "expr": "topk(25,\n  (\n  sum by (job,instance,ifName,ifAlias,ifDescr) (\n  irate(ifOutErrors{job=~\"$job\",instance=~\"$instance\",ifName=~\"$ifName\"}[$__rate_interval])\n)\n)>0\n)",
     "legendFormat": "{{ifName}}: errors out ({{ifAlias}} {{ifDescr}})"
    }
   ]
  },
  {
   "title": "Dropped packets",
   "type": "timeseries",
   "description": "dropped in (sum): Network interface discards in.\n  \n\ndropped out (sum): Network interface discards out.\n  \n\nunknown dropped in (sum): The number of packets received via the interface\nwhich were discarded because of an unknown or\nunsupported protocol.\n",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "topk(25,\n  (\n  sum by (job,instance,ifName,ifAlias,ifDescr) (\n  irate(ifInDiscards{job=~\"$job\",instance=~\"$instance\",ifName=~\"$ifName\"}[$__rate_interval])\n)\n)>0\n)",
     "legendFormat": "{{ifName}}: dropped in ({{ifAlias}} {{ifDescr}})"
    },
    {
     "expr": "topk(25,\n  (\n  sum by (job,instance,ifName,ifAlias,ifDescr) (\n  irate(ifOutDiscards{job=~\"$job\",instance=~\"$instance\",ifName=~\"$ifName\"}[$__rate_interval])\n)\n)>0\n)",
     "legendFormat": "{{ifName}}: dropped out ({{ifAlias}} {{ifDescr}})"
    },
    {
     "expr": "topk(25,\n  (\n  sum by (job,instance,ifName,ifAlias,ifDescr) (\n  irate(ifInUnknownProtos{job=~\"$job\",instance=~\"$instance\",ifName=~\"$ifName\"}[$__rate_interval])\n)\n)>0\n)",
     "legendFormat": "{{ifName}}: unknown dropped in ({{ifAlias}} {{ifDescr}})"
    }
   ]
  },
  {
   "title": "Unicast",
   "type": "timeseries",
   "description": "unicast in (sum): Network interface unicast packets in.\n  \n\nunicast out (sum): Network interface unicast packets out.\n",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "topk(25,\n  (\n  sum by (job,instance,ifName,ifAlias,ifDescr) (\n  irate(ifHCInUcastPkts{job=~\"$job\",instance=~\"$instance\",ifName=~\"$ifName\"}[$__rate_interval])\n)\n)>0\n)",
     "legendFormat": "{{ifName}}: unicast in ({{ifAlias}} {{ifDescr}})"
    },
    {
     "expr": "topk(25,\n  (\n  sum by (job,instance,ifName,ifAlias,ifDescr) (\n  irate(ifHCOutUcastPkts{job=~\"$job\",instance=~\"$instance\",ifName=~\"$ifName\"}[$__rate_interval])\n)\n)>0\n)",
     "legendFormat": "{{ifName}}: unicast out ({{ifAlias}} {{ifDescr}})"
    }
   ]
  },
  {
   "title": "Broadcast",
   "type": "timeseries",
   "description": "broadcast in (sum): Network interface broadcast packets in.\n  \n\nbroadcast out (sum): 'Network interface broadcast packets out.',\n",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "topk(25,\n  (\n  sum by (job,instance,ifName,ifAlias,ifDescr) (\n  irate(ifHCInBroadcastPkts{job=~\"$job\",instance=~\"$instance\",ifName=~\"$ifName\"}[$__rate_interval])\n)\n)>0\n)",
     "legendFormat": "{{ifName}}: broadcast in ({{ifAlias}} {{ifDescr}})"
    },
    {
     "expr": "topk(25,\n  (\n  sum by (job,instance,ifName,ifAlias,ifDescr) (\n  irate(ifHCOutBroadcastPkts{job=~\"$job\",instance=~\"$instance\",ifName=~\"$ifName\"}[$__rate_interval])\n)\n)>0\n)",
     "legendFormat": "{{ifName}}: broadcast out ({{ifAlias}} {{ifDescr}})"
    }
   ]
  },
  {
   "title": "Multicast",
   "type": "timeseries",
   "description": "multicast in (sum): Network interface multicast packets in.\n  \n\nmulticast out (sum): Network interface multicast packets out.\n",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "topk(25,\n  (\n  sum by (job,instance,ifName,ifAlias,ifDescr) (\n  irate(ifHCInMulticastPkts{job=~\"$job\",instance=~\"$instance\",ifName=~\"$ifName\"}[$__rate_interval])\n)\n)>0\n)",
     "legendFormat": "{{ifName}}: multicast in ({{ifAlias}} {{ifDescr}})"
    },
    {
     "expr": "topk(25,\n  (\n  sum by (job,instance,ifName,ifAlias,ifDescr) (\n  irate(ifHCOutMulticastPkts{job=~\"$job\",instance=~\"$instance\",ifName=~\"$ifName\"}[$__rate_interval])\n)\n)>0\n)",
     "legendFormat": "{{ifName}}: multicast out ({{ifAlias}} {{ifDescr}})"
    }
   ]
  },
  {
   "title": "FRU (Components)",
   "type": "row",
   "gridPos": { "h": 1, "w": 0, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "FRU status",
     "type": "table",
     "description": "FRU status (sum): Field replaceable unit status  \n",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "(\n  sum by (job,instance,entPhysicalName,cefcFRUPowerOperStatus) (\n  cefcFRUPowerOperStatus{job=~\"$job\",instance=~\"$instance\"}\n)\n)!=0",
       "legendFormat": "{{instance}}: FRU status ({{entPhysicalName}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Fibre channel",
   "type": "row",
   "gridPos": { "h": 1, "w": 0, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "FC buffer-to-buffer credit",
     "type": "timeseries",
     "description": "credit receive (sum): The current value of receive buffer-to-buffer credits for this port.\n  \n\ncredit transmit (sum): The current value of transmit buffer-to-buffer credits for this port.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "topk(25,\n  sum by (job,instance,ifName,ifAlias,ifDescr) (\n  fcIfCurrRxBbCredit{job=~\"$job\",instance=~\"$instance\",ifName=~\"$ifName\"}\n)\n)",
       "legendFormat": "{{ifName}}: credit receive ({{ifAlias}} {{ifDescr}})"
      },
      {
       "expr": "topk(25,\n  sum by (job,instance,ifName,ifAlias,ifDescr) (\n  fcIfCurrTxBbCredit{job=~\"$job\",instance=~\"$instance\",ifName=~\"$ifName\"}\n)\n)",
       "legendFormat": "{{ifName}}: credit transmit ({{ifAlias}} {{ifDescr}})"
      }
     ]
    },
    {
     "title": "FC errors",
     "type": "timeseries",
     "description": "fcIfTxWaitCount (sum): The number of times the FC-port waited due to lack of transmit credits.\n  \n\nfcIfFramesDiscard (sum): The number of frames discarded by the FC-port.\n  \n\nfcIfTxWtAvgBBCreditTransitionToZero (sum): fcIfTxWtAvgBBCreditTransitionToZero increments if the credit\navailable is zero for 100 ms.\n  \n\nfcHCIfBBCreditTransistionFromZero (sum): fcHCIfBBCreditTransistionFromZero increments if the transmit b2b\ncredit is zero.\n  \n\nfcHCIfBBCreditTransistionToZero (sum): fcHCIfBBCreditTransistionToZero increments if the receive b2b\ncredit is zero.\n  \n\nfcIfInvalidCrcs (sum): The number of invalid CRCs detected by the FC-Port.\n  \n\nfcIfInvalidTxWords (sum): The number of invalid transmission words detected by the FC-Port.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "topk(25,\n  sum by (job,instance,ifName,ifAlias,ifDescr) (\n  irate(fcIfTxWaitCount{job=~\"$job\",instance=~\"$instance\",ifName=~\"$ifName\"}[$__rate_interval])\n)\n)",
       "legendFormat": "{{ifName}}: fcIfTxWaitCount ({{ifAlias}} {{ifDescr}})"
      },
      {
       "expr": "topk(25,\n  sum by (job,instance,ifName,ifAlias,ifDescr) (\n  irate(fcIfFramesDiscard{job=~\"$job\",instance=~\"$instance\",ifName=~\"$ifName\"}[$__rate_interval])\n)\n)",
       "legendFormat": "{{ifName}}: fcIfFramesDiscard ({{ifAlias}} {{ifDescr}})"
      },
      {
       "expr": "topk(25,\n  sum by (job,instance,ifName,ifAlias,ifDescr) (\n  irate(fcIfTxWtAvgBBCreditTransitionToZero{job=~\"$job\",instance=~\"$instance\",ifName=~\"$ifName\"}[$__rate_interval])\n)\n)",
       "legendFormat": "{{ifName}}: fcIfTxWtAvgBBCreditTransitionToZero ({{ifAlias}} {{ifDescr}})"
      },
      {
       "expr": "topk(25,\n  sum by (job,instance,ifName,ifAlias,ifDescr) (\n  irate(fcHCIfBBCreditTransistionFromZero{job=~\"$job\",instance=~\"$instance\",ifName=~\"$ifName\"}[$__rate_interval])\n)\n)",
       "legendFormat": "{{ifName}}: fcHCIfBBCreditTransistionFromZero ({{ifAlias}} {{ifDescr}})"
      },
      {
       "expr": "topk(25,\n  sum by (job,instance,ifName,ifAlias,ifDescr) (\n  irate(fcHCIfBBCreditTransistionToZero{job=~\"$job\",instance=~\"$instance\",ifName=~\"$ifName\"}[$__rate_interval])\n)\n)",
       "legendFormat": "{{ifName}}: fcHCIfBBCreditTransistionToZero ({{ifAlias}} {{ifDescr}})"
      },
      {
       "expr": "topk(25,\n  sum by (job,instance,ifName,ifAlias,ifDescr) (\n  irate(fcIfInvalidCrcs{job=~\"$job\",instance=~\"$instance\",ifName=~\"$ifName\"}[$__rate_interval])\n)\n)",
       "legendFormat": "{{ifName}}: fcIfInvalidCrcs ({{ifAlias}} {{ifDescr}})"
      },
      {
       "expr": "topk(25,\n  sum by (job,instance,ifName,ifAlias,ifDescr) (\n  irate(fcIfInvalidTxWords{job=~\"$job\",instance=~\"$instance\",ifName=~\"$ifName\"}[$__rate_interval])\n)\n)",
       "legendFormat": "{{ifName}}: fcIfInvalidTxWords ({{ifAlias}} {{ifDescr}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Sensors",
   "type": "row",
   "gridPos": { "h": 1, "w": 0, "x": 0, "y": 59 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temperature",
     "type": "timeseries",
     "description": "Temperature sensor.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "(\n  avg by (job,instance) (\n  mtxrHlTemperature{job=~\"$job\",instance=~\"$instance\"}\n)\n)/10\nor\n(\n  avg by (job,instance,jnxOperatingDescr) (\n  jnxOperatingTemp{job=~\"$job\",instance=~\"$instance\"}\n)\n)!=0\nor\navg by (job,instance,entPhysicalName) (\n  # https://www.ietf.org/rfc/rfc3433.html\n# entSensorPrecision:\n# If an object of this type contains a value in the range 1 to\n# 9, it represents the number of decimal places in the\n# fractional part of an associated EntitySensorValue fixed-\n# point number.\n# If an object of this type contains a value in the range -8\n# to -1, it represents the number of accurate digits in the\n# associated EntitySensorValue fixed-point number.\n# entSensorScale\n#     SYNTAX INTEGER {\n#         yocto(1),   -- 10^-24\n#         zepto(2),   -- 10^-21\n#         atto(3),    -- 10^-18\n#         femto(4),   -- 10^-15\n#         pico(5),    -- 10^-12\n#         nano(6),    -- 10^-9\n#         micro(7),   -- 10^-6\n#         milli(8),   -- 10^-3\n#         units(9),   -- 10^0\n#         kilo(10),   -- 10^3\n#         mega(11),   -- 10^6\n#         giga(12),   -- 10^9\n#         tera(13),   -- 10^12\n#         exa(14),    -- 10^15\n#         peta(15),   -- 10^18\n#         zetta(16),  -- 10^21\n#         yotta(17)   -- 10^24\n#     }\n(\n  entSensorValue{entSensorScale=\"9\", entSensorType=\"8\", entPhysicalName!~\".+(\\\\d+/\\\\d+(/\\\\d+)?).*\", job=~\"$job\",instance=~\"$instance\"}\n  *10^-entSensorPrecision{job=~\"$job\",instance=~\"$instance\"}\n  or\n  entSensorValue{entSensorScale=\"8\", entSensorType=\"8\", entPhysicalName!~\".+(\\\\d+/\\\\d+(/\\\\d+)?).*\", job=~\"$job\",instance=~\"$instance\"}\n  *10^-3\n  *10^-entSensorPrecision{job=~\"$job\",instance=~\"$instance\"}\n  or \n  entSensorValue{entSensorScale=\"7\", entSensorType=\"8\", entPhysicalName!~\".+(\\\\d+/\\\\d+(/\\\\d+)?).*\", job=~\"$job\",instance=~\"$instance\"}\n  *10^-6\n  *10^-entSensorPrecision{job=~\"$job\",instance=~\"$instance\"}\n)\n\n)",
       "legendFormat": "{{entPhysicalName}}{{jnxOperatingDescr}}"
      }
     ]
    },
    {
     "title": "DC voltage",
     "type": "timeseries",
     "description": "DC voltage sensor.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "targets": [
      {
       "expr": "(\n  avg by (job,instance) (\n  mtxrHlVoltage{job=~\"$job\",instance=~\"$instance\"}\n)\n)/10\nor\navg by (job,instance,entPhysicalName) (\n  (entSensorValue{entSensorType=\"4\", entSensorScale=\"9\", job=~\"$job\",instance=~\"$instance\"}\n*10^-entSensorPrecision{entSensorType=\"4\", job=~\"$job\",instance=~\"$instance\"}\nor \nentSensorValue{entSensorType=\"4\", entSensorScale=\"8\", job=~\"$job\",instance=~\"$instance\"}\n*10^-3\n*10^-entSensorPrecision{entSensorType=\"4\", job=~\"$job\",instance=~\"$instance\"}\nor \nentSensorValue{entSensorType=\"4\", entSensorScale=\"7\", job=~\"$job\",instance=~\"$instance\"}\n*10^-6\n*10^-entSensorPrecision{entSensorType=\"4\", job=~\"$job\",instance=~\"$instance\"})\n\n)",
       "legendFormat": "{{entPhysicalName}}"
      }
     ]
    },
    {
     "title": "Power",
     "type": "timeseries",
     "description": "Power used in Watts.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "avg by (job,instance) (\n  mtxrHlPower{job=~\"$job\",instance=~\"$instance\"}\n)\nor\navg by (job,instance,entPhysicalName) (\n  (entSensorValue{entSensorType=\"6\", entSensorScale=\"9\", job=~\"$job\",instance=~\"$instance\"}\n*10^-entSensorPrecision{entSensorType=\"6\", job=~\"$job\",instance=~\"$instance\"}\nor \nentSensorValue{entSensorType=\"6\", entSensorScale=\"8\", job=~\"$job\",instance=~\"$instance\"}\n*10^-3\n*10^-entSensorPrecision{entSensorType=\"6\", job=~\"$job\",instance=~\"$instance\"}\nor \nentSensorValue{entSensorType=\"6\", entSensorScale=\"7\", job=~\"$job\",instance=~\"$instance\"}\n*10^-6\n*10^-entSensorPrecision{entSensorType=\"6\", job=~\"$job\",instance=~\"$instance\"})\n\n)",
       "legendFormat": "{{entPhysicalName}}"
      }
     ]
    },
    {
     "title": "Receive/Transmit power",
     "type": "timeseries",
     "description": "Receive/Transmit power.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "dBm" } },
     "targets": [
      {
       "expr": "avg by (job,instance,entPhysicalName) (\n  (entSensorValue{entSensorType=\"14\", entSensorScale=\"9\", job=~\"$job\",instance=~\"$instance\"}\n*10^-entSensorPrecision{entSensorType=\"14\", job=~\"$job\",instance=~\"$instance\"}\nor \nentSensorValue{entSensorType=\"14\", entSensorScale=\"8\", job=~\"$job\",instance=~\"$instance\"}\n*10^-3\n*10^-entSensorPrecision{entSensorType=\"14\", job=~\"$job\",instance=~\"$instance\"}\nor \nentSensorValue{entSensorType=\"14\", entSensorScale=\"7\", job=~\"$job\",instance=~\"$instance\"}\n*10^-6\n*10^-entSensorPrecision{entSensorType=\"14\", job=~\"$job\",instance=~\"$instance\"})\n\n)",
       "legendFormat": "{{entPhysicalName}}"
      }
     ]
    },
    {
     "title": "Fan speed",
     "type": "timeseries",
     "description": "Fan speed.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "rotrpm" } },
     "targets": [
      {
       "expr": "avg by (job,instance,entPhysicalName) (\n  (entSensorValue{entSensorType=\"10\", entSensorScale=\"9\", job=~\"$job\",instance=~\"$instance\"}\n*10^-entSensorPrecision{entSensorType=\"10\", job=~\"$job\",instance=~\"$instance\"}\nor \nentSensorValue{entSensorType=\"10\", entSensorScale=\"8\", job=~\"$job\",instance=~\"$instance\"}\n*10^-3\n*10^-entSensorPrecision{entSensorType=\"10\", job=~\"$job\",instance=~\"$instance\"}\nor \nentSensorValue{entSensorType=\"10\", entSensorScale=\"7\", job=~\"$job\",instance=~\"$instance\"}\n*10^-6\n*10^-entSensorPrecision{entSensorType=\"10\", job=~\"$job\",instance=~\"$instance\"})\n\n)",
       "legendFormat": "{{entPhysicalName}}"
      }
     ]
    }
   ]
  }
 ]
}