{
 "title": "SNMP fleet overview",
 "tags": [ "snmp" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values({__name__=~\"ifOperStatus\"}, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values({__name__=~\"ifOperStatus\",job=~\"$job\"}, instance)"
   },
   { "name": "adhoc", "label": "Ad hoc filters" },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" }
  ]
 },
 "panels": [
  {
   "title": "Network devices",
   "type": "table",
   "description": "Network devices overview.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count by (job,instance) (\n  ifOperStatus{job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{instance}}: Interfaces"
    },
    {
     "expr": "sum by (job,instance,sysName) (\n  sysName{job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{instance}}: System name"
    },
    {
     "expr": "sum by (job,instance,version) (\n  label_replace(\n  ciscoImageString{ciscoImageString=~\"CW_VERSION.+\", job=~\"$job\",instance=~\"$instance\"}, \"version\", \"$1\", \"ciscoImageString\", \"CW_VERSION\\\\$(.+)\\\\$\"\n)\n\n)\nor ignoring(version)\nsum by (job,instance,version) (\n  label_replace(sysDescr{sysDescr=~\".+JUNOS.+\", job=~\"$job\",instance=~\"$instance\"}, \"version\", \"$1\", \"sysDescr\", \".+JUNOS (.+?) .+\")\n)\nor ignoring(version)\nsum by (job,instance,version) (\n  label_replace(sysDescr{sysDescr=~\".+Version.+\", job=~\"$job\",instance=~\"$instance\"}, \"version\", \"$1\", \"sysDescr\", \".+Version (.+?) .+\")\n)",
     "legendFormat": "{{instance}}: Version"
    },
    {
     "expr": "(\n  sum by (job,instance) (\n  sysUpTime{job=~\"$job\",instance=~\"$instance\"}\n)\n)/100",
     "legendFormat": "{{instance}}: Uptime"
    },
    {
     "expr": "avg by (job,instance) (\n  cpmCPUTotal1minRev{job=~\"$job\",instance=~\"$instance\"}\n)\nor\navg by (job,instance) (\n  hrProcessorLoad{hrDeviceType=\"1.3.6.1.2.1.25.3.1.3\",job=~\"$job\",instance=~\"$instance\"}\n)\nor\navg by (job,instance) (\n  jnxOperatingCPU{jnxOperatingContentsIndex=\"9\", job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{instance}}: CPU utilization"
    },
    {
     "expr": "avg by (job,instance) (\n  # NX-OS:\n(\n  cpmCPUMemoryUsed{job=~\"$job\",instance=~\"$instance\"}\n  /\n  (cpmCPUMemoryUsed{job=~\"$job\",instance=~\"$instance\"} + cpmCPUMemoryFree{job=~\"$job\",instance=~\"$instance\"}) * 100\n)\nor\n# cisco CISCO-ENHANCED-MEMPOOL-MIB\n# cempMemPoolType=\"10\" - virtual memory, i.e in ASA(v).\n(\n  (\n    cempMemPoolUsed{job=~\"$job\",instance=~\"$instance\"}\n    /\n    (cempMemPoolUsed{job=~\"$job\",instance=~\"$instance\"} + cempMemPoolFree{job=~\"$job\",instance=~\"$instance\"}) * 100\n  ) * on (instance, cempMemPoolIndex, entPhysicalIndex) group_left () \n        (cempMemPoolType{job=~\"$job\",instance=~\"$instance\"} == 10)/10\n)\nor\n# cisco firmwares that supports only CISCO-MEMORY-POOL-MIB\n# ciscoMemoryPoolType=\"1\" - Processor\n(ciscoMemoryPoolUsed{ciscoMemoryPoolType=\"1\", job=~\"$job\",instance=~\"$instance\"}\n/\n(ciscoMemoryPoolUsed{ciscoMemoryPoolType=\"1\", job=~\"$job\",instance=~\"$instance\"} + ciscoMemoryPoolFree{ciscoMemoryPoolType=\"1\", job=~\"$job\",instance=~\"$instance\"}) * 100)\n\n)\nor\navg by (job,instance) (\n  hrStorageUsed{hrStorageDescr!~\".*(?i:(cache|buffer)).*\", hrStorageType=\"1.3.6.1.2.1.25.2.1.2\", job=~\"$job\",instance=~\"$instance\"}/hrStorageSize{hrStorageDescr!~\".*(?i:(cache|buffer)).*\", hrStorageType=\"1.3.6.1.2.1.25.2.1.2\", job=~\"$job\",instance=~\"$instance\"}*100\n\n)\nor\navg by (job,instance) (\n  hrStorageUsed{hrStorageDescr=\"main memory\",hrStorageIndex=\"65536\", job=~\"$job\",instance=~\"$instance\"}/hrStorageSize{hrStorageDescr=\"main memory\",hrStorageIndex=\"65536\", job=~\"$job\",instance=~\"$instance\"}*100\n\n)\nor\navg by (job,instance) (\n  jnxOperatingBuffer{jnxOperatingContentsIndex=\"9\", job=~\"$job\",instance=~\"$instance\"}\n)",
     "legendFormat": "{{instance}}: Memory utilization"
    },
    {
     "expr": "\n  (\n  sum by (job,instance) (\n  irate(ifHCOutOctets{job=~\"$job\",instance=~\"$instance\"} [$__rate_interval])\n)\n)*8\n\n# set max limit to workaround for TB-PB/sec spikes when counters are overloaded too quickly on very busy interfaces.\n<100*10^9",
     "legendFormat": "{{instance}}: transmitted"
    },
    {
     "expr": "\n  (\n  sum by (job,instance) (\n  irate(ifHCInOctets{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])\n)\n)*8\n\n# set max limit to workaround for TB-PB/sec spikes when counters are overloaded too quickly on very busy interfaces.\n<100*10^9",
     "legendFormat": "{{instance}}: received"
    },
    {
     "expr": "sum by (job,instance) (irate(ifOutErrors{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])) +\nsum by (job,instance) (irate(ifInErrors{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])) +\nsum by (job,instance) (irate(ifInDiscards{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])) +\nsum by (job,instance) (irate(ifOutDiscards{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))+ \nsum by (job,instance) (irate(ifInUnknownProtos{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))\n",
     "legendFormat": "{{instance}}: errors and drops"
    },
    {
     "expr": "count by (instance,job)(\n  count by (job,instance,alertname) (max_over_time(ALERTS{alertstate=\"firing\", severity=\"warning\", job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))\n  * on(job,instance) group_left group by (job,instance) (sysUpTime{job=~\"$job\",instance=~\"$instance\"})\n\n)",
     "legendFormat": "{{instance}}: Warnings"
    },
    {
     "expr": "count by (instance,job)(\n  count by (job,instance,alertname) (max_over_time(ALERTS{alertstate=\"firing\", severity=\"critical\", job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))\n  * on(job,instance) group_left group by (job,instance) (sysUpTime{job=~\"$job\",instance=~\"$instance\"})\n\n)",
     "legendFormat": "{{instance}}: Critical"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "timeseries",
   "description": "Network interface traffic out.\n",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "topk(25,\n  \n  (\n  sum by (job,instance) (\n  irate(ifHCOutOctets{job=~\"$job\",instance=~\"$instance\"} [$__rate_interval])\n)\n)*8\n\n# set max limit to workaround for TB-PB/sec spikes when counters are overloaded too quickly on very busy interfaces.\n<100*10^9\n)",
     "legendFormat": "{{instance}}: transmitted"
    },
    {
     "expr": "topk(25,\n  \n  (\n  sum by (job,instance) (\n  irate(ifHCInOctets{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])\n)\n)*8\n\n# set max limit to workaround for TB-PB/sec spikes when counters are overloaded too quickly on very busy interfaces.\n<100*10^9\n)",
     "legendFormat": "{{instance}}: received"
    }
   ]
  },
  {
   "title": "Network errors",
   "type": "timeseries",
   "description": "Network interface errors in.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "topk(25,\n  (\n  sum by (job,instance) (\n  irate(ifInErrors{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])\n)\n)>0\n)",
     "legendFormat": "{{instance}}: errors in"
    },
    {
     "expr": "topk(25,\n  (\n  sum by (job,instance) (\n  irate(ifOutErrors{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])\n)\n)>0\n)",
     "legendFormat": "{{instance}}: errors out"
    }
   ]
  },
  {
   "title": "Packets dropped",
   "type": "timeseries",
   "description": "Network interface discards in.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "topk(25,\n  (\n  sum by (job,instance) (\n  irate(ifInDiscards{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])\n)\n)>0\n)",
     "legendFormat": "{{instance}}: dropped in"
    },
    {
     "expr": "topk(25,\n  (\n  sum by (job,instance) (\n  irate(ifOutDiscards{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])\n)\n)>0\n)",
     "legendFormat": "{{instance}}: dropped out"
    },
    {
     "expr": "topk(25,\n  (\n  sum by (job,instance) (\n  irate(ifInUnknownProtos{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])\n)\n)>0\n)",
     "legendFormat": "{{instance}}: unknown dropped in"
    }
   ]
  },
  {
   "title": "Unicast",
   "type": "timeseries",
   "description": "Network interface unicast packets in.\n",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "topk(25,\n  (\n  sum by (job,instance) (\n  irate(ifHCInUcastPkts{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])\n)\n)>0\n)",
     "legendFormat": "{{instance}}: unicast in"
    },
    {
     "expr": "topk(25,\n  (\n  sum by (job,instance) (\n  irate(ifHCOutUcastPkts{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])\n)\n)>0\n)",
     "legendFormat": "{{instance}}: unicast out"
    }
   ]
  },
  {
   "title": "Broadcast",
   "type": "timeseries",
   "description": "Network interface broadcast packets in.\n",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "topk(25,\n  (\n  sum by (job,instance) (\n  irate(ifHCInBroadcastPkts{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])\n)\n)>0\n)",
     "legendFormat": "{{instance}}: broadcast in"
    },
    {
     "expr": "topk(25,\n  (\n  sum by (job,instance) (\n  irate(ifHCOutBroadcastPkts{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])\n)\n)>0\n)",
     "legendFormat": "{{instance}}: broadcast out"
    }
   ]
  },
  {
   "title": "Multicast",
   "type": "timeseries",
   "description": "Network interface multicast packets in.\n",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "topk(25,\n  (\n  sum by (job,instance) (\n  irate(ifHCInMulticastPkts{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])\n)\n)>0\n)",
     "legendFormat": "{{instance}}: multicast in"
    },
    {
     "expr": "topk(25,\n  (\n  sum by (job,instance) (\n  irate(ifHCOutMulticastPkts{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])\n)\n)>0\n)",
     "legendFormat": "{{instance}}: multicast out"
    }
   ]
  }
 ]
}