{
 "title": "Wildfly datasource",
 "tags": [ "wildfly-mixin" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(wildfly_batch_jberet_active_count{}, job)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(wildfly_batch_jberet_active_count{job=~\"$job\"}, cluster)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(wildfly_batch_jberet_active_count{job=~\"$job\",cluster=~\"$cluster\"}, instance)"
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" },
   {
    "name": "data_source",
    "query": "label_values(wildfly_datasources_pool_in_use_count{job=~\"$job\",cluster=~\"$cluster\"}, data_source)"
   }
  ]
 },
 "panels": [
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Active connections",
   "type": "timeseries",
   "description": "Active connections to the datasource over time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "wildfly_datasources_pool_in_use_count{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",data_source=~\"$data_source\"}",
     "legendFormat": "{{data_source}}"
    }
   ]
  },
  {
   "title": "Idle connections",
   "type": "timeseries",
   "description": "Idle connections to the datasource over time",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "wildfly_datasources_pool_idle_count{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",data_source=~\"$data_source\"}",
     "legendFormat": "{{data_source}}"
    }
   ]
  },
  { "title": "Transactions", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 9 } },
  {
   "title": "Created transactions",
   "type": "timeseries",
   "description": "Number of transactions that were created over time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "increase(wildfly_transactions_number_of_transactions_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "In-flight transactions",
   "type": "timeseries",
   "description": "Number of transactions that are in-flight over time",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "wildfly_transactions_number_of_inflight_transactions{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Aborted transactions",
   "type": "timeseries",
   "description": "Number of transactions that have been aborted over time",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "increase(wildfly_transactions_number_of_aborted_transactions_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}