{
 "title": "Wildfly overview",
 "tags": [ "wildfly-mixin" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(wildfly_batch_jberet_active_count{}, job)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(wildfly_batch_jberet_active_count{job=~\"$job\"}, cluster)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(wildfly_batch_jberet_active_count{job=~\"$job\",cluster=~\"$cluster\"}, instance)"
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" },
   {
    "name": "server",
    "query": "label_values(wildfly_undertow_request_count_total{job=~\"$job\",cluster=~\"$cluster\"}, server)"
   },
   {
    "name": "deployment",
    "query": "label_values(wildfly_undertow_active_sessions{job=~\"$job\",cluster=~\"$cluster\"}, deployment)"
   }
  ]
 },
 "panels": [
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Requests",
   "type": "timeseries",
   "description": "Requests rate over time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(wildfly_undertow_request_count_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",server=~\"$server\"}[$__rate_interval])",
     "legendFormat": "{{server}} - {{http_listener}}{{https_listener}}"
    }
   ]
  },
  {
   "title": "Request errors",
   "type": "timeseries",
   "description": "Rate of requests that result in 500 over time",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(wildfly_undertow_error_count_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",server=~\"$server\"}[$__rate_interval])",
     "legendFormat": "{{server}} - {{http_listener}}{{https_listener}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 9 } },
  {
   "title": "Network received throughput",
   "type": "timeseries",
   "description": "Throughput rate of data received over time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(wildfly_undertow_bytes_received_total_bytes{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",server=~\"$server\"}[$__rate_interval])",
     "legendFormat": "{{server}} - {{http_listener}}{{https_listener}}"
    }
   ]
  },
  {
   "title": "Network sent throughput",
   "type": "timeseries",
   "description": "Throughput rate of data sent over time",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(wildfly_undertow_bytes_sent_total_bytes{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",server=~\"$server\"}[$__rate_interval])",
     "legendFormat": "{{server}} - {{http_listener}}{{https_listener}}"
    }
   ]
  },
  { "title": "Sessions", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 18 } },
  {
   "title": "Active sessions",
   "type": "timeseries",
   "description": "Number of active sessions to deployment over time",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "wildfly_undertow_active_sessions{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",deployment=~\"$deployment\"}",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Expired sessions",
   "type": "timeseries",
   "description": "Number of sessions that have expired for a deployment over time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "increase(wildfly_undertow_expired_sessions_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",deployment=~\"$deployment\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Rejected sessions",
   "type": "timeseries",
   "description": "Number of sessions that have been rejected from a deployment over time",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "increase(wildfly_undertow_rejected_sessions_total{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",deployment=~\"$deployment\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{deployment}}"
    }
   ]
  }
 ]
}