{
 "title": "Apache Hadoop NameNode overview",
 "tags": [ "apache-hadoop-mixin" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(hadoop_namenode_blockstotal{}, job)"
   },
   {
    "name": "hadoop_cluster",
    "label": "Hadoop cluster",
    "query": "label_values(hadoop_namenode_blockstotal{job=~\"$job\"}, hadoop_cluster)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(hadoop_namenode_blockstotal{job=~\"$job\",hadoop_cluster=~\"$hadoop_cluster\"}, cluster)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(hadoop_namenode_blockstotal{job=~\"$job\",hadoop_cluster=~\"$hadoop_cluster\",cluster=~\"$cluster\"}, instance)"
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" }
  ]
 },
 "panels": [
  { "title": "NameNode overview", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "DataNode state",
   "type": "piechart",
   "description": "The DataNodes current state.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "hadoop_namenode_numlivedatanodes{job=~\"$job\",hadoop_cluster=~\"$hadoop_cluster\",cluster=~\"$cluster\",instance=~\"$instance\", name=\"FSNamesystem\"}",
     "legendFormat": "{{hadoop_cluster}} - {{instance}} - live DataNodes"
    },
    {
     "expr": "hadoop_namenode_numdeaddatanodes{job=~\"$job\",hadoop_cluster=~\"$hadoop_cluster\",cluster=~\"$cluster\",instance=~\"$instance\", name=\"FSNamesystem\"}",
     "legendFormat": "{{hadoop_cluster}} - {{instance}} - dead DataNodes"
    },
    {
     "expr": "hadoop_namenode_numstaledatanodes{job=~\"$job\",hadoop_cluster=~\"$hadoop_cluster\",cluster=~\"$cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{hadoop_cluster}} - {{instance}} - stale DataNodes"
    },
    {
     "expr": "hadoop_namenode_numdecommissioningdatanodes{job=~\"$job\",hadoop_cluster=~\"$hadoop_cluster\",cluster=~\"$cluster\",instance=~\"$instance\", name=\"FSNamesystem\"}",
     "legendFormat": "{{hadoop_cluster}} - {{instance}} - decommissioning DataNodes"
    }
   ]
  },
  {
   "title": "Capacity utilization",
   "type": "timeseries",
   "description": "The storage utilization of the NameNode.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * hadoop_namenode_capacityused{job=~\"$job\",hadoop_cluster=~\"$hadoop_cluster\",cluster=~\"$cluster\",instance=~\"$instance\", name=\"FSNamesystem\"} / clamp_min(hadoop_namenode_capacitytotal{job=~\"$job\",hadoop_cluster=~\"$hadoop_cluster\",cluster=~\"$cluster\",instance=~\"$instance\", name=\"FSNamesystem\"}, 1)",
     "legendFormat": "{{hadoop_cluster}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Total blocks",
   "type": "timeseries",
   "description": "Total number of blocks managed by the NameNode.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "hadoop_namenode_blockstotal{job=~\"$job\",hadoop_cluster=~\"$hadoop_cluster\",cluster=~\"$cluster\",instance=~\"$instance\", name=\"FSNamesystem\"}",
     "legendFormat": "{{hadoop_cluster}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Missing blocks",
   "type": "timeseries",
   "description": "Number of blocks reported by DataNodes as missing.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "hadoop_namenode_missingblocks{job=~\"$job\",hadoop_cluster=~\"$hadoop_cluster\",cluster=~\"$cluster\",instance=~\"$instance\", name=\"FSNamesystem\"}",
     "legendFormat": "{{hadoop_cluster}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Under-replicated blocks",
   "type": "timeseries",
   "description": "Number of blocks that are under-replicated.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "hadoop_namenode_underreplicatedblocks{job=~\"$job\",hadoop_cluster=~\"$hadoop_cluster\",cluster=~\"$cluster\",instance=~\"$instance\", name=\"FSNamesystem\"}",
     "legendFormat": "{{hadoop_cluster}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Transactions since last checkpoint",
   "type": "timeseries",
   "description": "Number of transactions processed by the NameNode since the last checkpoint.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "hadoop_namenode_transactionssincelastcheckpoint{job=~\"$job\",hadoop_cluster=~\"$hadoop_cluster\",cluster=~\"$cluster\",instance=~\"$instance\", name=\"FSNamesystem\"}",
     "legendFormat": "{{hadoop_cluster}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Volume failures",
   "type": "timeseries",
   "description": "The recent increase in number of volume failures on all DataNodes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "increase(hadoop_namenode_volumefailurestotal{job=~\"$job\",hadoop_cluster=~\"$hadoop_cluster\",cluster=~\"$cluster\",instance=~\"$instance\", name=\"FSNamesystem\"}[$__interval:] offset -$__interval)",
     "legendFormat": "{{hadoop_cluster}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Total files",
   "type": "timeseries",
   "description": "Total number of files managed by the NameNode.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "hadoop_namenode_filestotal{job=~\"$job\",hadoop_cluster=~\"$hadoop_cluster\",cluster=~\"$cluster\",instance=~\"$instance\", name=\"FSNamesystem\"}",
     "legendFormat": "{{hadoop_cluster}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Total load",
   "type": "timeseries",
   "description": "Total load on the NameNode.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "hadoop_namenode_totalload{job=~\"$job\",hadoop_cluster=~\"$hadoop_cluster\",cluster=~\"$cluster\",instance=~\"$instance\", name=\"FSNamesystem\"}",
     "legendFormat": "{{hadoop_cluster}} - {{instance}}"
    }
   ]
  }
 ]
}