{
 "title": "IBM MQ queue manager overview",
 "tags": [ "ibm-mq-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(ibmmq_qmgr_commit_count{}, cluster)"
   },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(ibmmq_qmgr_commit_count{cluster=~\"$cluster\"}, job)"
   },
   {
    "name": "mq_cluster",
    "label": "MQ cluster",
    "query": "label_values(ibmmq_qmgr_commit_count{cluster=~\"$cluster\",job=~\"$job\"}, mq_cluster)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(ibmmq_qmgr_commit_count{cluster=~\"$cluster\",job=~\"$job\",mq_cluster=~\"$mq_cluster\"}, instance)"
   },
   {
    "name": "qmgr",
    "label": "Queue manager",
    "query": "label_values(ibmmq_qmgr_commit_count{cluster=~\"$cluster\",job=~\"$job\",mq_cluster=~\"$mq_cluster\",instance=~\"$instance\"}, qmgr)"
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" }
  ]
 },
 "panels": [
  { "title": "Queue manager overview", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Active listeners",
   "type": "stat",
   "description": "The number of active listeners for the queue manager.",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ibmmq_qmgr_active_listeners{cluster=~\"$cluster\",job=~\"$job\",mq_cluster=~\"$mq_cluster\",instance=~\"$instance\",qmgr=~\"$qmgr\"}"
    }
   ]
  },
  {
   "title": "Active connections",
   "type": "stat",
   "description": "The number of active connections for the queue manager.",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ibmmq_qmgr_connection_count{cluster=~\"$cluster\",job=~\"$job\",mq_cluster=~\"$mq_cluster\",instance=~\"$instance\",qmgr=~\"$qmgr\"}"
    }
   ]
  },
  {
   "title": "Queues",
   "type": "stat",
   "description": "The unique number of queues being managed by the queue manager.",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(ibmmq_queue_depth{cluster=~\"$cluster\",job=~\"$job\",mq_cluster=~\"$mq_cluster\",instance=~\"$instance\",qmgr=~\"$qmgr\"}) by (queue, mq_cluster, qmgr))"
    }
   ]
  },
  {
   "title": "Estimated memory utilization",
   "type": "timeseries",
   "description": "The estimated memory usage of the queue managers.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(ibmmq_qmgr_ram_total_estimate_for_queue_manager_bytes{cluster=~\"$cluster\",job=~\"$job\",mq_cluster=~\"$mq_cluster\",instance=~\"$instance\",qmgr=~\"$qmgr\"}/ibmmq_qmgr_ram_total_bytes{cluster=~\"$cluster\",job=~\"$job\",mq_cluster=~\"$mq_cluster\",instance=~\"$instance\",qmgr=~\"$qmgr\"})",
     "legendFormat": "{{mq_cluster}} - {{qmgr}}"
    }
   ]
  },
  {
   "title": "Queue manager status",
   "type": "table",
   "description": "A table showing the status and uptime of the queue manager.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "ibmmq_qmgr_uptime{cluster=~\"$cluster\",job=~\"$job\",mq_cluster=~\"$mq_cluster\",instance=~\"$instance\",qmgr=~\"$qmgr\"}",
     "legendFormat": "Uptime"
    },
    {
     "expr": "ibmmq_qmgr_status{cluster=~\"$cluster\",job=~\"$job\",mq_cluster=~\"$mq_cluster\",instance=~\"$instance\",qmgr=~\"$qmgr\"}",
     "legendFormat": "Status"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "description": "The system/user CPU usage of the queue manager.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "ibmmq_qmgr_user_cpu_time_percentage{cluster=~\"$cluster\",job=~\"$job\",mq_cluster=~\"$mq_cluster\",instance=~\"$instance\",qmgr=~\"$qmgr\"}",
     "legendFormat": "{{mq_cluster}} - {{qmgr}} - user"
    },
    {
     "expr": "ibmmq_qmgr_system_cpu_time_percentage{cluster=~\"$cluster\",job=~\"$job\",mq_cluster=~\"$mq_cluster\",instance=~\"$instance\",qmgr=~\"$qmgr\"}",
     "legendFormat": "{{mq_cluster}} - {{qmgr}} - system"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "timeseries",
   "description": "The disk allocated to the queue manager that is being used.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "ibmmq_qmgr_queue_manager_file_system_in_use_bytes{cluster=~\"$cluster\",job=~\"$job\",mq_cluster=~\"$mq_cluster\",instance=~\"$instance\",qmgr=~\"$qmgr\"}",
     "legendFormat": "{{mq_cluster}} - {{qmgr}}"
    }
   ]
  },
  {
   "title": "Commits",
   "type": "timeseries",
   "description": "The commits of the queue manager.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "ibmmq_qmgr_commit_count{cluster=~\"$cluster\",job=~\"$job\",mq_cluster=~\"$mq_cluster\",instance=~\"$instance\",qmgr=~\"$qmgr\"}",
     "legendFormat": "{{mq_cluster}} - {{qmgr}}"
    }
   ]
  },
  {
   "title": "Publish throughput",
   "type": "timeseries",
   "description": "The amount of data being pushed from the queue manager to subscribers.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "ibmmq_qmgr_published_to_subscribers_bytes{cluster=~\"$cluster\",job=~\"$job\",mq_cluster=~\"$mq_cluster\",instance=~\"$instance\",qmgr=~\"$qmgr\"}",
     "legendFormat": "{{mq_cluster}} - {{qmgr}}"
    }
   ]
  },
  {
   "title": "Published messages",
   "type": "timeseries",
   "description": "The number of messages being published by the queue manager.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "targets": [
    {
     "expr": "ibmmq_qmgr_published_to_subscribers_message_count{cluster=~\"$cluster\",job=~\"$job\",mq_cluster=~\"$mq_cluster\",instance=~\"$instance\",qmgr=~\"$qmgr\"}",
     "legendFormat": "{{mq_cluster}} - {{qmgr}}"
    }
   ]
  },
  {
   "title": "Expired messages",
   "type": "timeseries",
   "description": "The expired messages of the queue manager.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "ibmmq_qmgr_expired_message_count{cluster=~\"$cluster\",job=~\"$job\",mq_cluster=~\"$mq_cluster\",instance=~\"$instance\",qmgr=~\"$qmgr\"}",
     "legendFormat": "{{mq_cluster}} - {{qmgr}}"
    }
   ]
  },
  {
   "title": "Queue operations",
   "type": "timeseries",
   "description": "The number of queue operations of the queue manager.",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "operations" } },
   "targets": [
    {
     "expr": "sum by (mq_cluster, qmgr, job) (ibmmq_queue_mqset_count{cluster=~\"$cluster\",job=~\"$job\",mq_cluster=~\"$mq_cluster\",instance=~\"$instance\",qmgr=~\"$qmgr\"})",
     "legendFormat": "{{mq_cluster}} - {{qmgr}} - MQSET"
    },
    {
     "expr": "sum by (mq_cluster, qmgr, job) (ibmmq_queue_mqinq_count{cluster=~\"$cluster\",job=~\"$job\",mq_cluster=~\"$mq_cluster\",instance=~\"$instance\",qmgr=~\"$qmgr\"})",
     "legendFormat": "{{mq_cluster}} - {{qmgr}} - MQINQ"
    },
    {
     "expr": "sum by (mq_cluster, qmgr, job) (ibmmq_queue_mqget_count{cluster=~\"$cluster\",job=~\"$job\",mq_cluster=~\"$mq_cluster\",instance=~\"$instance\",qmgr=~\"$qmgr\"})",
     "legendFormat": "{{mq_cluster}} - {{qmgr}} - MQGET"
    },
    {
     "expr": "sum by (mq_cluster, qmgr, job) (ibmmq_queue_mqopen_count{cluster=~\"$cluster\",job=~\"$job\",mq_cluster=~\"$mq_cluster\",instance=~\"$instance\",qmgr=~\"$qmgr\"})",
     "legendFormat": "{{mq_cluster}} - {{qmgr}} - MQOPEN"
    },
    {
     "expr": "sum by (mq_cluster, qmgr, job) (ibmmq_queue_mqclose_count{cluster=~\"$cluster\",job=~\"$job\",mq_cluster=~\"$mq_cluster\",instance=~\"$instance\",qmgr=~\"$qmgr\"})",
     "legendFormat": "{{mq_cluster}} - {{qmgr}} - MQCLOSE"
    },
    {
     "expr": "sum by (mq_cluster, qmgr, job) (ibmmq_queue_mqput_mqput1_count{cluster=~\"$cluster\",job=~\"$job\",mq_cluster=~\"$mq_cluster\",instance=~\"$instance\",qmgr=~\"$qmgr\"})",
     "legendFormat": "{{mq_cluster}} - {{qmgr}} - MQPUT/MQPUT1"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 33 } },
  {
   "title": "Log latency",
   "type": "timeseries",
   "description": "The recent latency of log writes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "ibmmq_qmgr_log_write_latency_seconds{cluster=~\"$cluster\",job=~\"$job\",mq_cluster=~\"$mq_cluster\",instance=~\"$instance\",qmgr=~\"$qmgr\"}",
     "legendFormat": "{{mq_cluster}} - {{qmgr}}"
    }
   ]
  },
  {
   "title": "Log usage",
   "type": "timeseries",
   "description": "The amount of data on the filesystem occupied by queue manager logs.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "ibmmq_qmgr_log_in_use_bytes{cluster=~\"$cluster\",job=~\"$job\",mq_cluster=~\"$mq_cluster\",instance=~\"$instance\",qmgr=~\"$qmgr\"}",
     "legendFormat": "{{mq_cluster}} - {{qmgr}}"
    }
   ]
  }
 ]
}