{
 "title": "IBM MQ queue overview",
 "tags": [ "ibm-mq-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(ibmmq_qmgr_commit_count{}, cluster)"
   },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(ibmmq_qmgr_commit_count{cluster=~\"$cluster\"}, job)"
   },
   {
    "name": "mq_cluster",
    "label": "MQ cluster",
    "query": "label_values(ibmmq_qmgr_commit_count{cluster=~\"$cluster\",job=~\"$job\"}, mq_cluster)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(ibmmq_qmgr_commit_count{cluster=~\"$cluster\",job=~\"$job\",mq_cluster=~\"$mq_cluster\"}, instance)"
   },
   {
    "name": "qmgr",
    "label": "Queue manager",
    "query": "label_values(ibmmq_qmgr_commit_count{cluster=~\"$cluster\",job=~\"$job\",mq_cluster=~\"$mq_cluster\",instance=~\"$instance\"}, qmgr)"
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" },
   {
    "name": "queue",
    "label": "Queue",
    "query": "label_values(ibmmq_queue_average_queue_time_seconds, queue)"
   }
  ]
 },
 "panels": [
  { "title": "Queue overview", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Average queue time",
   "type": "timeseries",
   "description": "The average amount of time a message spends in the queue.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "ibmmq_queue_average_queue_time_seconds{cluster=~\"$cluster\",job=~\"$job\",mq_cluster=~\"$mq_cluster\",instance=~\"$instance\",qmgr=~\"$qmgr\", queue=~\"$queue\"}",
     "legendFormat": "{{mq_cluster}} - {{qmgr}} - {{queue}}"
    }
   ]
  },
  {
   "title": "Expired messages",
   "type": "timeseries",
   "description": "The expired messages of the queue.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ibmmq_queue_expired_messages{cluster=~\"$cluster\",job=~\"$job\",mq_cluster=~\"$mq_cluster\",instance=~\"$instance\",qmgr=~\"$qmgr\", queue=~\"$queue\"}",
     "legendFormat": "{{mq_cluster}} - {{qmgr}} - {{queue}}"
    }
   ]
  },
  {
   "title": "Queue depth",
   "type": "timeseries",
   "description": "The depth of the queue.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ibmmq_queue_depth{cluster=~\"$cluster\",job=~\"$job\",mq_cluster=~\"$mq_cluster\",instance=~\"$instance\",qmgr=~\"$qmgr\", queue=~\"$queue\"}",
     "legendFormat": "{{mq_cluster}} - {{qmgr}} - {{queue}}"
    }
   ]
  },
  {
   "title": "Operation throughput",
   "type": "timeseries",
   "description": "The amount of throughput going through the queue via MQGETs and MQPUTs.",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "ibmmq_queue_mqget_bytes{cluster=~\"$cluster\",job=~\"$job\",mq_cluster=~\"$mq_cluster\",instance=~\"$instance\",qmgr=~\"$qmgr\", queue=~\"$queue\"}",
     "legendFormat": "{{qmgr}} - {{queue}} - MQGET"
    },
    {
     "expr": "ibmmq_queue_mqput_bytes{cluster=~\"$cluster\",job=~\"$job\",mq_cluster=~\"$mq_cluster\",instance=~\"$instance\",qmgr=~\"$qmgr\", queue=~\"$queue\"}",
     "legendFormat": "{{qmgr}} - {{queue}} - MQPUT"
    }
   ]
  },
  {
   "title": "Operations",
   "type": "timeseries",
   "description": "The number of queue operations of the queue manager.",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "operations" } },
   "targets": [
    {
     "expr": "ibmmq_queue_mqset_count{cluster=~\"$cluster\",job=~\"$job\",mq_cluster=~\"$mq_cluster\",instance=~\"$instance\",qmgr=~\"$qmgr\", queue=~\"$queue\"}",
     "legendFormat": "{{qmgr}} - {{queue}} - MQSET"
    },
    {
     "expr": "ibmmq_queue_mqinq_count{cluster=~\"$cluster\",job=~\"$job\",mq_cluster=~\"$mq_cluster\",instance=~\"$instance\",qmgr=~\"$qmgr\", queue=~\"$queue\"}",
     "legendFormat": "{{qmgr}} - {{queue}} - MQINQ"
    },
    {
     "expr": "ibmmq_queue_mqget_count{cluster=~\"$cluster\",job=~\"$job\",mq_cluster=~\"$mq_cluster\",instance=~\"$instance\",qmgr=~\"$qmgr\", queue=~\"$queue\"}",
     "legendFormat": "{{qmgr}} - {{queue}} - MQGET"
    },
    {
     "expr": "ibmmq_queue_mqopen_count{cluster=~\"$cluster\",job=~\"$job\",mq_cluster=~\"$mq_cluster\",instance=~\"$instance\",qmgr=~\"$qmgr\", queue=~\"$queue\"}",
     "legendFormat": "{{qmgr}} - {{queue}} - MQOPEN"
    },
    {
     "expr": "ibmmq_queue_mqclose_count{cluster=~\"$cluster\",job=~\"$job\",mq_cluster=~\"$mq_cluster\",instance=~\"$instance\",qmgr=~\"$qmgr\", queue=~\"$queue\"}",
     "legendFormat": "{{qmgr}} - {{queue}} - MQCLOSE"
    },
    {
     "expr": "ibmmq_queue_mqput_mqput1_count{cluster=~\"$cluster\",job=~\"$job\",mq_cluster=~\"$mq_cluster\",instance=~\"$instance\",qmgr=~\"$qmgr\", queue=~\"$queue\"}",
     "legendFormat": "{{qmgr}} - {{queue}} - MQPUT/MQPUT1"
    }
   ]
  }
 ]
}