{
 "title": "IBM MQ cluster overview",
 "tags": [ "ibm-mq-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(ibmmq_qmgr_commit_count{}, cluster)"
   },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(ibmmq_qmgr_commit_count{cluster=~\"$cluster\"}, job)"
   },
   {
    "name": "mq_cluster",
    "label": "MQ cluster",
    "query": "label_values(ibmmq_qmgr_commit_count{cluster=~\"$cluster\",job=~\"$job\"}, mq_cluster)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(ibmmq_qmgr_commit_count{cluster=~\"$cluster\",job=~\"$job\",mq_cluster=~\"$mq_cluster\"}, instance)"
   },
   {
    "name": "qmgr",
    "label": "Queue manager",
    "query": "label_values(ibmmq_qmgr_commit_count{cluster=~\"$cluster\",job=~\"$job\",mq_cluster=~\"$mq_cluster\",instance=~\"$instance\"}, qmgr)"
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" }
  ]
 },
 "panels": [
  { "title": "Cluster overview", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Clusters",
   "type": "stat",
   "description": "The unique number of clusters being reported.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(ibmmq_qmgr_commit_count{cluster=~\"$cluster\",job=~\"$job\",mq_cluster=~\"$mq_cluster\",instance=~\"$instance\",qmgr=~\"$qmgr\"}) by (mq_cluster))",
     "legendFormat": "{{job}} - {{mq_cluster}}"
    }
   ]
  },
  {
   "title": "Queue managers",
   "type": "stat",
   "description": "The unique number of queue managers in the cluster being reported.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(ibmmq_qmgr_commit_count{cluster=~\"$cluster\",job=~\"$job\",mq_cluster=~\"$mq_cluster\",instance=~\"$instance\",qmgr=~\"$qmgr\"}) by (qmgr, mq_cluster))",
     "legendFormat": "{{}}"
    }
   ]
  },
  {
   "title": "Topics",
   "type": "stat",
   "description": "The unique number of topics in the cluster.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(ibmmq_topic_messages_received{cluster=~\"$cluster\",job=~\"$job\",mq_cluster=~\"$mq_cluster\",instance=~\"$instance\",qmgr=~\"$qmgr\"}) by (topic, mq_cluster))",
     "legendFormat": "{{job}} - {{mq_cluster}}"
    }
   ]
  },
  {
   "title": "Queues",
   "type": "stat",
   "description": "The unique number of queues in the cluster.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(ibmmq_queue_depth{cluster=~\"$cluster\",job=~\"$job\",mq_cluster=~\"$mq_cluster\",instance=~\"$instance\",qmgr=~\"$qmgr\"}) by (queue, mq_cluster))"
    }
   ]
  },
  {
   "title": "Cluster status",
   "type": "table",
   "description": "The status of the cluster.",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "ibmmq_cluster_suspend{cluster=~\"$cluster\",job=~\"$job\",mq_cluster=~\"$mq_cluster\",instance=~\"$instance\",qmgr=~\"$qmgr\"}",
     "legendFormat": "{{job}} - {{mq_cluster}}"
    }
   ]
  },
  {
   "title": "Queue operations",
   "type": "piechart",
   "description": "The number of queue operations of the cluster.",
   "gridPos": { "h": 14, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "operations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (mq_cluster) (ibmmq_queue_mqset_count{cluster=~\"$cluster\",job=~\"$job\",mq_cluster=~\"$mq_cluster\",instance=~\"$instance\",qmgr=~\"$qmgr\"})",
     "legendFormat": "MQSET"
    },
    {
     "expr": "sum by (mq_cluster) (ibmmq_queue_mqinq_count{cluster=~\"$cluster\",job=~\"$job\",mq_cluster=~\"$mq_cluster\",instance=~\"$instance\",qmgr=~\"$qmgr\"})",
     "legendFormat": "MQINQ"
    },
    {
     "expr": "sum by (mq_cluster) (ibmmq_queue_mqget_count{cluster=~\"$cluster\",job=~\"$job\",mq_cluster=~\"$mq_cluster\",instance=~\"$instance\",qmgr=~\"$qmgr\"})",
     "legendFormat": "MQGET"
    },
    {
     "expr": "sum by (mq_cluster) (ibmmq_queue_mqopen_count{cluster=~\"$cluster\",job=~\"$job\",mq_cluster=~\"$mq_cluster\",instance=~\"$instance\",qmgr=~\"$qmgr\"})",
     "legendFormat": "MQOPEN"
    },
    {
     "expr": "sum by (mq_cluster) (ibmmq_queue_mqclose_count{cluster=~\"$cluster\",job=~\"$job\",mq_cluster=~\"$mq_cluster\",instance=~\"$instance\",qmgr=~\"$qmgr\"})",
     "legendFormat": "MQCLOSE"
    },
    {
     "expr": "sum by (mq_cluster) (ibmmq_queue_mqput_mqput1_count{cluster=~\"$cluster\",job=~\"$job\",mq_cluster=~\"$mq_cluster\",instance=~\"$instance\",qmgr=~\"$qmgr\"})",
     "legendFormat": "MQPUT/MQPUT1"
    }
   ]
  },
  {
   "title": "Queue manager status",
   "type": "table",
   "description": "The queue managers of the cluster displayed in a table.",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "ibmmq_qmgr_status{cluster=~\"$cluster\",job=~\"$job\",mq_cluster=~\"$mq_cluster\",instance=~\"$instance\",qmgr=~\"$qmgr\"}"
    }
   ]
  },
  {
   "title": "Transmission queue time",
   "type": "timeseries",
   "description": "The time it takes for the messages to get through the transmission queue. (Long) - total time taken for messages to be transmitted over the channel, (Short) - an average, minimum, or maximum time taken to transmit messages over the channel in recent intervals.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "ibmmq_channel_xmitq_time_short{type=\"SENDER\", cluster=~\"$cluster\",job=~\"$job\",mq_cluster=~\"$mq_cluster\",instance=~\"$instance\",qmgr=~\"$qmgr\"}",
     "legendFormat": "{{channel}} - short"
    },
    {
     "expr": "ibmmq_channel_xmitq_time_long{type=~\"SENDER\", cluster=~\"$cluster\",job=~\"$job\",mq_cluster=~\"$mq_cluster\",instance=~\"$instance\",qmgr=~\"$qmgr\"}",
     "legendFormat": "{{channel}} - long"
    }
   ]
  }
 ]
}