{
 "title": "Gitea Overview",
 "tags": [ "gitea" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "job",
    "label": "job",
    "query": "label_values(gitea_organizations, job)"
   },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(gitea_organizations{job=\"$job\"}, instance)"
   },
   { "name": "agg_interval", "label": "aggregation interval", "query": "1m,10m,1h,1d,7d" }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 0, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Gitea stats",
   "type": "stat",
   "gridPos": { "h": 4, "w": 16, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gitea_organizations{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Organizations"
    },
    {
     "expr": "gitea_teams{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Teams"
    },
    {
     "expr": "gitea_users{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Users"
    },
    {
     "expr": "gitea_repositories{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Repositories"
    },
    {
     "expr": "gitea_milestones{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Milestones"
    },
    {
     "expr": "gitea_stars{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Stars"
    },
    {
     "expr": "gitea_releases{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Releases"
    },
    {
     "expr": "gitea_issues_open{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Issues opened"
    },
    {
     "expr": "gitea_issues_closed{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Issues closed"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "time()-process_start_time_seconds{job=~\"$job\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=~\"$job\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])*100"
    }
   ]
  },
  {
   "title": "File descriptors usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{job=~\"$job\", instance=~\"$instance\"}"
    },
    {
     "expr": "process_max_fds{job=~\"$job\", instance=~\"$instance\"}"
    }
   ]
  },
  { "title": "Changes", "type": "row", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Changes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "panelId": 200 }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "changes(process_start_time_seconds{job=~\"$job\", instance=~\"$instance\"}[$__interval]) > 0",
     "legendFormat": "Restarts"
    },
    {
     "expr": "floor(delta(gitea_organizations{job=~\"$job\", instance=~\"$instance\"}[$__interval])) > 0",
     "legendFormat": "Organizations"
    },
    {
     "expr": "floor(delta(gitea_teams{job=~\"$job\", instance=~\"$instance\"}[$__interval])) > 0",
     "legendFormat": "Teams"
    },
    {
     "expr": "floor(delta(gitea_users{job=~\"$job\", instance=~\"$instance\"}[$__interval])) > 0",
     "legendFormat": "Users"
    },
    {
     "expr": "floor(delta(gitea_repositories{job=~\"$job\", instance=~\"$instance\"}[$__interval])) > 0",
     "legendFormat": "Repositories"
    },
    {
     "expr": "floor(delta(gitea_milestones{job=~\"$job\", instance=~\"$instance\"}[$__interval])) > 0",
     "legendFormat": "Milestones"
    },
    {
     "expr": "floor(delta(gitea_stars{job=~\"$job\", instance=~\"$instance\"}[$__interval])) > 0",
     "legendFormat": "Stars"
    },
    {
     "expr": "floor(delta(gitea_releases{job=~\"$job\", instance=~\"$instance\"}[$__interval])) > 0",
     "legendFormat": "Releases"
    },
    {
     "expr": "floor(delta(gitea_issues_open{job=~\"$job\", instance=~\"$instance\"}[$__interval])) > 0",
     "legendFormat": "Issues opened"
    },
    {
     "expr": "floor(delta(gitea_issues_closed{job=~\"$job\", instance=~\"$instance\"}[$__interval])) > 0",
     "legendFormat": "Issues closed"
    }
   ]
  },
  {
   "title": "Issues by repository",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "panelId": 210 }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "floor(increase(gitea_issues_by_repository{job=~\"$job\", instance=~\"$instance\"}[$__interval])) > 0",
     "legendFormat": "{{ repository }}"
    }
   ]
  },
  {
   "title": "Issues by labels",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "panelId": 220 }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "floor(increase(gitea_issues_by_label{job=~\"$job\", instance=~\"$instance\"}[$__interval])) > 0",
     "legendFormat": "{{ label }}"
    }
   ]
  }
 ]
}